// packages/@fex-design/components/react/src/primitive/message/message-context.ts
import type { MessageSide } from '@fex-design/core/message/types'
import { createContext, use } from 'react'

export interface MessageContextValue {
  side: MessageSide
  busy: boolean
}

export const MessageContext = createContext<MessageContextValue | null>(null)

export function useMessageContext() {
  return use(MessageContext)
}

// packages/@fex-design/components/solid/src/primitive/message/message-context.ts
import type { MessageSide } from '@fex-design/core/message/types'
import { createContext, useContext, type Accessor } from 'solid-js'

export interface MessageContextValue {
  side: Accessor<MessageSide>
  busy: Accessor<boolean>
}

export const MessageContext = createContext<MessageContextValue>()

export function useMessageContext() {
  const context = useContext(MessageContext)
  return context
}
