// apps/react-app/src/pages/Bubble/popover-demo.tsx
import { Bubble, BubbleContent } from '@fex-design/react/primitive/bubble'
import * as Popover from '@fex-design/react/primitive/popover'
import { Card } from '@fex-design/react/ui/card'
export function PopoverDemo() {
  return (
    <Card
      title="Popover"
      description="Compose the existing Popover for details without adding overlay behavior to Bubble."
    >
      <Popover.PopoverRoot placement="bottomLeft" arrow>
        <Popover.PopoverTrigger>
          {(triggerProps) => (
            <Bubble variant="danger">
              <BubbleContent
                render={({ props }) => (
                  <button {...props} {...triggerProps}>
                    Failed to run the command. Show details.
                  </button>
                )}
              />
            </Bubble>
          )}
        </Popover.PopoverTrigger>
        <Popover.PopoverPortal>
          <Popover.PopoverContent>
            <Popover.PopoverArrow />
            <Popover.PopoverHeader className="w-72">
              <Popover.PopoverTitle>Command error</Popover.PopoverTitle>
              <Popover.PopoverDescription>
                Dependency installation exited with code 1.
              </Popover.PopoverDescription>
            </Popover.PopoverHeader>
          </Popover.PopoverContent>
        </Popover.PopoverPortal>
      </Popover.PopoverRoot>
    </Card>
  )
}

// apps/vue-app/src/pages/Bubble/popover-demo.vue
<script setup lang="ts">
import { Bubble, BubbleContent } from '@fex-design/vue/primitive/bubble'
import {
  PopoverArrow,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverPortal,
  PopoverRoot,
  PopoverTitle,
  PopoverTrigger,
} from '@fex-design/vue/primitive/popover'
import Card from '@fex-design/vue/ui/card'
</script>
<template>
  <Card title="Popover" description="Compose existing Popover for error details."
    ><PopoverRoot placement="bottomLeft" arrow
      ><PopoverTrigger v-slot="trigger"
        ><Bubble variant="danger"
          ><BubbleContent
            ><template #render="{ props }"
              ><button v-bind="{ ...props, ...trigger.props }" :ref="trigger.ref">
                Failed to run the command. Show details.
              </button></template
            ></BubbleContent
          ></Bubble
        ></PopoverTrigger
      ><PopoverPortal
        ><PopoverContent
          ><PopoverArrow /><PopoverHeader class="w-72"
            ><PopoverTitle>Command error</PopoverTitle
            ><PopoverDescription
              >Dependency installation exited with code 1.</PopoverDescription
            ></PopoverHeader
          ></PopoverContent
        ></PopoverPortal
      ></PopoverRoot
    ></Card
  >
</template>
