// packages/@fex-design/components/solid/src/primitive/popover/popover-root.tsx
import { createMemo, splitProps, type JSX } from 'solid-js'
import type { PopoverOptions, PopoverRenderState } from '@fex-design/core/popover/types'
import { PopoverContext } from './popover-context'
import { createPopover } from './create-popover'

export type PopoverProps = PopoverOptions & {
  children?: JSX.Element | ((state: PopoverRenderState) => JSX.Element)
}

function PopoverChildren(props: Pick<PopoverProps, 'children'> & { state: PopoverRenderState }) {
  const content = createMemo(() => props.children)
  const value = content()
  return <>{typeof value === 'function' ? value(props.state) : value}</>
}

export function Popover(props: PopoverProps) {
  const [local, options] = splitProps(props, ['children'])
  const context = createPopover(() => options)
  const state = {
    get open() {
      return context.snapshot().open
    },
    close: context.overlay.close,
  }
  return (
    <PopoverContext.Provider value={context}>
      <PopoverChildren state={state}>{local.children}</PopoverChildren>
    </PopoverContext.Provider>
  )
}

export { Popover as PopoverRoot }
export type PopoverRootProps = PopoverProps

// apps/demo-monorepo/packages/ui/src/components/primitive/popover/popover-root.tsx
import type { ReactNode } from 'react'
import type { PopoverOptions, PopoverRenderState } from './utils'
import { useCoreStore } from '@demo/hooks/use-core-store'
import { PopoverContext, usePopoverContext } from './popover-context'
import { usePopover } from './use-popover'

export interface PopoverProps extends PopoverOptions {
  children?: ReactNode | ((state: PopoverRenderState) => ReactNode)
}

function RenderContent({ children }: { children: (state: PopoverRenderState) => ReactNode }) {
  const { overlay } = usePopoverContext('Popover')
  const snapshot = useCoreStore(overlay)
  return children({ open: snapshot.open, close: overlay.close })
}

export function Popover({ children, ...options }: PopoverProps) {
  const context = usePopover(options)
  return (
    <PopoverContext value={context}>
      {typeof children === 'function' ? <RenderContent>{children}</RenderContent> : children}
    </PopoverContext>
  )
}

export { Popover as PopoverRoot }
export type PopoverRootProps = PopoverProps
