// packages/@fex-design/angular/src/primitive/card/card.ts
import {
  cardClassName,
  cardContentClassName,
  cardDescriptionClassName,
  cardExtraClassName,
  cardFooterClassName,
  cardHeaderClassName,
  cardTitleClassName,
} from '@fex-design/styles/card'
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { cn } from '@fex/utils'
import { createHostClassName } from '../../signals/host-class'

@Component({
  selector: 'div[card]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: ':host { display: block; }',
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card',
  },
  template: '<ng-content />',
})
export class Card {
  protected readonly hostClassName = createHostClassName(cardClassName)
}

@Component({
  selector: 'div[cardHeader]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-header',
  },
  template: '<ng-content />',
})
export class CardHeader {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardHeaderClassName, this.className()))
}

@Component({
  selector: 'div[cardTitle]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-title',
  },
  template: '<ng-content />',
})
export class CardTitle {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardTitleClassName, this.className()))
}

@Component({
  selector: 'div[cardDescription]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-description',
  },
  template: '<ng-content />',
})
export class CardDescription {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardDescriptionClassName, this.className()))
}

@Component({
  selector: 'div[cardExtra]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-extra',
  },
  template: '<ng-content />',
})
export class CardExtra {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardExtraClassName, this.className()))
}

@Component({
  selector: 'div[cardContent]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-content',
  },
  template: '<ng-content />',
})
export class CardContent {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardContentClassName, this.className()))
}

@Component({
  selector: 'div[cardFooter]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-footer',
  },
  template: '<ng-content />',
})
export class CardFooter {
  className = input<string | undefined>()
  protected readonly hostClassName = createHostClassName(() => cn(cardFooterClassName, this.className()))
}

// packages/@fex-design/react/src/primitive/card/card.tsx
import {
  cardExtraClassName,
  cardClassName,
  cardContentClassName,
  cardDescriptionClassName,
  cardFooterClassName,
  cardHeaderClassName,
  cardTitleClassName,
} from '@fex-design/styles/card'
import { cn } from '@fex/utils'
import { type ComponentProps } from 'react'

export function Card({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card" className={cn(cardClassName, className)} {...props} />
}
export function CardHeader({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-header" className={cn(cardHeaderClassName, className)} {...props} />
}
export function CardTitle({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-title" className={cn(cardTitleClassName, className)} {...props} />
}
export function CardDescription({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      data-slot="card-description"
      className={cn(cardDescriptionClassName, className)}
      {...props}
    />
  )
}
export function CardExtra({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-extra" className={cn(cardExtraClassName, className)} {...props} />
}
export function CardContent({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-content" className={cn(cardContentClassName, className)} {...props} />
}
export function CardFooter({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-footer" className={cn(cardFooterClassName, className)} {...props} />
}
