// packages/@fex-design/react/src/primitive/spinner/spinner.tsx
import {
  spinnerClassName,
  spinnerContainerClassName,
  spinnerTextClassName,
} from '@fex-design/styles/spinner'
import { cn } from '@fex/utils'
import type { SpinnerOptions } from '@fex-design/core/spinner/types'
import type { ComponentProps } from 'react'
import { LoadingIcon } from '../../icon/loading'

export function SpinnerContainer({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      data-slot="spinner-container"
      className={cn(spinnerContainerClassName, className)}
      {...props}
    />
  )
}

export function Spinner({
  children,
  className,
  size = 'md',
  ...props
}: ComponentProps<'span'> & SpinnerOptions) {
  return (
    <span
      data-slot="spinner"
      className={cn(spinnerClassName({ size }), className)}
      role="status"
      {...props}
    >
      {children ?? <LoadingIcon className="animate-spin" />}
    </span>
  )
}

export function SpinnerText({ className, ...props }: ComponentProps<'span'>) {
  return (
    <span data-slot="spinner-text" className={cn(spinnerTextClassName, className)} {...props} />
  )
}

// packages/@fex-design/solid/src/primitive/spinner/spinner.tsx
import {
  spinnerClassName,
  spinnerContainerClassName,
  spinnerTextClassName,
} from '@fex-design/styles/spinner'
import { cn } from '@fex/utils'
import type { SpinnerOptions } from '@fex-design/core/spinner/types'
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { LoadingIcon } from '../../icon/loading'
export function SpinnerContainer(props: JSX.HTMLAttributes<HTMLSpanElement>) {
  const [local, rest] = splitProps(props, ['class'])
  return (
    <span
      {...rest}
      data-slot="spinner-container"
      class={cn(spinnerContainerClassName, local.class)}
    />
  )
}
export function Spinner(props: JSX.HTMLAttributes<HTMLSpanElement> & SpinnerOptions) {
  const [local, rest] = splitProps(props, ['class', 'size', 'children'])
  return (
    <span
      {...rest}
      data-slot="spinner"
      role="status"
      class={cn(spinnerClassName({ size: local.size }), local.class)}
    >
      {local.children ?? <LoadingIcon class="animate-spin" />}
    </span>
  )
}
export function SpinnerText(props: JSX.HTMLAttributes<HTMLSpanElement>) {
  const [local, rest] = splitProps(props, ['class'])
  return <span {...rest} data-slot="spinner-text" class={cn(spinnerTextClassName, local.class)} />
}
