// packages/@fex-design/components/solid/src/primitive/data-table/data-table-sort-button.tsx
import { dataTableSortButtonClassName } from '@fex-design/components-styles/data-table'
import { cn } from '@fex-design/utils'
import type { Column, RowData, TableFeatures } from '@tanstack/table-core'
import { splitProps, type JSX, type ParentProps } from 'solid-js'
import { ChevronDownIcon, ChevronUpIcon } from '@fex-design/solid/icons/chevron'
import { Button } from '../../ui/button/button'

interface SortableColumn {
  getCanSort: () => boolean
  getIsSorted: () => false | 'asc' | 'desc'
  getSortIndex: () => number
  getToggleSortingHandler: () => ((event: unknown) => void) | undefined
}

export interface DataTableSortButtonProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
> extends ParentProps<Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'children'>> {
  column: Column<TFeatures, TData>
}

export function DataTableSortButton<TFeatures extends TableFeatures, TData extends RowData>(
  props: DataTableSortButtonProps<TFeatures, TData>,
) {
  const [local, rest] = splitProps(props, ['column', 'children', 'class', 'onClick'])
  const column = local.column as unknown as SortableColumn
  const direction = () => column.getIsSorted()
  return (
    <Button
      {...rest}
      variant="text"
      disabled={!column.getCanSort()}
      aria-pressed={Boolean(direction())}
      class={cn(dataTableSortButtonClassName, local.class)}
      onClick={(event) => {
        if (typeof local.onClick === 'function') local.onClick(event)
        if (!event.defaultPrevented) column.getToggleSortingHandler()?.(event)
      }}
    >
      <span>{local.children}</span>
      <span class="inline-flex items-center" aria-hidden>
        {direction() === 'asc' ? (
          <ChevronUpIcon class="size-3.5" />
        ) : direction() === 'desc' ? (
          <ChevronDownIcon class="size-3.5" />
        ) : (
          <span class="relative inline-block size-3.5">
            <ChevronUpIcon class="absolute inset-x-0 top-0 size-3" />
            <ChevronDownIcon class="absolute inset-x-0 bottom-0 size-3" />
          </span>
        )}
        {direction() && column.getSortIndex() >= 0 ? <sup>{column.getSortIndex() + 1}</sup> : null}
      </span>
    </Button>
  )
}

// packages/@fex-design/components/react/src/primitive/data-table/data-table-sort-button.tsx
import { dataTableSortButtonClassName } from '@fex-design/components-styles/data-table'
import { cn } from '@fex-design/utils'
import type { Column, RowData, TableFeatures } from '@tanstack/react-table'
import type { ButtonHTMLAttributes, ReactNode } from 'react'
import { ChevronDownIcon, ChevronUpIcon } from '@fex-design/react/icons/chevron'
import { Button } from '../../ui/button'

export interface DataTableSortButtonProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
> extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  column: Column<TFeatures, TData>
  children?: ReactNode
}

export function DataTableSortButton<TFeatures extends TableFeatures, TData extends RowData>({
  column,
  children,
  className,
  onClick,
  ...props
}: DataTableSortButtonProps<TFeatures, TData>) {
  const sortColumn = column as unknown as Column<TFeatures, TData> & {
    getCanSort: () => boolean
    getIsSorted: () => false | 'asc' | 'desc'
    getSortIndex: () => number
    getToggleSortingHandler: () => ((event: unknown) => void) | undefined
  }
  const direction = sortColumn.getIsSorted()
  const sortIndex = sortColumn.getSortIndex()
  return (
    <Button
      {...props}
      type="button"
      variant="text"
      disabled={!sortColumn.getCanSort()}
      aria-pressed={Boolean(direction)}
      className={cn(dataTableSortButtonClassName, className)}
      onClick={(event) => {
        onClick?.(event)
        if (!event.defaultPrevented) sortColumn.getToggleSortingHandler()?.(event)
      }}
    >
      <span>{children}</span>
      <span className="inline-flex items-center" aria-hidden>
        {direction === 'asc' ? (
          <ChevronUpIcon className="size-3.5" />
        ) : direction === 'desc' ? (
          <ChevronDownIcon className="size-3.5" />
        ) : (
          <span className="relative inline-block size-3.5">
            <ChevronUpIcon className="absolute inset-x-0 top-0 size-3" />
            <ChevronDownIcon className="absolute inset-x-0 bottom-0 size-3" />
          </span>
        )}
        {direction && sortIndex >= 0 ? <sup>{sortIndex + 1}</sup> : null}
      </span>
    </Button>
  )
}
