// apps/solid-app/src/pages/Mentions/params-demo.tsx
import { MentionsContent } from '@fex-design/solid/primitive/mentions/content'
import { MentionsItem } from '@fex-design/solid/primitive/mentions/item'
import { MentionsList } from '@fex-design/solid/primitive/mentions/list'
import { MentionsRoot, useMentions } from '@fex-design/solid/primitive/mentions/root'
import { MentionsTrigger } from '@fex-design/solid/primitive/mentions/trigger'
import { Card } from '@fex-design/solid/ui/card'
import { For, createSignal } from 'solid-js'
import { filterByText, mentionDocs } from './data'

function Docs() {
  const mentions = useMentions()
  return (
    <MentionsList>
      <For each={filterByText(mentionDocs, mentions.text(), (doc) => doc.title)}>
        {(doc) => <MentionsItem itemKey={doc.id} value={doc.title} data={doc}>{doc.title}</MentionsItem>}
      </For>
    </MentionsList>
  )
}

export function ParamsDemo() {
  const [value, setValue] = createSignal('')
  const [params, setParams] = createSignal<string[]>([])
  return (
    <Card title="Parameter-only selection" description="Selection stores params without writing mention text.">
      <MentionsRoot
        prefix="#"
        value={value()}
        onChange={setValue}
        onSelect={(item) => setParams((current) => [...current, item.value])}
      >
        <MentionsTrigger placeholder="Type # to attach knowledge context" />
        <MentionsContent><Docs /></MentionsContent>
      </MentionsRoot>
      <div class="mt-1.5 flex flex-wrap gap-1 text-xs text-muted-foreground">
        <For each={params()} fallback="No params yet">{(param) => <span>#{param}</span>}</For>
      </div>
    </Card>
  )
}

// apps/svelte-app/src/routes/mentions/params-demo.svelte
<script lang="ts">
  import MentionsRoot from "@fex-design/svelte/primitive/mentions/root";
  import MentionsTrigger from "@fex-design/svelte/primitive/mentions/trigger";
  import MentionsContent from "@fex-design/svelte/primitive/mentions/content";
  import MentionsList from "@fex-design/svelte/primitive/mentions/list";
  import MentionsItem from "@fex-design/svelte/primitive/mentions/item";
  import Card from "@fex-design/svelte/ui/card";
  import { mentionDocs } from "./data";

  let value = $state("");
  let params = $state<string[]>([]);
</script>

<Card
  title="Parameter-only selection"
  description="Selection stores params without writing mention text."
>
  <MentionsRoot
    {value}
    prefix="#"
    onChange={(next) => (value = next)}
    onSelect={(item) => (params = [...params, item.value])}
  >
    <MentionsTrigger placeholder="Type # to attach knowledge context" />
    <MentionsContent>
      <MentionsList>
        {#each mentionDocs as doc (doc.id)}
          <MentionsItem itemKey={doc.id} value={doc.title}
            >{#snippet children()}{doc.title}{/snippet}</MentionsItem
          >
        {/each}
      </MentionsList>
    </MentionsContent>
  </MentionsRoot>
  <div class="mt-1.5 flex flex-wrap gap-1 text-xs text-muted-foreground">
    {#if params.length}
      {#each params as param (param)}<span>#{param}</span>{/each}
    {:else}
      <span>No params yet</span>
    {/if}
  </div>
</Card>
