// packages/@fex-design/components/react/src/primitive/tooltip/tooltip-root.tsx
import { useId, useRef, useState, type ReactNode } from "react"
import {
  createTooltip,
  type TooltipOptions,
} from "@fex-design/core/tooltip/create-tooltip"
import { shallowEqualObject } from "@fex-design/utils"
import { useIsomorphicLayoutEffect } from "@fex-design/react/hooks/use-isomorphic-layout-effect"
import { useLazyRef } from "@fex-design/react/hooks/use-lazy-ref"
import { useMemoizedFn } from "@fex-design/react/hooks/use-memoized-fn"
import useUnmount from "@fex-design/react/hooks/use-unmount"
import { TooltipContext } from "./tooltip-context"

export interface TooltipRootProps extends TooltipOptions {
  children?: ReactNode
}

export function TooltipRoot({
  children,
  open: openProp,
  defaultOpen,
  onOpenChange,
  ...config
}: TooltipRootProps) {
  const controlled = openProp !== undefined
  const [localOpen, setLocalOpen] = useState(defaultOpen ?? false)
  const handleOpenChange = useMemoizedFn<NonNullable<TooltipOptions["onOpenChange"]>>(
    (open, info) => {
      if (!controlled) setLocalOpen(open)
      onOpenChange?.(open, info)
    },
  )
  const options: TooltipOptions = {
    ...config,
    open: controlled ? openProp : localOpen,
    onOpenChange: handleOpenChange,
  }
  const overlayRef = useLazyRef(() => createTooltip(options))
  const latestOptions = useRef(options)
  const triggerRef = useRef<HTMLElement | null>(null)
  const contentId = `tooltip-${useId().replaceAll(":", "")}`
  const overlay = overlayRef.current
  useIsomorphicLayoutEffect(() => {
    if (shallowEqualObject(latestOptions.current, options)) return
    latestOptions.current = options
    overlay.setOptions(options)
  })
  useUnmount(() => overlay.destroy())
  return <TooltipContext value={{ contentId, overlay, triggerRef }}>{children}</TooltipContext>
}

export { TooltipRoot as Tooltip }
export type TooltipProps = TooltipRootProps

// packages/@fex-design/vue/src/primitive/tooltip/tooltip-root.vue
<script setup lang="ts">
import { createTooltip, type TooltipOptions } from '@fex-design/core/tooltip/create-tooltip'
import { shallowEqualObject } from '@fex/utils'
import { computed, onBeforeUnmount, provide, ref, shallowRef, useId, watchEffect } from 'vue'
import { useCoreStore } from '../../composables/use-core-store'
import { tooltipKey } from './context'

type TooltipRootProps = Omit<TooltipOptions, 'onOpenChange'>
const props = withDefaults(defineProps<TooltipRootProps>(), { defaultOpen: false, open: undefined })
const emit = defineEmits<{
  openChange: [open: boolean, info: Parameters<NonNullable<TooltipOptions['onOpenChange']>>[1]]
}>()
const controlled = computed(() => props.open !== undefined)
const localOpen = ref(props.defaultOpen)
const triggerElement = shallowRef<HTMLElement | null>(null)
function handleOpenChange(
  open: boolean,
  info: Parameters<NonNullable<TooltipOptions['onOpenChange']>>[1],
) {
  if (!controlled.value) localOpen.value = open
  emit('openChange', open, info)
}
function createOptions(): TooltipOptions {
  return {
    ...props,
    open: controlled.value ? Boolean(props.open) : localOpen.value,
    onOpenChange: handleOpenChange,
  }
}
let latestOptions = createOptions()
const overlay = createTooltip(latestOptions)
const snapshot = useCoreStore(overlay)
provide(tooltipKey, {
  contentId: `fex-tooltip-${useId().replaceAll(':', '')}`,
  overlay,
  snapshot,
  triggerElement,
})
watchEffect(() => {
  const next = createOptions()
  if (!shallowEqualObject(latestOptions, next)) {
    latestOptions = next
    overlay.setOptions(next)
  }
})
onBeforeUnmount(() => overlay.destroy())
</script>
<template><slot /></template>
