// packages/@fex-design/components/svelte/src/primitive/context-menu/context-menu-trigger.svelte
<script lang="ts" generics="TPayload = unknown">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { getContext } from "svelte";
  import {
    contextMenuContextKey,
    type ContextMenuContext,
  } from "./context-menu-context";

  interface Props {
    payload?: TPayload;
    children?: Snippet<
      [
        {
          action: (element: HTMLElement) => { destroy: () => void };
          props: HTMLAttributes<HTMLElement>;
          state: ReturnType<
            ContextMenuContext<TPayload>["controller"]["getSnapshot"]
          >;
        },
      ]
    >;
  }
  let { payload, children }: Props = $props();
  const { controller, snapshot } = getContext<ContextMenuContext<TPayload>>(
    contextMenuContextKey,
  );
  function eventInfo(event: Event & Partial<PointerEvent>) {
    return {
      target: event.target,
      currentTarget: event.currentTarget,
      clientX: event.clientX,
      clientY: event.clientY,
      button: event.button,
      pointerType: event.pointerType,
      event,
      preventDefault: event.preventDefault.bind(event),
      stopPropagation: event.stopPropagation.bind(event),
    };
  }
  function action(element: HTMLElement) {
    controller.overlay.setReferenceElement(element);
    return {
      destroy() {
        controller.overlay.setReferenceElement(null);
      },
    };
  }
  const triggerProps = $derived({
    "aria-haspopup": "menu",
    "data-state": $snapshot.overlay.open ? "open" : "closed",
    oncontextmenu: (event: MouseEvent) =>
      controller.openAt(
        {
          payload,
          element: event.currentTarget as HTMLElement,
          clientX: event.clientX,
          clientY: event.clientY,
          event,
        },
        eventInfo(event),
      ),
    onkeydown: (event: KeyboardEvent) => {
      if (
        (event.shiftKey && event.key === "F10") ||
        event.key === "ContextMenu"
      ) {
        event.preventDefault();
        const element = event.currentTarget as HTMLElement;
        const rect = element.getBoundingClientRect();
        controller.openAt(
          { payload, element, clientX: rect.left, clientY: rect.bottom, event },
          eventInfo(event),
        );
      }
    },
  } satisfies HTMLAttributes<HTMLElement>);
</script>

{@render children?.({ action, props: triggerProps, state: $snapshot })}

// packages/@fex-design/components/vue/src/primitive/context-menu/context-menu-trigger.vue
<script setup lang="ts" generic="TPayload = unknown">
import { computed, onBeforeUnmount, type ComponentPublicInstance, type VNodeRef } from 'vue'
import { useContextMenuContext } from './context'

const props = defineProps<{ payload?: TPayload }>()
const { controller, snapshot } = useContextMenuContext<TPayload>('ContextMenuTrigger')
function setReference(element: Element | ComponentPublicInstance | null) {
  const target = element instanceof HTMLElement ? element : null
  controller.overlay.setReferenceElement(target)
}
function openAt(event: MouseEvent, x = event.clientX, y = event.clientY) {
  if (event.defaultPrevented || !(event.currentTarget instanceof HTMLElement)) return
  controller.openAt(
    { payload: props.payload, element: event.currentTarget, clientX: x, clientY: y, event },
    {
      target: event.target,
      currentTarget: event.currentTarget,
      clientX: x,
      clientY: y,
      button: event.button,
      event,
      preventDefault: () => event.preventDefault(),
      stopPropagation: () => event.stopPropagation(),
    },
  )
}
const triggerProps = computed(() => ({
  'aria-haspopup': 'menu' as const,
  'data-state': snapshot.value.overlay.open ? ('open' as const) : ('closed' as const),
  onContextmenu: (event: MouseEvent) => openAt(event),
  onKeydown: (event: KeyboardEvent) => {
    if ((event.shiftKey && event.key === 'F10') || event.key === 'ContextMenu') {
      event.preventDefault()
      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect()
      openAt(event as unknown as MouseEvent, rect.left, rect.bottom)
    }
  },
}))
const triggerRef: VNodeRef = (element) => setReference(element)
onBeforeUnmount(() => controller.overlay.setReferenceElement(null))
</script>
<template><slot :props="triggerProps" :ref="triggerRef" :state="snapshot" /></template>
