// packages/@fex-design/components/solid/src/primitive/input-number/input-number-context.ts
import { createContext, useContext } from 'solid-js'
import type { UseInputNumberReturn } from './use-input-number'
export const InputNumberContext = createContext<UseInputNumberReturn>()
export function useInputNumberContext(component: string) {
  const value = useContext(InputNumberContext)
  if (!value) throw new Error(`${component} must be used inside InputNumberRoot.`)
  return value
}

// packages/@fex-design/components/react/src/primitive/input-number/input-number-context.ts
import { createContext, use } from 'react'
import type { UseInputNumberReturn } from './use-input-number'

export const InputNumberContext = createContext<UseInputNumberReturn | null>(null)

export function useInputNumberContext(component: string) {
  const context = use(InputNumberContext)
  if (!context) throw new Error(`${component} must be used inside InputNumberRoot.`)
  return context
}
