// packages/@fex-design/components/react/src/primitive/toast/toast-title.tsx
import { toastTitleClassName } from "@fex-design/components-styles/toast"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type ToastTitleProps = ComponentProps<"div">

export function ToastTitle({ className, ...props }: ToastTitleProps) {
  return <div data-slot="toast-title" className={cn(toastTitleClassName, className)} {...props} />
}

// packages/@fex-design/components/solid/src/primitive/toast/toast-title.tsx
import { toastTitleClassName } from "@fex-design/components-styles/toast"
import { cn } from "@fex-design/utils"
import type { JSX } from "solid-js"

export type ToastTitleProps = JSX.HTMLAttributes<HTMLDivElement>

export function ToastTitle(props: ToastTitleProps) {
  return <div {...props} data-slot="toast-title" class={cn(toastTitleClassName, props.class)} />
}
