// packages/@fex-design/components/react/src/primitive/tour/tour-context.ts
import { createContext, use } from 'react'
import type { TourController, TourSnapshot } from '@fex-design/core/tour/types'
import type { Floating } from '@fex-design/core/floating/create-floating'

export interface TourContextValue<TData = unknown> {
  controller: TourController<TData>
  snapshot: TourSnapshot<TData>
  keyboard: boolean
  overlay: boolean
  closeOnOverlayClick: boolean
  defaultGap: number
  zIndex: number
  getPopupContainer?: ((referenceElement: HTMLElement | null) => HTMLElement) | undefined
}

export const TourContext = createContext<TourContextValue | null>(null)

export function useTourContext(component: string) {
  const context = use(TourContext)
  if (!context) throw new Error(`${component} must be used inside Tour.Root`)
  return context
}

export interface TourContentContextValue {
  floating: Floating
  snapshot: ReturnType<Floating['getSnapshot']>
  setContentElement: (element: HTMLDivElement | null) => void
}

export const TourContentContext = createContext<TourContentContextValue | null>(null)

export function useTourContentContext(component: string) {
  const context = use(TourContentContext)
  if (!context) throw new Error(`${component} must be used inside Tour.Content`)
  return context
}

// packages/@fex-design/components/solid/src/primitive/tour/tour-context.ts
import type { Floating } from '@fex-design/core/floating/create-floating'
import type { TourController, TourSnapshot } from '@fex-design/core/tour/types'
import { createContext, useContext, type Accessor } from 'solid-js'

export interface TourContextValue<TData = unknown> {
  controller: TourController<TData>
  snapshot: Accessor<TourSnapshot<TData>>
  overlay: boolean
  closeOnOverlayClick: boolean
  defaultGap: number
  zIndex: number
  getPopupContainer?: (referenceElement: HTMLElement | null) => HTMLElement
}
export interface TourContentContextValue {
  floating: Floating
  snapshot: Accessor<ReturnType<Floating['getSnapshot']>>
}
export const TourContext = createContext<TourContextValue>()
export const TourContentContext = createContext<TourContentContextValue>()
export function useTourContext(component: string) {
  const context = useContext(TourContext)
  if (!context) throw new Error(`${component} must be used inside TourRoot`)
  return context
}
export function useTourContentContext(component: string) {
  const context = useContext(TourContentContext)
  if (!context) throw new Error(`${component} must be used inside TourContent`)
  return context
}
