// packages/@fex-design/vue/src/primitive/breadcrumb/breadcrumb-page.vue
<script setup lang="ts">
import { breadcrumbPageClassName } from '@fex-design/styles/breadcrumb'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'
const attrs = useAttrs()
</script>
<template>
  <span
    v-bind="attrs"
    aria-current="page"
    :class="cn(breadcrumbPageClassName, attrs.class as string)"
    data-slot="breadcrumb-page"
    ><slot
  /></span>
</template>

// packages/@fex-design/components/react/src/primitive/breadcrumb/breadcrumb-page.tsx
import { breadcrumbPageClassName } from "@fex-design/components-styles/breadcrumb"
import { cn } from "@fex-design/utils"
import type { HTMLAttributes } from "react"

export type BreadcrumbPageProps = HTMLAttributes<HTMLSpanElement>

export function BreadcrumbPage({ className, children, ...props }: BreadcrumbPageProps) {
  return (
    <span
      {...props}
      aria-current={props["aria-current"] ?? "page"}
      className={cn(breadcrumbPageClassName, className)}
      data-slot="breadcrumb-page"
    >
      {children}
    </span>
  )
}
