// packages/@fex-design/components/vue/src/primitive/tree/tree-virtual-viewport.vue
<script setup lang="ts" generic="TNode extends TreeNodeData">
import type { FocusFeatureApi } from '@fex-design/core/tree/features/focus'
import type { TreeKey, TreeNodeData } from '@fex-design/core/tree/types'
import { useVirtualizer } from '@tanstack/vue-virtual'
import { cn } from '@fex-design/utils'
import { computed, shallowRef, useAttrs } from 'vue'
import { useTreeContext } from './context'
import { useTreeVisibleItems } from './use-tree-visible-items'

export interface TreeVirtualViewportHandle {
  scrollToKey(
    key: TreeKey,
    options?: { align?: 'auto' | 'start' | 'center' | 'end'; reveal?: boolean },
  ): boolean
}

defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{ height: number; overscan?: number }>(), { overscan: 6 })
const attrs = useAttrs()
const viewportAttrs = computed(() => {
  const { class: _class, style: _style, ...rest } = attrs
  return rest
})
const viewportClass = computed(() => cn('overflow-auto', attrs.class as string | undefined))
const { tree, rowHeight } = useTreeContext<TNode>('TreeVirtualViewport')
const items = useTreeVisibleItems(tree)
const scrollElement = shallowRef<HTMLDivElement | null>(null)
const virtualizer = useVirtualizer(
  computed(() => ({
    count: items.value.length,
    getScrollElement: () => scrollElement.value,
    estimateSize: () => rowHeight.value,
    overscan: props.overscan,
    getItemKey: (index: number) => items.value[index]?.key ?? index,
  })),
)

function scrollToKey(
  key: TreeKey,
  options?: { align?: 'auto' | 'start' | 'center' | 'end'; reveal?: boolean },
) {
  if (options?.reveal) tree.getFeature<FocusFeatureApi>('focus')?.reveal(key)
  const index = tree.getVisibleIndex(key)
  if (index === undefined || index < 0) return false
  virtualizer.value.scrollToIndex(index, { align: options?.align ?? 'auto' })
  return true
}
defineExpose<TreeVirtualViewportHandle>({ scrollToKey })
</script>

<template>
  <div
    v-bind="viewportAttrs"
    ref="scrollElement"
    data-slot="tree-virtual-viewport"
    :class="viewportClass"
    :style="[attrs.style, { height: `${props.height}px` }]"
  >
    <div class="relative w-full" :style="{ height: `${virtualizer.getTotalSize()}px` }">
      <div
        v-for="virtualItem in virtualizer.getVirtualItems()"
        :key="String(virtualItem.key)"
        class="absolute left-0 w-full"
        :style="{
          height: `${virtualItem.size}px`,
          transform: `translateY(${virtualItem.start}px)`,
        }"
      >
        <slot v-if="items[virtualItem.index]" :item="items[virtualItem.index]" :tree="tree" />
      </div>
    </div>
  </div>
</template>

// packages/@fex-design/components/react/src/primitive/tree/tree-virtual-viewport.tsx
import type { FocusFeatureApi } from '@fex-design/core/tree/features/focus'
import type { TreeKey, TreeNodeData, TreeVisibleItem } from '@fex-design/core/tree/types'
import { cn } from '@fex-design/utils'
import { useVirtualizer } from '@tanstack/react-virtual'
import {
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
  type Ref,
} from 'react'
import { useTreeContext } from './tree-context'
import { useTreeVisibleItems } from './use-tree-visible-items'

export interface TreeVirtualViewportProps<TNode extends TreeNodeData> extends Omit<
  HTMLAttributes<HTMLDivElement>,
  'children'
> {
  height: number
  overscan?: number | undefined
  ref?: Ref<TreeVirtualViewportHandle> | undefined
  children: (item: TreeVisibleItem<TNode>) => ReactNode
}

export interface TreeVirtualViewportHandle {
  scrollToKey(
    key: TreeKey,
    options?: { align?: 'auto' | 'start' | 'center' | 'end'; reveal?: boolean },
  ): boolean
}

export function TreeVirtualViewport<TNode extends TreeNodeData>({
  height,
  overscan = 6,
  children,
  className,
  style,
  ref,
  ...props
}: TreeVirtualViewportProps<TNode>) {
  const { tree, rowHeight } = useTreeContext<TNode>()
  const scrollElementRef = useRef<HTMLDivElement>(null)
  const items = useTreeVisibleItems(tree)
  const virtualizer = useVirtualizer({
    count: items.length,
    getScrollElement: () => scrollElementRef.current,
    estimateSize: () => rowHeight,
    overscan,
  })

  useImperativeHandle(
    ref,
    () => ({
      scrollToKey(key, options) {
        if (options?.reveal) tree.getFeature<FocusFeatureApi>('focus')?.reveal(key)
        const visibleIndex = tree.getVisibleIndex(key)
        if (visibleIndex === undefined || visibleIndex < 0) return false
        virtualizer.scrollToIndex(visibleIndex, { align: options?.align ?? 'auto' })
        return true
      },
    }),
    [tree, virtualizer],
  )

  return (
    <div
      {...props}
      ref={scrollElementRef}
      data-slot="tree-virtual-viewport"
      className={cn('overflow-auto', className)}
      style={{ ...style, height }}
    >
      <div className="relative w-full" style={{ height: virtualizer.getTotalSize() }}>
        {virtualizer.getVirtualItems().map((virtualItem) => {
          const item = items[virtualItem.index]
          if (!item) return null
          return (
            <div
              key={item.key}
              className="absolute left-0 w-full"
              style={{ height: virtualItem.size, transform: `translateY(${virtualItem.start}px)` }}
            >
              {children(item)}
            </div>
          )
        })}
      </div>
    </div>
  )
}
