// packages/@fex-design/components/solid/src/primitive/time-picker/time-picker-column.tsx
import type { TimePickerOption, TimePeriod } from '@fex-design/core/time-picker/types'
import {
  timePickerColumnClassName,
  timePickerColumnItemClassName,
  timePickerColumnSpacerClassName,
  timePickerColumnViewportClassName,
} from '@fex-design/components-styles/time-picker'
import { cn } from '@fex-design/utils'
import { createEffect, For, splitProps, type JSX } from 'solid-js'
import { ScrollbarBar, ScrollbarRoot, ScrollbarViewport } from '../scrollbar'
import { useTimePickerContext } from './time-picker-context'

export type ColumnValue = number | TimePeriod

export interface TimePickerColumnProps<TValue extends ColumnValue> extends Omit<
  JSX.HTMLAttributes<HTMLDivElement>,
  'onSelect' | 'children'
> {
  options: readonly TimePickerOption<TValue>[]
  selectedValue?: TValue | undefined
  disabled?: boolean | undefined
  onSelect(value: TValue): void
}

export function TimePickerColumn<TValue extends ColumnValue>(props: TimePickerColumnProps<TValue>) {
  const [local, rest] = splitProps(props, [
    'options',
    'selectedValue',
    'disabled',
    'onSelect',
    'class',
    'onKeyDown',
  ])
  const context = useTimePickerContext('TimePickerColumn')
  let listElement: HTMLDivElement | undefined = undefined
  const itemElements = new Map<TValue, HTMLButtonElement>()
  let activeValue: TValue | undefined
  const isDisabled = () => context.disabled() || Boolean(local.disabled)

  createEffect(() => {
    const selected = local.selectedValue
    const request = context.snapshot().scrollRequest
    queueMicrotask(() => {
      const item = selected === undefined ? undefined : itemElements.get(selected)
      if (item && listElement)
        listElement.scrollTo({ top: item.offsetTop, behavior: request?.behavior ?? 'auto' })
    })
  })

  function move(direction: 1 | -1) {
    const enabled = local.options.filter((option) => !option.disabled)
    const current = enabled.findIndex((option) => option.value === activeValue)
    const next = enabled[Math.min(enabled.length - 1, Math.max(0, current + direction))]
    if (!next) return
    activeValue = next.value
    itemElements.get(next.value)?.focus()
  }

  return (
    <ScrollbarRoot
      data-slot="time-picker-column"
      data-disabled={isDisabled() ? 'true' : undefined}
      class={cn(timePickerColumnClassName, local.class)}
      disabled={isDisabled()}
    >
      <ScrollbarViewport
        {...rest}
        ref={(element) => {
          listElement = element
        }}
        role="listbox"
        tabIndex={isDisabled() ? -1 : 0}
        aria-disabled={isDisabled() || undefined}
        overflowX="hidden"
        class={timePickerColumnViewportClassName}
        onKeyDown={(event) => {
          if (typeof local.onKeyDown === 'function') local.onKeyDown(event)
          if (event.defaultPrevented || isDisabled() || context.readOnly()) return
          if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
            event.preventDefault()
            move(event.key === 'ArrowDown' ? 1 : -1)
          }
        }}
      >
        <For each={local.options}>
          {(item) => {
            const selected = () => Object.is(item.value, local.selectedValue)
            return (
              <button
                ref={(element) => itemElements.set(item.value, element)}
                type="button"
                role="option"
                tabIndex={-1}
                disabled={isDisabled() || item.disabled}
                aria-selected={selected()}
                data-selected={selected() ? 'true' : undefined}
                data-disabled={item.disabled ? 'true' : undefined}
                class={timePickerColumnItemClassName}
                onFocus={() => {
                  activeValue = item.value
                }}
                onClick={() => {
                  if (isDisabled() || context.readOnly() || item.disabled) return
                  activeValue = item.value
                  local.onSelect(item.value)
                  const itemElement = itemElements.get(item.value)
                  if (listElement && itemElement)
                    listElement.scrollTo({ top: itemElement.offsetTop, behavior: 'smooth' })
                }}
              >
                {item.label}
              </button>
            )
          }}
        </For>
        <div aria-hidden="true" class={timePickerColumnSpacerClassName} />
      </ScrollbarViewport>
      <ScrollbarBar axis="y" />
    </ScrollbarRoot>
  )
}

// packages/@fex-design/components/react/src/primitive/time-picker/time-picker-column.tsx
import {
  timePickerColumnClassName,
  timePickerColumnItemClassName,
  timePickerColumnSpacerClassName,
  timePickerColumnViewportClassName,
} from '@fex-design/components-styles/time-picker'
import type { TimePeriod, TimePickerOption } from '@fex-design/core/time-picker/types'
import { cn } from '@fex-design/utils'
import {
  useRef,
  useState,
  type ComponentProps,
  type KeyboardEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react'
import { useComposedRef } from '@fex-design/react/hooks/use-composed-ref'
import { useIsomorphicLayoutEffect } from '@fex-design/react/hooks/use-isomorphic-layout-effect'
import { useTimePickerContext } from './time-picker-context'
import { ScrollbarBar, ScrollbarRoot, ScrollbarViewport } from '../scrollbar/scrollbar'

type ColumnValue = number | TimePeriod

export interface TimePickerColumnItemRenderState<TValue extends ColumnValue> {
  item: TimePickerOption<TValue>
  selected: boolean
  active: boolean
  itemProps: ComponentProps<'button'> & {
    ref: Ref<HTMLButtonElement>
    'data-selected'?: string | undefined
    'data-active'?: string | undefined
    'data-disabled'?: string | undefined
  }
}

interface TimePickerColumnProps<TValue extends ColumnValue> extends Omit<
  ComponentProps<'div'>,
  'children' | 'onSelect'
> {
  options: readonly TimePickerOption<TValue>[]
  selectedValue: TValue | undefined
  disabled?: boolean
  onSelect(value: TValue): void
  children?: ((state: TimePickerColumnItemRenderState<TValue>) => ReactElement | null) | ReactNode
}

export function TimePickerColumn<TValue extends ColumnValue>({
  options,
  selectedValue,
  disabled = false,
  onSelect,
  children,
  className,
  onKeyDown,
  ref,
  ...props
}: TimePickerColumnProps<TValue>) {
  const { snapshot, disabled: rootDisabled, readOnly } = useTimePickerContext('TimePickerColumn')
  const listRef = useRef<HTMLDivElement | null>(null)
  const itemRefs = useRef(new Map<ColumnValue, HTMLButtonElement>())
  const activeValueRef = useRef<TValue | undefined>(selectedValue)
  const [activeValue, setActiveValue] = useState<TValue | undefined>(selectedValue)
  const resolvedDisabled = rootDisabled || disabled
  const composedRef = useComposedRef<HTMLDivElement>(listRef, ref)

  function scrollSelected(behavior: ScrollBehavior) {
    if (selectedValue === undefined) return
    const list = listRef.current
    const item = itemRefs.current.get(selectedValue)
    if (!list || !item) return
    list.scrollTo({ top: item.offsetTop, behavior })
  }

  // DOM scrolling is an external system. Layout timing ensures items exist before
  // the selected value is aligned without feeding scrollTop back into component state.
  useIsomorphicLayoutEffect(() => {
    scrollSelected(snapshot.scrollRequest?.behavior ?? 'auto')
  }, [selectedValue, snapshot.scrollRequest?.id])

  function moveActive(direction: 1 | -1) {
    const enabled = options.filter((option) => !option.disabled)
    if (enabled.length === 0) return
    const currentIndex = enabled.findIndex((option) => option.value === activeValueRef.current)
    const nextIndex = Math.min(enabled.length - 1, Math.max(0, currentIndex + direction))
    const next = enabled[nextIndex]
    if (!next) return
    activeValueRef.current = next.value
    setActiveValue(next.value)
    itemRefs.current.get(next.value)?.focus()
  }

  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event)
    if (event.defaultPrevented || resolvedDisabled || readOnly) return
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      moveActive(event.key === 'ArrowDown' ? 1 : -1)
    }
  }

  return (
    <ScrollbarRoot
      data-slot="time-picker-column"
      data-disabled={resolvedDisabled ? 'true' : undefined}
      className={cn(timePickerColumnClassName, className)}
      disabled={resolvedDisabled}
    >
      <ScrollbarViewport
        {...props}
        ref={composedRef}
        role="listbox"
        tabIndex={resolvedDisabled ? -1 : 0}
        aria-disabled={resolvedDisabled || undefined}
        className={timePickerColumnViewportClassName}
        overflow={{ x: 'hidden', y: 'auto' }}
        onKeyDown={handleKeyDown}
      >
        {options.map((item) => {
          const selected = Object.is(item.value, selectedValue)
          const itemProps: TimePickerColumnItemRenderState<TValue>['itemProps'] = {
            ref: (element) => {
              if (element) itemRefs.current.set(item.value, element)
              else itemRefs.current.delete(item.value)
            },
            type: 'button',
            role: 'option',
            tabIndex: -1,
            disabled: resolvedDisabled || item.disabled,
            'aria-selected': selected,
            'data-selected': selected ? 'true' : undefined,
            'data-disabled': item.disabled ? 'true' : undefined,
            'data-active': Object.is(activeValue, item.value) ? 'true' : undefined,
            onFocus: () => {
              activeValueRef.current = item.value
              setActiveValue(item.value)
            },
            onClick: () => {
              if (resolvedDisabled || readOnly || item.disabled) return
              activeValueRef.current = item.value
              setActiveValue(item.value)
              onSelect(item.value)
              const itemElement = itemRefs.current.get(item.value)
              if (listRef.current && itemElement) {
                listRef.current.scrollTo({ top: itemElement.offsetTop, behavior: 'smooth' })
              }
            },
          }
          const state = { item, selected, active: Object.is(activeValue, item.value), itemProps }
          return typeof children === 'function' ? (
            children(state)
          ) : (
            <TimePickerColumnItem key={String(item.value)} {...itemProps}>
              {item.label}
            </TimePickerColumnItem>
          )
        })}
        <div aria-hidden="true" className={timePickerColumnSpacerClassName} />
      </ScrollbarViewport>
      <ScrollbarBar axis="y" />
    </ScrollbarRoot>
  )
}

export interface TimePickerColumnItemProps extends ComponentProps<'button'> {
  ref?: Ref<HTMLButtonElement>
}

export function TimePickerColumnItem({ className, ref, ...props }: TimePickerColumnItemProps) {
  return <button {...props} ref={ref} className={cn(timePickerColumnItemClassName, className)} />
}
