// packages/@fex-design/components/react/src/primitive/masonry/masonry-root.tsx
import {
  useEffect,
  useRef,
  type HTMLAttributes,
} from 'react'
import {
  createMasonryController,
} from '@fex-design/core/masonry/create-masonry-controller'
import type {
  MasonryControllerOptions,
} from '@fex-design/core/masonry/types'
import {
  masonryRootClassName,
} from '@fex-design/components-styles/masonry'
import { cn } from '@fex-design/utils'
import { useLazyRef } from '@fex-design/react/hooks/use-lazy-ref'
import { MasonryContext } from './masonry-context'

export interface MasonryRootProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'dir'>, MasonryControllerOptions {}

export function MasonryRoot({
  columns,
  gap,
  placement,
  direction = 'ltr',
  onLayoutChange,
  className,
  children,
  ...props
}: MasonryRootProps) {
  const controller = useLazyRef(() =>
    createMasonryController({ columns, gap, placement, direction, onLayoutChange }),
  ).current
  const rootRef = useRef<HTMLDivElement>(null)
  controller.setOptions({ columns, gap, placement, direction, onLayoutChange })

  useEffect(() => {
    const element = rootRef.current
    if (!element) return
    const observer = new ResizeObserver(([entry]) =>
      controller.setWidth(entry?.contentRect.width ?? 0),
    )
    observer.observe(element)
    return () => observer.disconnect()
  }, [controller])

  useEffect(() => () => controller.destroy(), [controller])

  return (
    <MasonryContext
      value={{ controller, options: { columns, gap, placement, direction, onLayoutChange } }}
    >
      <div
        {...props}
        ref={rootRef}
        dir={direction}
        data-slot="masonry"
        className={cn(masonryRootClassName, className)}
      >
        {children}
      </div>
    </MasonryContext>
  )
}

// packages/@fex-design/svelte/src/primitive/masonry/masonry-root.svelte
<script lang="ts">
  import { createMasonryController } from "@fex-design/core/masonry/create-masonry-controller";
  import type { MasonryControllerOptions } from "@fex-design/core/masonry/types";
  import { masonryRootClassName } from "@fex-design/styles/masonry";
  import { cn } from "@fex/utils";
  import { onMount, setContext, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { masonryContextKey, type MasonryContext } from "./context";
  interface Props
    extends
      Omit<HTMLAttributes<HTMLDivElement>, "children" | "dir">,
      MasonryControllerOptions {
    children?: Snippet;
  }
  let {
    columns,
    gap,
    placement,
    direction = "ltr",
    onLayoutChange,
    children,
    class: className,
    ...rest
  }: Props = $props();
  const controller = createMasonryController({
    columns,
    gap,
    placement,
    direction,
    onLayoutChange,
  });
  let element = $state<HTMLDivElement>();
  $effect(() =>
    controller.setOptions({
      columns,
      gap,
      placement,
      direction,
      onLayoutChange,
    }),
  );
  setContext<MasonryContext>(masonryContextKey, {
    controller,
    options: () => ({ columns, gap, placement, direction, onLayoutChange }),
  });
  onMount(() => {
    const observer = new ResizeObserver(([entry]) =>
      controller.setWidth(entry?.contentRect.width ?? 0),
    );
    if (element) observer.observe(element);
    return () => {
      observer.disconnect();
      controller.destroy();
    };
  });
</script>

<div
  {...rest}
  bind:this={element}
  dir={direction}
  data-slot="masonry"
  class={cn(masonryRootClassName, className)}
>
  {@render children?.()}
</div>
