// packages/@fex-design/svelte/src/primitive/badge/badge.svelte
<script lang="ts">
  import { isBadgePresetColor, type BadgeOptions } from "@fex-design/core";
  import { badgeClassName } from "@fex-design/styles/badge";
  import { cn } from "@fex/utils";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  interface Props
    extends
      Omit<HTMLAttributes<HTMLSpanElement>, "class" | "color">,
      BadgeOptions {
    class?: string;
    children?: Snippet;
  }
  let {
    class: className,
    children,
    color,
    size = "md",
    count,
    showZero = false,
    overflowCount,
    style,
    ...rest
  }: Props = $props();
  const value = $derived(
    typeof count === "number" &&
      overflowCount !== undefined &&
      count > overflowCount
      ? `${overflowCount}+`
      : count,
  );
  const visible = $derived(
    (value !== undefined && value !== null && (value !== 0 || showZero)) ||
      children !== undefined,
  );
  const presetColor = $derived(isBadgePresetColor(color) ? color : undefined);
  const customColor = $derived(color && !presetColor ? color : undefined);
  const classList = $derived(
    cn(badgeClassName({ color: presetColor, size }), className),
  );
  const mergedStyle = $derived(
    [style, customColor ? `--badge-color:${customColor}` : ""]
      .filter(Boolean)
      .join(";"),
  );
</script>

{#if visible}<span
    {...rest}
    data-slot="badge"
    data-color={color ?? "default"}
    data-size={size}
    class={classList}
    style={mergedStyle || undefined}
    >{#if value !== undefined}{value}{:else}{@render children?.()}{/if}</span
  >{/if}

// packages/@fex-design/vue/src/primitive/badge/badge.vue
<script setup lang="ts">
import { isBadgePresetColor, type BadgeOptions } from '@fex-design/core'
import { badgeClassName } from '@fex-design/styles/badge'
import { cn } from '@fex/utils'
import { computed, useAttrs } from 'vue'

defineOptions({ name: 'Badge', inheritAttrs: false })

const props = defineProps<BadgeOptions & { size?: 'sm' | 'md' | 'lg' }>()

const attrs = useAttrs()
const presetColor = computed(() => (isBadgePresetColor(props.color) ? props.color : undefined))
const customColor = computed(() => (props.color && !presetColor.value ? props.color : undefined))
const value = computed(() =>
  typeof props.count === 'number' &&
  props.overflowCount != null &&
  props.count > props.overflowCount
    ? `${props.overflowCount}+`
    : props.count,
)
const visible = computed(
  () => (value.value != null && (value.value !== 0 || props.showZero)) || value.value == null,
)
</script>

<template>
  <span
    v-if="visible"
    v-bind="attrs"
    data-slot="badge"
    :data-color="props.color ?? 'default'"
    :data-size="props.size ?? 'md'"
    :class="
      cn(
        badgeClassName({ color: presetColor, size: props.size }),
        attrs.class as string | undefined,
      )
    "
    :style="[{ '--badge-color': customColor }, attrs.style]"
  >
    {{ value ?? '' }}<slot v-if="value == null" />
  </span>
</template>
