// packages/@fex-design/react/src/primitive/cascader/cascader-panel.tsx
import type { CascaderNode } from '@fex-design/core/cascader/types'
import {
  cascaderColumnClassName,
  cascaderColumnViewportClassName,
  cascaderContentClassName,
  cascaderEmptyClassName,
  cascaderLoadingClassName,
  cascaderOptionClassName,
  cascaderOptionIconClassName,
  cascaderOptionLabelClassName,
  cascaderPanelHeight,
  cascaderPanelClassName,
} from '@fex-design/styles/cascader'
import {
  checkboxCheckIconClassName,
  checkboxClassName,
  checkboxIndicatorClassName,
  checkboxMinusIconClassName,
} from '@fex-design/styles/checkbox'
import { cn } from '@fex/utils'
import { type ComponentProps, type CSSProperties, type ReactNode } from 'react'
import { CheckIcon } from '../../icon/check'
import { ChevronRightIcon } from '../../icon/chevron'
import { LoadingIcon } from '../../icon/loading'
import { MinusIcon } from '../../icon/minus'
import { CheckboxIndicator, CheckboxRoot } from '../checkbox/checkbox'
import { PopoverContent, PopoverPortal } from '../popover/popover'
import { ScrollbarBar, ScrollbarRoot, ScrollbarViewport } from '../scrollbar/scrollbar'
import { useCascader } from './cascader-context'

export function CascaderContent({ className, children, ...props }: ComponentProps<'div'>) {
  return (
    <PopoverPortal>
      <PopoverContent
        {...props}
        role={undefined}
        className={cn(cascaderContentClassName, className)}
      >
        {children ?? <CascaderPanel />}
      </PopoverContent>
    </PopoverPortal>
  )
}

export interface CascaderPanelProps extends ComponentProps<'div'> {
  optionRender?: (node: CascaderNode, state: CascaderOptionState) => ReactNode
  empty?: ReactNode
}

export function CascaderPanel({
  className,
  optionRender,
  empty,
  style,
  ...props
}: CascaderPanelProps) {
  const cascader = useCascader()
  const searchResults = cascader.controller.getSearchResults()
  if (cascader.snapshot.searchValue && cascader.showSearch) {
    return (
      <div
        {...props}
        style={
          {
            ...style,
            '--cascader-column-count': 1,
            '--cascader-panel-height': cascaderPanelHeight(
              cascader.loading ? 0 : searchResults.length,
            ),
          } as CSSProperties
        }
        className={cn(cascaderPanelClassName, className)}
      >
        <CascaderColumn className="w-full min-w-full border-r-0">
          {cascader.loading ? (
            <CascaderLoading />
          ) : searchResults.length ? (
            searchResults.map((path) => (
              <CascaderOption
                key={path.at(-1)!.key}
                node={path.at(-1)!}
                label={path.map((node) => node.label).join(' / ')}
                render={optionRender}
              />
            ))
          ) : (
            (empty ?? <CascaderEmpty />)
          )}
        </CascaderColumn>
      </div>
    )
  }
  const columns = cascader.controller.getColumns()
  const itemCount = Math.max(0, ...columns.map((column) => column.nodes.length))
  return (
    <div
      {...props}
      role="tree"
      style={
        {
          ...style,
          '--cascader-column-count': columns.length,
          '--cascader-panel-height': cascaderPanelHeight(itemCount),
        } as CSSProperties
      }
      className={cn(cascaderPanelClassName, className)}
    >
      {columns.map((column, index) => (
        <CascaderColumn key={column.parentKey ?? 'root'} aria-label={`Level ${index + 1}`}>
          {column.nodes.map((node) => (
            <CascaderOption key={node.key} node={node} render={optionRender} />
          ))}
        </CascaderColumn>
      ))}
    </div>
  )
}

export function CascaderColumn({ className, children, ...props }: ComponentProps<'div'>) {
  return (
    <div {...props} role="listbox" className={cn(cascaderColumnClassName, className)}>
      <ScrollbarRoot className="h-full" overflow={{ y: 'auto', x: 'hidden' }}>
        <ScrollbarViewport className={cascaderColumnViewportClassName}>
          {children}
        </ScrollbarViewport>
        <ScrollbarBar axis="y" />
      </ScrollbarRoot>
    </div>
  )
}

export interface CascaderOptionState {
  active: boolean
  selected: boolean
  checked: boolean
  indeterminate: boolean
  disabled: boolean
  leaf: boolean
  loading: boolean
}

export function CascaderOption({
  node,
  label,
  render,
  className,
  ...props
}: Omit<ComponentProps<'div'>, 'children'> & {
  node: CascaderNode
  label?: ReactNode
  render?: CascaderPanelProps['optionRender']
}) {
  const cascader = useCascader()
  const state: CascaderOptionState = {
    active: cascader.snapshot.activePath.includes(node.key),
    selected: cascader.snapshot.selectedPathKeys.includes(node.key),
    checked: cascader.snapshot.checkedKeys.includes(node.key),
    indeterminate: cascader.snapshot.indeterminateKeys.includes(node.key),
    disabled: node.disabled,
    leaf: node.leaf,
    loading: cascader.snapshot.loadingKeys.includes(node.key),
  }
  return (
    <div
      {...props}
      role="option"
      aria-selected={state.selected}
      aria-disabled={state.disabled || undefined}
      data-active={state.active ? 'true' : undefined}
      data-selected={state.selected ? 'true' : undefined}
      data-disabled={state.disabled ? 'true' : undefined}
      className={cn(cascaderOptionClassName, className)}
      onPointerEnter={() => {
        if (cascader.expandTrigger === 'hover' && !node.leaf) cascader.controller.expand(node.key)
      }}
      onClick={() => cascader.controller.select(node.key)}
    >
      {render?.(node, state) ?? (
        <>
          {cascader.multiple ? (
            <CheckboxRoot
              checked={state.indeterminate ? 'indeterminate' : state.checked}
              disabled={state.disabled}
              className={checkboxClassName()}
              onClick={(event) => {
                event.stopPropagation()
                cascader.controller.toggleCheck(node.key)
              }}
            >
              <CheckboxIndicator className={checkboxIndicatorClassName}>
                <CheckIcon className={checkboxCheckIconClassName} />
                <MinusIcon className={checkboxMinusIconClassName} />
              </CheckboxIndicator>
            </CheckboxRoot>
          ) : null}
          <span className={cascaderOptionLabelClassName}>{label ?? node.label}</span>
          <span className={cascaderOptionIconClassName}>
            {state.loading ? (
              <LoadingIcon className="animate-spin" />
            ) : !state.leaf ? (
              <ChevronRightIcon />
            ) : state.selected ? (
              <CheckIcon />
            ) : null}
          </span>
        </>
      )}
    </div>
  )
}

export function CascaderEmpty({
  children = 'No options',
  className,
  ...props
}: ComponentProps<'div'>) {
  return (
    <div {...props} className={cn(cascaderEmptyClassName, className)}>
      {children}
    </div>
  )
}

export function CascaderLoading({
  children = 'Loading...',
  className,
  ...props
}: ComponentProps<'div'>) {
  return (
    <div {...props} className={cn(cascaderLoadingClassName, className)}>
      <LoadingIcon className="animate-spin" />
      {children}
    </div>
  )
}

// packages/@fex-design/svelte/src/primitive/cascader/cascader-panel.svelte
<script lang="ts">
  import type { CascaderNode } from "@fex-design/core/cascader/types";
  import {
    cascaderColumnClassName,
    cascaderColumnViewportClassName,
    cascaderEmptyClassName,
    cascaderLoadingClassName,
    cascaderOptionClassName,
    cascaderOptionIconClassName,
    cascaderOptionLabelClassName,
    cascaderPanelClassName,
    cascaderPanelHeight,
  } from "@fex-design/styles/cascader";
  import {
    checkboxCheckIconClassName,
    checkboxClassName,
    checkboxIndicatorClassName,
    checkboxMinusIconClassName,
  } from "@fex-design/styles/checkbox";
  import { getContext } from "svelte";
  import CheckIcon from "../../icon/check.svelte";
  import ChevronRight from "../../icon/chevron-right.svelte";
  import LoadingIcon from "../../icon/loading.svelte";
  import MinusIcon from "../../icon/minus.svelte";
  import Checkbox from "../checkbox/checkbox.svelte";
  import CheckboxIndicator from "../checkbox/checkbox-indicator.svelte";
  import Scrollbar from "../scrollbar/scrollbar.svelte";
  import ScrollbarBar from "../scrollbar/scrollbar-bar.svelte";
  import ScrollbarViewport from "../scrollbar/scrollbar-viewport.svelte";
  import { cascaderContextKey, type CascaderContext } from "./context";

  const cascader = getContext<CascaderContext>(cascaderContextKey);
  const snapshot = cascader.snapshot;
  const state = (node: CascaderNode) => ({
    active: $snapshot.activePath.includes(node.key),
    selected: $snapshot.selectedPathKeys.includes(node.key),
    checked: $snapshot.checkedKeys.includes(node.key),
    indeterminate: $snapshot.indeterminateKeys.includes(node.key),
    loading: $snapshot.loadingKeys.includes(node.key),
  });
  const columns = () => {
    void $snapshot.activePath;
    return cascader.controller.getColumns();
  };
  const results = () => {
    void $snapshot.searchValue;
    return cascader.controller.getSearchResults();
  };
  const height = () =>
    cascaderPanelHeight(
      $snapshot.searchValue && cascader.showSearch()
        ? cascader.loading()
          ? 0
          : results().length
        : Math.max(0, ...columns().map((column) => column.nodes.length)),
    );
  const columnCount = () =>
    $snapshot.searchValue && cascader.showSearch()
      ? 1
      : Math.max(1, columns().length);
  const enter = (node: CascaderNode) => {
    if (cascader.expandTrigger() === "hover" && !node.leaf)
      cascader.controller.expand(node.key);
  };
</script>

{#snippet option(node: CascaderNode, label?: string)}
  <div
    role="option"
    aria-selected={state(node).selected}
    aria-disabled={node.disabled || undefined}
    data-active={state(node).active || undefined}
    data-selected={state(node).selected || undefined}
    data-disabled={node.disabled || undefined}
    class={cascaderOptionClassName}
    onpointerenter={() => enter(node)}
    onclick={() => cascader.controller.select(node.key)}
  >
    {#if cascader.multiple()}<Checkbox
        checked={state(node).indeterminate
          ? "indeterminate"
          : state(node).checked}
        disabled={node.disabled}
        class={checkboxClassName()}
        onclick={(event) => {
          event.stopPropagation();
          cascader.controller.toggleCheck(node.key);
        }}
        >{#snippet children(checked)}<CheckboxIndicator
            {checked}
            class={checkboxIndicatorClassName}
            ><CheckIcon class={checkboxCheckIconClassName} /><MinusIcon
              class={checkboxMinusIconClassName}
            /></CheckboxIndicator
          >{/snippet}</Checkbox
      >{/if}
    <span class={cascaderOptionLabelClassName}>{label ?? node.label}</span><span
      class={cascaderOptionIconClassName}
      >{#if state(node).loading}<LoadingIcon
          class="animate-spin"
        />{:else if !node.leaf}<ChevronRight
        />{:else if state(node).selected}<CheckIcon />{/if}</span
    >
  </div>
{/snippet}

<div
  class={cascaderPanelClassName}
  style={`--cascader-column-count:${columnCount()};--cascader-panel-height:${height()}`}
>
  {#if $snapshot.searchValue && cascader.showSearch()}
    <div class={`${cascaderColumnClassName} w-full min-w-full border-r-0`}>
      <Scrollbar class="h-full"
        ><ScrollbarViewport
          overflowX="hidden"
          overflowY="auto"
          class={cascaderColumnViewportClassName}
          >{#if cascader.loading()}<div class={cascaderLoadingClassName}>
              <LoadingIcon class="animate-spin" />Loading...
            </div>{:else if results().length}{#each results() as path (path.at(-1)!.key)}{@render option(
                path.at(-1)!,
                path.map((node) => node.label).join(" / "),
              )}{/each}{:else}<div class={cascaderEmptyClassName}>
              No options
            </div>{/if}</ScrollbarViewport
        ><ScrollbarBar axis="y" /></Scrollbar
      >
    </div>
  {:else}
    {#each columns() as column, index (column.parentKey ?? "root")}<div
        role="listbox"
        aria-label={`Level ${index + 1}`}
        class={cascaderColumnClassName}
      >
        <Scrollbar class="h-full"
          ><ScrollbarViewport
            overflowX="hidden"
            overflowY="auto"
            class={cascaderColumnViewportClassName}
            >{#each column.nodes as node (node.key)}{@render option(
                node,
              )}{/each}</ScrollbarViewport
          ><ScrollbarBar axis="y" /></Scrollbar
        >
      </div>{/each}
  {/if}
</div>
