// apps/react-app/src/pages/Tree/index.tsx
import { Link } from 'react-router'
import { AsyncTreeDemo } from './async-demo'
import { AsyncSearchTreeDemo } from './async-search-demo'
import { BasicTreeDemo } from './basic-demo'
import { TreeBatchActionsDemo } from './batch-actions-demo'
import { CheckTreeDemo } from './check-demo'
import { ControlledTreeDemo } from './controlled-demo'
import { TreeDndDemo } from './dnd-demo'
import { TreeMutationDemo } from './mutation-demo'
import { SearchTreeDemo } from './search-demo'
import { VirtualTreeDemo } from './virtual-demo'

export function TreePage() {
  return (
    <main className="min-h-screen bg-secondary-background px-2 md:px-6 py-4">
      <div className="mx-auto w-full max-w-5xl space-y-4">
        <header className="space-y-1.5">
          <Link className="text-sm text-muted-foreground hover:text-foreground" to="/">
            Back home
          </Link>
          <div>
            <h1 className="text-2xl font-semibold text-foreground">Tree</h1>
            <p className="max-w-3xl text-sm leading-6 text-muted-foreground">
              Headless tree state, field mapping, async children, search data, keyboard navigation
              and virtual rendering.
            </p>
          </div>
        </header>
        <div className="space-y-4">
          <BasicTreeDemo />
          <ControlledTreeDemo />
          <TreeBatchActionsDemo />
          <TreeMutationDemo />
          <TreeDndDemo />
          <CheckTreeDemo />
          <AsyncTreeDemo />
          <AsyncSearchTreeDemo />
          <SearchTreeDemo />
          <VirtualTreeDemo />
        </div>
      </div>
    </main>
  )
}

// apps/vue-app/src/pages/Tree/index.vue
<script setup lang="ts">
import AsyncDemo from './async-demo.vue'
import AsyncSearchDemo from './async-search-demo.vue'
import BasicDemo from './basic-demo.vue'
import BatchActionsDemo from './batch-actions-demo.vue'
import CheckDemo from './check-demo.vue'
import ControlledDemo from './controlled-demo.vue'
import DndDemo from './dnd-demo.vue'
import MutationDemo from './mutation-demo.vue'
import SearchDemo from './search-demo.vue'
import VirtualDemo from './virtual-demo.vue'
</script>
<template>
  <main class="min-h-screen bg-secondary-background px-2 md:px-6 py-4">
    <div class="mx-auto w-full max-w-5xl space-y-4">
      <header class="space-y-1.5">
        <RouterLink class="text-sm text-muted-foreground hover:text-foreground" to="/"
          >Back home</RouterLink
        >
        <div>
          <h1 class="text-2xl font-semibold text-foreground">Tree</h1>
          <p class="max-w-3xl text-sm leading-6 text-muted-foreground">
            Headless tree state, field mapping, async children, search data, keyboard navigation and
            virtual rendering.
          </p>
        </div>
      </header>
      <div class="space-y-4">
        <BasicDemo /><ControlledDemo /><BatchActionsDemo /><MutationDemo /><DndDemo /><CheckDemo /><AsyncDemo /><AsyncSearchDemo /><SearchDemo /><VirtualDemo />
      </div>
    </div>
  </main>
</template>
