// apps/angular-app/src/pages/watermark/restore-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { Watermark } from '@fex-design/angular/primitive/watermark'
import { Button } from '@fex-design/angular/ui/button'
import Card from '@fex-design/angular/ui/card'

@Component({
  selector: 'fex-watermark-restore-demo',
  standalone: true,
  imports: [Button, Card, Watermark],
  templateUrl: './restore-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RestoreDemo {
  protected removeWatermark() {
    document
      .querySelector('[data-demo="angular-watermark-restore"] [data-slot="watermark"]')
      ?.remove()
  }
}

<fex-card title="Restore" description="Removing the generated watermark layer appends it back.">
  <div class="space-y-2">
    <button fexButton variant="outline" type="button" (click)="removeWatermark()">
      Remove generated layer
    </button>
    <fex-watermark
      [content]="['FEX Admin', 'Do not distribute']"
      data-demo="angular-watermark-restore"
      class="h-56 rounded-md border border-border bg-background"
    >
      <div class="grid h-full place-items-center p-4 text-center text-sm text-muted-foreground">
        The controller observes direct child removal on this root and restores the layer.
      </div>
    </fex-watermark>
  </div>
</fex-card>

// apps/react-app/src/pages/Watermark/restore-demo.tsx
import { Watermark } from '@fex-design/react/primitive/watermark'
import { Button } from '@fex-design/react/ui/button'
import { Card } from '@fex-design/react/ui/card'

export function RestoreDemo() {
  const removeWatermark = () => {
    document.querySelector('[data-demo="react-watermark-restore"] [data-slot="watermark"]')?.remove()
  }

  return (
    <Card title="Restore" description="Removing the generated watermark layer appends it back.">
      <div className="space-y-2">
        <Button variant="outline" onClick={removeWatermark}>
          Remove generated layer
        </Button>
        <Watermark
          content={['FEX Admin', 'Do not distribute']}
          data-demo="react-watermark-restore"
          className="h-56 rounded-md border border-border bg-background"
        >
          <div className="grid h-full place-items-center p-4 text-center text-sm text-muted-foreground">
            The controller observes direct child removal on this root and restores the layer.
          </div>
        </Watermark>
      </div>
    </Card>
  )
}
