// packages/@fex-design/vue/src/primitive/tree-select/tree-select-option.vue
<script setup lang="ts">
import type { TreeSelectItem } from '@fex-design/core/tree-select/types'
import { computed, inject } from 'vue'
import { treeSelectKey } from './context'
const props = withDefaults(
  defineProps<{
    item: TreeSelectItem
    toggle?: boolean
    closeOnSelect?: boolean
    clearSearchOnSelect?: boolean
  }>(),
  {
    toggle: undefined,
    closeOnSelect: undefined,
    clearSearchOnSelect: true,
  },
)
const context = inject(treeSelectKey)
if (!context) throw new Error('TreeSelectOption must be used inside TreeSelectRoot.')
const treeSelect = context
treeSelect.controller.registerItem(props.item)
const selected = computed(() => {
  void treeSelect.snapshot.value
  return treeSelect.controller.isSelected(props.item.value)
})
function select() {
  if (props.item.disabled) return
  if (props.toggle ?? treeSelect.snapshot.value.multiple) treeSelect.controller.toggle(props.item)
  else treeSelect.controller.select(props.item)
  if (props.clearSearchOnSelect) treeSelect.setSearchValue('')
  const shouldClose = props.closeOnSelect ?? !(props.toggle ?? treeSelect.snapshot.value.multiple)
  if (shouldClose) treeSelect.closePanel()
}
</script>
<template><slot :selected="selected" :select="select" /></template>

// packages/@fex-design/components/solid/src/primitive/tree-select/tree-select-option.tsx
import type { TreeSelectItem } from '@fex-design/core/tree-select/types'
import { createEffect, type JSX } from 'solid-js'
import { useTreeSelect } from './tree-select-context'

export interface TreeSelectOptionProps<TNode = unknown> {
  item: TreeSelectItem<TNode>
  toggle?: boolean
  closeOnSelect?: boolean
  clearSearchOnSelect?: boolean
  children(state: { selected: boolean; select(): void }): JSX.Element
}

export function TreeSelectOption<TNode = unknown>(props: TreeSelectOptionProps<TNode>) {
  const context = useTreeSelect<TNode>()
  createEffect(() => context.controller.registerItem(props.item))
  const select = () => {
    if (props.item.disabled) return
    if (props.toggle ?? context.snapshot().multiple) context.controller.toggle(props.item)
    else context.controller.select(props.item)
    if (props.clearSearchOnSelect ?? true) context.setSearchValue('')
    const shouldClose = props.closeOnSelect ?? !(props.toggle ?? context.snapshot().multiple)
    if (shouldClose) context.closePanel()
  }
  return props.children({
    get selected() {
      context.snapshot()
      return context.controller.isSelected(props.item.value)
    },
    select,
  })
}
