// packages/@fex-design/components/react/src/primitive/spinner/spinner-text.tsx
import { spinnerTextClassName } from "@fex-design/components-styles/spinner"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type SpinnerTextProps = ComponentProps<"span">

export function SpinnerText({ className, ...props }: SpinnerTextProps) {
  return (
    <span data-slot="spinner-text" className={cn(spinnerTextClassName, className)} {...props} />
  )
}

// packages/@fex-design/vue/src/primitive/spinner/spinner-text.vue
<script setup lang="ts">
import { spinnerTextClassName } from '@fex-design/styles/spinner'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'
defineOptions({ name: 'SpinnerText', inheritAttrs: false })
const attrs = useAttrs()
</script>
<template>
  <span
    v-bind="attrs"
    data-slot="spinner-text"
    :class="cn(spinnerTextClassName, attrs.class as string | undefined)"
    ><slot
  /></span>
</template>
