// packages/@fex-design/components/react/src/primitive/spinner/spinner-container.tsx
import { spinnerContainerClassName } from "@fex-design/components-styles/spinner"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type SpinnerContainerProps = ComponentProps<"div">

export function SpinnerContainer({ className, ...props }: SpinnerContainerProps) {
  return (
    <div
      data-slot="spinner-container"
      className={cn(spinnerContainerClassName, className)}
      {...props}
    />
  )
}

// packages/@fex-design/vue/src/primitive/spinner/spinner-container.vue
<script setup lang="ts">
import { spinnerContainerClassName } from '@fex-design/styles/spinner'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'
defineOptions({ name: 'SpinnerContainer', inheritAttrs: false })
const attrs = useAttrs()
</script>
<template><div v-bind="attrs" data-slot="spinner-container" :class="cn(spinnerContainerClassName, attrs.class as string | undefined)"><slot /></div></template>
