// packages/@fex-design/components/solid/src/primitive/dialog/dialog-overlay.tsx
import { dialogOverlayClassName } from "@fex-design/components-styles/dialog"
import { cn } from "@fex-design/utils"
import { onCleanup, splitProps } from "solid-js"
import { useDialog } from "./dialog-context"

export interface DialogOverlayProps {
  class?: string
}

export function DialogOverlay(props: DialogOverlayProps) {
  const [local] = splitProps(props, ["class"])
  const { dialog, snapshot } = useDialog("DialogOverlay")
  onCleanup(() => dialog.setOverlayElement(null))
  return (
    <div
      ref={(element) => dialog.setOverlayElement(element)}
      data-slot="dialog-overlay"
      data-state={snapshot().open ? "open" : "closed"}
      data-phase={snapshot().phase}
      class={cn(dialogOverlayClassName, local.class)}
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          dialog.dismiss.overlayPointer({
            target: event.target,
            currentTarget: event.currentTarget,
            event,
          })
        }
      }}
    />
  )
}

// packages/@fex-design/components/vue/src/primitive/dialog/dialog-overlay.vue
<script setup lang="ts">
import { dialogOverlayClassName } from '@fex-design/components-styles/dialog'
import { cn } from '@fex-design/utils'
import type { ComponentPublicInstance } from 'vue'
import { computed, onBeforeUnmount } from 'vue'
import { useDialogContext } from './context'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string }>()
const { dialog, snapshot } = useDialogContext('DialogOverlay')
const overlayClass = computed(() => cn(dialogOverlayClassName, props.class))

function onClick(event: MouseEvent) {
  if (event.target === event.currentTarget) {
    dialog.dismiss.overlayPointer({
      target: event.target,
      currentTarget: event.currentTarget,
      event,
    })
  }
}

function setOverlay(element: Element | ComponentPublicInstance | null) {
  dialog.setOverlayElement(element instanceof HTMLDivElement ? element : null)
}

onBeforeUnmount(() => {
  dialog.setOverlayElement(null)
})
</script>

<template>
  <div
    :ref="setOverlay"
    data-slot="dialog-overlay"
    :data-state="snapshot.open ? 'open' : 'closed'"
    :data-phase="snapshot.phase"
    :class="overlayClass"
    @click="onClick"
  />
</template>
