// apps/vue-app/src/pages/InputOTP/controlled-demo.vue
<script setup lang="ts">
import type { InputOTPValue } from '@fex-design/core/input-otp/types'
import { InputOTPGroup, InputOTPInput, InputOTPRoot } from '@fex-design/vue/primitive/input-otp'
import { Button } from '@fex-design/vue/ui/button'
import Card from '@fex-design/vue/ui/card'
import { ref } from 'vue'
const value=ref<InputOTPValue>(['AB','',''])
</script>
<template><Card title="受控值" description="外部状态可以更新或清空所有输入段。"><div class="grid gap-2"><InputOTPRoot :value="value" @change="(next)=>value=next"><InputOTPGroup><InputOTPInput v-for="index in [0,1,2]" :key="index" :index="index" :max-length="2" class="w-14" :aria-label="`受控输入第 ${index+1} 段`"/></InputOTPGroup></InputOTPRoot><p class="text-sm text-muted-foreground">分段值：{{ JSON.stringify(value) }}</p><Button class="w-fit" variant="outline" @click="value=['','','']">清空</Button></div></Card></template>

// apps/react-app/src/pages/InputOTP/controlled-demo.tsx
import type { InputOTPValue } from '@fex-design/core/input-otp/types'
import { InputOTPGroup, InputOTPInput, InputOTPRoot } from '@fex-design/react/primitive/input-otp'
import { Button } from '@fex-design/react/ui/button'
import { Card } from '@fex-design/react/ui/card'
import { useState } from 'react'
export function ControlledDemo() {
  const [value, setValue] = useState<InputOTPValue>(['AB', '', ''])
  return (
    <Card title="受控值" description="外部状态可以更新或清空所有输入段。">
      <div className="grid gap-2">
        <InputOTPRoot value={value} onChange={setValue}>
          <InputOTPGroup>
            {[0, 1, 2].map((index) => (
              <InputOTPInput
                key={index}
                index={index}
                maxLength={2}
                className="w-14"
                aria-label={`受控输入第 ${index + 1} 段`}
              />
            ))}
          </InputOTPGroup>
        </InputOTPRoot>
        <p className="text-sm text-muted-foreground">分段值：{JSON.stringify(value)}</p>
        <Button className="w-fit" variant="outline" onClick={() => setValue(['', '', ''])}>
          清空
        </Button>
      </div>
    </Card>
  )
}
