// packages/@fex-design/components/react/src/primitive/input-number/input-number-control.tsx
import type { ComponentProps } from 'react'
import { InputControl } from '../input'
import { useInputNumberContext } from './input-number-context'

export interface InputNumberControlProps extends Omit<
  ComponentProps<typeof InputControl>,
  'value' | 'defaultValue' | 'type'
> {}

export function InputNumberControl({ onBlur, onKeyDown, ...props }: InputNumberControlProps) {
  const inputNumber = useInputNumberContext('InputNumberControl')
  return (
    <InputControl
      {...props}
      type="text"
      inputMode={props.inputMode ?? 'decimal'}
      role="spinbutton"
      aria-valuemin={inputNumber.min}
      aria-valuemax={inputNumber.max}
      aria-valuenow={inputNumber.value}
      aria-valuetext={props['aria-valuetext'] ?? inputNumber.formattedValue}
      onBlur={(event) => {
        onBlur?.(event)
        if (!event.defaultPrevented) inputNumber.blur(event)
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event)
        if (!event.defaultPrevented) inputNumber.keydown(event)
      }}
    />
  )
}

// packages/@fex-design/components/svelte/src/primitive/input-number/input-number-control.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";
  import InputControl from "../input/input-control.svelte";
  import { getInputNumberContext } from "./context";
  let {
    inputmode = "decimal",
    onblur,
    onkeydown,
    ...rest
  }: HTMLInputAttributes = $props();
  const inputNumber = getInputNumberContext("InputNumberControl");
</script>

<InputControl
  {...rest}
  type="text"
  {inputmode}
  role="spinbutton"
  aria-valuemin={inputNumber.min()}
  aria-valuemax={inputNumber.max()}
  aria-valuenow={inputNumber.value()}
  aria-valuetext={inputNumber.formattedValue()}
  onblur={(event) => {
    onblur?.(event);
    if (!event.defaultPrevented) inputNumber.blur(event);
  }}
  onkeydown={(event) => {
    onkeydown?.(event);
    if (!event.defaultPrevented) inputNumber.keydown(event);
  }}
/>
