// apps/vue-app/src/pages/DatePicker/custom-panel.vue
<script setup lang="ts">
import Button from '@fex-design/vue/ui/button'
import { useDatePickerContext } from '@fex-design/vue/primitive/date-picker'

const picker = useDatePickerContext('CustomPanel')
</script>

<template>
  <div class="grid gap-1.5 p-2">
    <p class="text-sm text-muted-foreground">
      这是完全自定义面板，仍可访问 DatePicker primitive 暴露的关闭方法。
    </p>
    <Button size="sm" @click="picker.close()">关闭面板</Button>
  </div>
</template>

// apps/svelte-app/src/routes/date-picker/custom-panel.svelte
<script lang="ts">
  import Button from '@fex-design/svelte/ui/button'
  import { useDatePickerContext } from '@fex-design/svelte/primitive/date-picker'

  const picker = useDatePickerContext('CustomPanel')
</script>

<div class="grid gap-1.5 p-2">
  <p class="text-sm text-muted-foreground">这是完全自定义面板，仍可访问 DatePicker primitive 暴露的关闭方法。</p>
  <Button size="sm" onclick={picker.close}>关闭面板</Button>
</div>
