// apps/svelte-app/src/routes/tabs/sortable-demo.svelte
<script lang="ts">
  import EllipsisIcon from "@fex-design/svelte/icon/more";
  import {
    SortableItem,
    SortableOverlay,
    SortableRoot,
  } from "@fex-design/svelte/primitive/sortable";
  import TabsRoot from "@fex-design/svelte/primitive/tabs-root";
  import TabsList from "@fex-design/svelte/primitive/tabs-list";
  import TabsItem from "@fex-design/svelte/primitive/tabs-item";
  import TabsContent from "@fex-design/svelte/primitive/tabs-content";
  import Card from "@fex-design/svelte/ui/card";
  import { initialTabs } from "./data";

  const fixed = initialTabs[0]!;
  let items = $state(initialTabs.slice(1));
  const asValues = (values: string[] | Record<string, string[]>) =>
    Array.isArray(values) ? values : [];
  const itemByValue = (value: string) =>
    items.find((item) => item.value === value);

  function reorder(values: string[] | Record<string, string[]>) {
    const byValue = new Map(items.map((item) => [item.value, item]));
    items = asValues(values)
      .map((value) => byValue.get(value))
      .filter((item): item is NonNullable<typeof item> => Boolean(item));
  }
</script>

<Card
  title="Sortable composition"
  description="Overview stays fixed while the remaining tabs can be dragged horizontally."
>
  <SortableRoot
    items={items.map((item) => item.value)}
    axis="x"
    class="block"
    onChange={reorder}
  >
    {#snippet children({ items: preview })}
      <TabsRoot defaultValue="overview">
        <TabsList>
          <TabsItem value={fixed.value}>{fixed.label}</TabsItem>
          {#each asValues(preview) as value (value)}
            <SortableItem
              id={value}
              class="!inline-flex !min-h-0 !border-0 !bg-transparent !p-0 !shadow-none"
            >
              <TabsItem
                {value}
                class="cursor-grab touch-none active:cursor-grabbing"
              >
                <EllipsisIcon class="size-3 rotate-90 text-muted-foreground" />
                {itemByValue(value)?.label}
              </TabsItem>
            </SortableItem>
          {/each}
        </TabsList>
        <TabsContent value={fixed.value}>{fixed.content}</TabsContent>
        {#each items as item (item.value)}<TabsContent value={item.value}
            >{item.content}</TabsContent
          >{/each}
      </TabsRoot>
      <SortableOverlay
        class="!box-border !inline-flex !h-7 !min-h-0 !items-center !rounded-md !border-0 !bg-muted-background !p-0 !text-muted-foreground !shadow-sm !outline-none !ring-0"
      >
        {#snippet children({ activeId })}<div
            class="flex h-7 items-center gap-1.5 px-2.5 text-sm"
          >
            <EllipsisIcon class="size-3 rotate-90" />{itemByValue(
              String(activeId),
            )?.label}
          </div>{/snippet}
      </SortableOverlay>
    {/snippet}
  </SortableRoot>
</Card>

// apps/react-app/src/pages/Tabs/sortable-demo.tsx
import { EllipsisIcon } from '@fex-design/react/icons/more'
import * as Sortable from '@fex-design/react/primitive/sortable'
import { TabsContent, TabsItem, TabsList, TabsRoot } from '@fex-design/react/primitive/tabs'
import { Card } from '@fex-design/react/ui/card'
import { useState } from 'react'
import { initialTabs } from './data'

const sortableItemClassName =
  'cursor-grab touch-none active:cursor-grabbing data-[dragging=true]:opacity-60'

export function SortableTabsDemo() {
  const fixed = initialTabs[0]!
  const [items, setItems] = useState(initialTabs.slice(1))
  const byValue = new Map(items.map((item) => [item.value, item]))

  function reorder(values: string[]) {
    setItems(
      values
        .map((value) => byValue.get(value))
        .filter((item): item is NonNullable<typeof item> => Boolean(item)),
    )
  }

  return (
    <Card
      title="Sortable composition"
      description="Overview stays fixed while the remaining tabs can be dragged horizontally."
    >
      <Sortable.SortableRoot
        items={items.map((item) => item.value)}
        axis="x"
        onChange={reorder}
        className="block"
      >
        {({ items: values }) => (
          <>
            <TabsRoot defaultValue="overview">
              <TabsList>
                <TabsItem value={fixed.value}>{fixed.label}</TabsItem>
                {values.map((value) => {
                  const item = byValue.get(value)
                  return item ? (
                    <Sortable.SortableItem key={value} id={value}>
                      {({ props }) => (
                        <TabsItem value={value} {...props} className={sortableItemClassName}>
                          <EllipsisIcon className="size-3 rotate-90 text-muted-foreground" />
                          {item.label}
                        </TabsItem>
                      )}
                    </Sortable.SortableItem>
                  ) : null
                })}
              </TabsList>
              <TabsContent value={fixed.value}>{fixed.content}</TabsContent>
              {items.map((item) => (
                <TabsContent key={item.value} value={item.value}>
                  {item.content}
                </TabsContent>
              ))}
            </TabsRoot>
            <Sortable.SortableOverlay className="!box-border !inline-flex !h-7 !min-h-0 !items-center !rounded-md !border-0 !bg-muted-background !p-0 !text-muted-foreground !shadow-sm !outline-none !ring-0">
              {({ activeId }) => (
                <div className="flex h-7 items-center gap-1.5 px-2.5 text-sm">
                  <EllipsisIcon className="size-3 rotate-90" />
                  {byValue.get(String(activeId))?.label}
                </div>
              )}
            </Sortable.SortableOverlay>
          </>
        )}
      </Sortable.SortableRoot>
    </Card>
  )
}
