// apps/vue-app/src/pages/Masonry/collection-demo.vue
<script setup lang="ts">
import { MasonryItem, MasonryRoot, MasonryViewport } from '@fex-design/vue/primitive/masonry'
import { Button } from '@fex-design/vue/ui/button'
import { ref } from 'vue'
import { masonryItems, type MasonryDemoItem } from './data'
const initial = masonryItems.slice(0, 8),
  items = ref([...initial])
let serial = 1
function add(middle = false) {
  const item: MasonryDemoItem = {
    id: `added-${serial}`,
    title: `新增 ${serial}`,
    height: 120 + (serial % 3) * 40,
  }
  serial++
  const next = [...items.value]
  next.splice(middle ? Math.floor(next.length / 2) : next.length, 0, item)
  items.value = next
}
</script>
<template>
  <div class="grid gap-2">
    <div class="flex flex-wrap gap-1.5">
      <Button size="sm" @click="add()">末尾添加</Button
      ><Button size="sm" variant="outline" @click="add(true)">中间插入</Button
      ><Button
        size="sm"
        variant="outline"
        @click="items = [...items].sort(() => Math.random() - 0.5)"
        >打乱</Button
      ><Button size="sm" variant="outline" @click="items = [...initial]">恢复</Button>
    </div>
    <MasonryRoot :columns="3" :gap="12"
      ><MasonryViewport
        ><MasonryItem
          v-for="(item, index) in items"
          :key="item.id"
          :item-key="item.id"
          :index="index"
          ><article
            class="rounded-md border border-border bg-background p-2"
            :style="{ minHeight: `${item.height / 2}px` }"
          >
            <strong>{{ item.title }}</strong>
            <p class="text-xs text-muted-foreground">{{ item.id }}</p>
            <Button
              class="mt-2"
              size="sm"
              variant="outline"
              @click="items = items.filter((value) => value.id !== item.id)"
              >删除</Button
            >
          </article></MasonryItem
        ></MasonryViewport
      ></MasonryRoot
    >
  </div>
</template>

// apps/react-app/src/pages/Masonry/collection-demo.tsx
import { MasonryItem, MasonryRoot, MasonryViewport } from '@fex-design/react/primitive/masonry'
import { Button } from '@fex-design/react/ui/button'
import { useState } from 'react'
import { masonryItems, type MasonryDemoItem } from './data'

const initial = masonryItems.slice(0, 8)
export function CollectionMasonryDemo() {
  const [items, setItems] = useState(initial)
  const [serial, setSerial] = useState(1)
  const add = (middle = false) => { const item: MasonryDemoItem = { id: `added-${serial}`, title: `新增 ${serial}`, height: 120 + serial % 3 * 40 }; setSerial(value => value + 1); setItems(value => { const next = [...value]; next.splice(middle ? Math.floor(next.length / 2) : next.length, 0, item); return next }) }
  return <div className="grid gap-2"><div className="flex flex-wrap gap-1.5"><Button size="sm" onClick={() => add()}>末尾添加</Button><Button size="sm" variant="outline" onClick={() => add(true)}>中间插入</Button><Button size="sm" variant="outline" onClick={() => setItems(value => [...value].sort(() => Math.random() - 0.5))}>打乱</Button><Button size="sm" variant="outline" onClick={() => setItems(initial)}>恢复</Button></div><MasonryRoot columns={3} gap={12}><MasonryViewport>{items.map((item, index) => <MasonryItem key={item.id} itemKey={item.id} index={index}><article className="rounded-md border border-border bg-background p-2" style={{ minHeight: item.height / 2 }}><strong>{item.title}</strong><p className="text-xs text-muted-foreground">{item.id}</p><Button className="mt-2" size="sm" variant="outline" onClick={() => setItems(value => value.filter(current => current.id !== item.id))}>删除</Button></article></MasonryItem>)}</MasonryViewport></MasonryRoot></div>
}
