// packages/@fex-design/svelte/src/primitive/bubble/bubble-reaction.svelte
<script lang="ts">
  import {
    bubbleReactionClassName,
    bubbleReactionCountClassName,
  } from "@fex-design/styles/bubble";
  import { cn } from "@fex/utils";
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import Toggle from "../toggle/toggle.svelte";
  interface Props extends Omit<HTMLButtonAttributes, "children" | "onchange"> {
    pressed?: boolean;
    defaultPressed?: boolean;
    count?: number;
    onchange?: (value: boolean) => void;
    children?: Snippet;
    render?: Snippet<
      [
        {
          props: Record<string, unknown>;
          state: { pressed: boolean; disabled: boolean };
        },
      ]
    >;
  }
  let {
    pressed,
    defaultPressed = false,
    count,
    disabled = false,
    onchange,
    class: className,
    children,
    render,
    ...rest
  }: Props = $props();
  let state = $derived({
    pressed: pressed ?? defaultPressed,
    disabled: Boolean(disabled),
  });
  let binding = $derived({
    "data-slot": "bubble-reaction",
    "data-state": state.pressed ? "on" : "off",
    class: cn(bubbleReactionClassName(), className),
  });
</script>

{#if render}{@render render({ props: binding, state })}{:else}<Toggle
    {...rest}
    {pressed}
    {defaultPressed}
    {disabled}
    variant="outline"
    size="sm"
    data-slot="bubble-reaction"
    class={cn(bubbleReactionClassName(), className)}
    {onchange}
    >{@render children?.()}{#if count !== undefined}<span
        data-slot="bubble-reaction-count"
        class={bubbleReactionCountClassName}>{count}</span
      >{/if}</Toggle
  >{/if}

// packages/@fex-design/components/solid/src/primitive/bubble/bubble-reaction.tsx
import {
  bubbleReactionClassName,
  bubbleReactionCountClassName,
} from '@fex-design/components-styles/bubble'
import { cn } from '@fex-design/utils'
import { splitProps } from 'solid-js'
import { Toggle } from '../toggle/toggle'
import type { BubbleActionProps } from './bubble-action'

export interface BubbleReactionProps extends BubbleActionProps {
  count?: number
}

export function BubbleReaction(props: BubbleReactionProps) {
  const [local, rest] = splitProps(props, [
    'render',
    'class',
    'pressed',
    'defaultPressed',
    'disabled',
    'children',
    'count',
  ])
  const state = () => ({
    pressed: local.pressed ?? local.defaultPressed ?? false,
    disabled: Boolean(local.disabled),
  })
  if (local.render)
    return local.render({
      props: {
        'data-slot': 'bubble-reaction',
        'data-state': state().pressed ? 'on' : 'off',
        class: cn(bubbleReactionClassName(), local.class),
      },
      state: state(),
    })
  return (
    <Toggle
      {...rest}
      pressed={local.pressed}
      defaultPressed={local.defaultPressed}
      disabled={local.disabled}
      variant="outline"
      size="sm"
      data-slot="bubble-reaction"
      class={cn(bubbleReactionClassName(), local.class)}
    >
      {local.children}
      {local.count !== undefined && (
        <span data-slot="bubble-reaction-count" class={bubbleReactionCountClassName}>
          {local.count}
        </span>
      )}
    </Toggle>
  )
}
