// packages/@fex-design/components/react/src/primitive/bubble/bubble-group.tsx
import {
  resolveConversationSide,
  type BubbleGroupSpacing,
  type ConversationSide,
} from '@fex-design/core/bubble/types'
import { bubbleGroupClassName } from '@fex-design/components-styles/bubble'
import { cn } from '@fex-design/utils'
import { use, type ComponentProps } from 'react'
import { MessageSideContext } from './bubble-context'

export interface BubbleGroupProps extends ComponentProps<'div'> {
  side?: ConversationSide
  spacing?: BubbleGroupSpacing
}

export function BubbleGroup({ side, spacing = 'default', className, ...props }: BubbleGroupProps) {
  const messageSide = use(MessageSideContext)
  const resolvedSide = resolveConversationSide(side, messageSide ?? undefined)
  return (
    <div
      {...props}
      data-slot="bubble-group"
      data-side={resolvedSide}
      data-spacing={spacing}
      className={cn(bubbleGroupClassName({ spacing }), className)}
    />
  )
}

// packages/@fex-design/components/solid/src/primitive/bubble/bubble-group.tsx
import {
  resolveConversationSide,
  type BubbleGroupSpacing,
  type ConversationSide,
} from '@fex-design/core/bubble/types'
import { bubbleGroupClassName } from '@fex-design/components-styles/bubble'
import { cn } from '@fex-design/utils'
import {
  splitProps,
  useContext,
  type JSX,
  type ParentProps,
} from 'solid-js'
import { MessageSideContext } from './bubble-context'

export interface BubbleGroupProps extends ParentProps<JSX.HTMLAttributes<HTMLDivElement>> {
  side?: ConversationSide
  spacing?: BubbleGroupSpacing
}

export function BubbleGroup(props: BubbleGroupProps) {
  const [local, rest] = splitProps(props, ['side', 'spacing', 'class'])
  const inherited = useContext(MessageSideContext)
  const side = () => resolveConversationSide(local.side, inherited?.())
  return (
    <div
      {...rest}
      data-slot="bubble-group"
      data-side={side()}
      data-spacing={local.spacing ?? 'default'}
      class={cn(bubbleGroupClassName({ spacing: local.spacing ?? 'default' }), local.class)}
    />
  )
}
