// apps/svelte-app/src/routes/auto-complete/custom-demo.svelte
<script lang="ts">
  import AutoCompleteRoot from "@fex-design/svelte/primitive/auto-complete";
  import AutoCompleteContent from "@fex-design/svelte/primitive/auto-complete-content";
  import AutoCompleteList from "@fex-design/svelte/primitive/auto-complete-list";
  import AutoCompleteTrigger from "@fex-design/svelte/primitive/auto-complete-trigger";
  import Card from "@fex-design/svelte/ui/card";
  import { fieldNames, users } from "./data";
</script>

<div class="grid gap-4 md:grid-cols-2">
  <Card
    title="Custom items and disabled suggestion"
    description="Original backend items drive richer rows; Alex is disabled."
  >
    <AutoCompleteRoot items={users} {fieldNames}>
      <AutoCompleteTrigger
        placeholder="Custom suggestion rows"
        clearable
        status="warning"
      />
      <AutoCompleteContent>
        <div
          class="border-b border-border px-3 py-2 text-xs text-muted-foreground"
        >
          People directory
        </div>
        <AutoCompleteList>
          {#snippet item(user, state)}
            <div>
              <div class="font-medium">{user.name}</div>
              <div class="text-xs text-muted-foreground">
                {user.department} · {user.email}{state.disabled
                  ? " · unavailable"
                  : ""}
              </div>
            </div>
          {/snippet}
        </AutoCompleteList>
      </AutoCompleteContent>
    </AutoCompleteRoot>
  </Card>
  <Card
    title="Validation and native props"
    description="Input validation styles and native form attributes are preserved."
  >
    <AutoCompleteRoot items={users} {fieldNames}>
      <AutoCompleteTrigger
        name="reviewer"
        required
        aria-describedby="reviewer-error-svelte"
        placeholder="Required reviewer"
        clearable
        invalid
        status="error"
      />
      <AutoCompleteContent />
    </AutoCompleteRoot>
    <p id="reviewer-error-svelte" class="mt-1.5 text-xs text-danger">
      Choose a reviewer or enter a new name.
    </p>
  </Card>
</div>

// apps/vue-app/src/pages/AutoComplete/custom-demo.vue
<script setup lang="ts">
import {
  AutoCompleteContent,
  AutoCompleteList,
  AutoCompleteRoot,
  AutoCompleteTrigger,
} from '@fex-design/vue/primitive/auto-complete'
import Card from '@fex-design/vue/ui/card'
import { fieldNames, users } from './data'
</script>
<template>
  <div class="grid gap-4 md:grid-cols-2">
    <Card
      title="Custom items and disabled suggestion"
      description="Original backend items drive richer rows; Alex is disabled."
    >
      <AutoCompleteRoot :items="users" :field-names="fieldNames">
        <AutoCompleteTrigger placeholder="Custom suggestion rows" clearable status="warning" />
        <AutoCompleteContent>
          <div class="border-b border-border px-3 py-2 text-xs text-muted-foreground">
            People directory
          </div>
          <AutoCompleteList>
            <template #option="{ item, disabled }">
              <div>
                <div class="font-medium">{{ item.name }}</div>
                <div class="text-xs text-muted-foreground">
                  {{ item.department }} · {{ item.email }}{{ disabled ? ' · unavailable' : '' }}
                </div>
              </div>
            </template>
          </AutoCompleteList>
        </AutoCompleteContent>
      </AutoCompleteRoot>
    </Card>
    <Card
      title="Validation and native props"
      description="Input validation styles and native form attributes are preserved."
    >
      <AutoCompleteRoot :items="users" :field-names="fieldNames">
        <AutoCompleteTrigger
          name="reviewer"
          required
          aria-describedby="reviewer-error-vue"
          placeholder="Required reviewer"
          clearable
          invalid
          status="error"
        />
        <AutoCompleteContent />
      </AutoCompleteRoot>
      <p id="reviewer-error-vue" class="mt-1.5 text-xs text-danger">
        Choose a reviewer or enter a new name.
      </p>
    </Card>
  </div>
</template>
