// packages/@fex-design/components/react/src/primitive/progress/progress-value.tsx
import { progressValueClassName } from '@fex-design/components-styles/progress'
import { cn } from '@fex-design/utils'
import { type ComponentProps, type ReactNode, type Ref } from 'react'
import { useProgressContext } from './progress-context'
export interface ProgressValueProps extends ComponentProps<'span'> {
  ref?: Ref<HTMLSpanElement>
  children?:
    | ReactNode
    | ((context: { value: number | null; percentage: number | null }) => ReactNode)
}
export function ProgressValue({ ref, className, children, ...props }: ProgressValueProps) {
  const context = useProgressContext('ProgressValue')
  const display = typeof children === 'function'
    ? children({ value: context.value, percentage: context.percentage })
    : children
  return (
    <span
      {...props}
      ref={ref}
      data-slot="progress-value"
      data-status={context.status}
      className={cn(progressValueClassName, className)}
    >
      {display}
    </span>
  )
}

// packages/@fex-design/components/svelte/src/primitive/progress/progress-value.svelte
<script lang="ts">
  import { progressValueClassName } from "@fex-design/components-styles/progress"
  import { cn } from "@fex-design/utils"
  import { getContext, type Snippet } from "svelte"
  import type { HTMLAttributes } from "svelte/elements"
  import { progressContextKey, type ProgressContext } from "./context"

  interface ProgressValueProps extends HTMLAttributes<HTMLSpanElement> {
    children?: Snippet<[{ value: number | null; percentage: number | null }]>
  }

  let { class: className, children, ...rest }: ProgressValueProps = $props()
  const { context } = getContext<ProgressContext>(progressContextKey)
  const current = $derived(context())
</script>

<span
  {...rest}
  data-slot="progress-value"
  data-status={current.status}
  class={cn(progressValueClassName, className)}
>
  {#if children}{@render children({ value: current.value, percentage: current.percentage })}{/if}
</span>
