// packages/@fex-design/vue/src/primitive/tooltip/tooltip-root.vue
<script setup lang="ts">
import { createTooltip, type TooltipOptions } from '@fex-design/core/tooltip/create-tooltip'
import type { FloatingOverlayOptions } from '@fex-design/core/overlay/create-floating-overlay'
import { shallowEqualObject } from '@fex/utils'
import { computed, onBeforeUnmount, provide, ref, shallowRef, useId, watchEffect } from 'vue'
import { useCoreStore } from '../../composables/use-core-store'
import { tooltipKey } from './context'

interface TooltipRootProps {
  align?: FloatingOverlayOptions['align']
  alignOffset?: number
  avoidCollisions?: boolean
  closeDelay?: number
  collisionPadding?: FloatingOverlayOptions['collisionPadding']
  defaultOpen?: boolean
  disabled?: boolean
  forceMount?: boolean
  getPopupContainer?: FloatingOverlayOptions['getPopupContainer']
  hoverCloseDelay?: number
  hoverOpenDelay?: number
  open?: boolean
  placement?: FloatingOverlayOptions['placement']
  side?: FloatingOverlayOptions['side']
  sideOffset?: number
}
const props = withDefaults(defineProps<TooltipRootProps>(), { defaultOpen: false, open: undefined })
const emit = defineEmits<{
  openChange: [open: boolean, info: Parameters<NonNullable<TooltipOptions['onOpenChange']>>[1]]
}>()
const controlled = computed(() => props.open !== undefined)
const localOpen = ref(props.defaultOpen)
const triggerElement = shallowRef<HTMLElement | null>(null)
function handleOpenChange(
  open: boolean,
  info: Parameters<NonNullable<TooltipOptions['onOpenChange']>>[1],
) {
  if (!controlled.value) localOpen.value = open
  emit('openChange', open, info)
}
function createOptions(): TooltipOptions {
  return {
    ...props,
    open: controlled.value ? Boolean(props.open) : localOpen.value,
    onOpenChange: handleOpenChange,
  }
}
let latestOptions = createOptions()
const overlay = createTooltip(latestOptions)
const snapshot = useCoreStore(overlay)
provide(tooltipKey, {
  contentId: `fex-tooltip-${useId().replaceAll(':', '')}`,
  overlay,
  snapshot,
  triggerElement,
})
watchEffect(() => {
  const next = createOptions()
  if (!shallowEqualObject(latestOptions, next)) {
    latestOptions = next
    overlay.setOptions(next)
  }
})
onBeforeUnmount(() => overlay.destroy())
</script>
<template><slot /></template>

// packages/@fex-design/components/angular/src/primitive/tooltip/tooltip-root.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  type OnChanges,
  type OnDestroy,
} from '@angular/core'
import {
  createTooltip,
  type Tooltip as TooltipCore,
  type TooltipOptions,
} from '@fex-design/core/tooltip/create-tooltip'
import { createCoreStoreSignal } from '@fex-design/angular/signals/core-store-signal'

let tooltipId = 0

@Component({
  selector: 'div[tooltipRoot], span[tooltipRoot]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: '<ng-content />',
})
export class Tooltip implements OnChanges, OnDestroy {
  @Input() open?: boolean
  @Input() defaultOpen = false
  @Input() disabled?: boolean
  @Input() placement?: TooltipOptions['placement']
  @Input() side?: TooltipOptions['side']
  @Input() align?: TooltipOptions['align']
  @Input() sideOffset?: number
  @Input() alignOffset?: number
  @Input() avoidCollisions?: TooltipOptions['avoidCollisions']
  @Input() hoverOpenDelay?: number
  @Input() hoverCloseDelay?: number
  @Input() closeDelay?: number
  @Input() getPopupContainer?: TooltipOptions['getPopupContainer']
  @Output() openChange = new EventEmitter<boolean>()
  readonly contentId = `tooltip-${++tooltipId}`
  private localOpen = this.defaultOpen
  readonly overlay: TooltipCore = createTooltip(this.options())
  readonly snapshot = createCoreStoreSignal(this.overlay)
  private options(): TooltipOptions {
    return {
      open: this.open ?? this.localOpen,
      disabled: this.disabled,
      placement: this.placement,
      side: this.side,
      align: this.align,
      sideOffset: this.sideOffset,
      alignOffset: this.alignOffset,
      avoidCollisions: this.avoidCollisions,
      hoverOpenDelay: this.hoverOpenDelay,
      hoverCloseDelay: this.hoverCloseDelay,
      closeDelay: this.closeDelay,
      getPopupContainer: this.getPopupContainer,
      onOpenChange: (open) => {
        if (this.open === undefined) {
          this.localOpen = open
          this.overlay?.setOptions(this.options())
        }
        this.openChange.emit(open)
      },
    }
  }
  ngOnChanges() {
    this.overlay.setOptions(this.options())
  }
  ngOnDestroy() {
    this.overlay.destroy()
  }
}
