// packages/@fex-design/components/react/src/primitive/input-number/input-number-clear.tsx
import type { ComponentProps } from 'react'
import { InputClear } from '../input'
import { useInputNumberContext } from './input-number-context'

export interface InputNumberClearProps extends ComponentProps<typeof InputClear> {}

export function InputNumberClear({ onClick, ...props }: InputNumberClearProps) {
  const inputNumber = useInputNumberContext('InputNumberClear')
  return (
    <InputClear
      {...props}
      data-slot="input-number-clear"
      onClick={(event) => {
        onClick?.(event)
        if (!event.defaultPrevented) inputNumber.clear(event.nativeEvent)
      }}
    />
  )
}

// packages/@fex-design/components/solid/src/primitive/input-number/input-number-clear.tsx
import type { ComponentProps } from 'solid-js'
import { InputClear } from '../input'
import { useInputNumberContext } from './input-number-context'
export function InputNumberClear(props: ComponentProps<typeof InputClear>) {
  const n = useInputNumberContext('InputNumberClear')
  return (
    <InputClear
      {...props}
      data-slot="input-number-clear"
      onClick={(e) => {
        if (typeof props.onClick === 'function') props.onClick(e)
        if (!e.defaultPrevented) n.clear(e)
      }}
    />
  )
}
