// packages/@fex-design/svelte/src/primitive/input/input-clear.svelte
<script lang="ts">
  import { inputClearClassName } from "@fex-design/styles/input";
  import { cn } from "@fex/utils";
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import CircleXIcon from "../../icon/circle-x.svelte";
  import { getInputContext } from "./context";

  interface Props extends Omit<HTMLButtonAttributes, "class"> {
    class?: string;
    forceMount?: boolean;
    children?: Snippet;
  }

  let {
    class: className,
    forceMount = false,
    children,
    onclick,
    ...rest
  }: Props = $props();
  const input = getInputContext("InputClear");
</script>

{#if forceMount || input.canClear()}
  <button
    type="button"
    aria-label="Clear input"
    {...rest}
    data-slot="input-clear"
    disabled={!forceMount && !input.canClear()}
    class={cn(inputClearClassName, className)}
    onclick={(event) => {
      onclick?.(event);
      if (!event.defaultPrevented) input.clear();
    }}
  >
    {#if children}{@render children()}{:else}<CircleXIcon />{/if}
  </button>
{/if}

// packages/@fex-design/components/react/src/primitive/input/input-clear.tsx
import { inputClearClassName } from "@fex-design/components-styles/input"
import { cn } from "@fex-design/utils"
import type { ComponentProps, MouseEvent, ReactNode, Ref } from "react"
import { CircleXIcon } from "@fex-design/react/icons/circle-x"
import { useInputContext } from "./input-context"

export interface InputClearProps extends Omit<ComponentProps<"button">, "type"> {
  ref?: Ref<HTMLButtonElement> | undefined
  children?: ReactNode
}

export function InputClear({
  className,
  children,
  "aria-label": ariaLabel = "Clear input",
  onClick,
  ref,
  ...props
}: InputClearProps) {
  const input = useInputContext("InputClear")

  return (
    <button
      {...props}
      ref={ref}
      type="button"
      aria-label={ariaLabel}
      data-slot="input-clear"
      className={cn(inputClearClassName, className)}
      onClick={(event: MouseEvent<HTMLButtonElement>) => {
        onClick?.(event)
        if (!event.defaultPrevented) input.clear()
      }}
    >
      {children ?? <CircleXIcon />}
    </button>
  )
}
