// packages/@fex-design/vue/src/primitive/context-menu/context-menu-item.vue
<script setup lang="ts">
import { useContextMenuContext } from './context'
const { controller } = useContextMenuContext('ContextMenuItem')
const emit = defineEmits<{ click: [MouseEvent] }>()
function click(event: MouseEvent) {
  emit('click', event)
  if (!event.defaultPrevented)
    controller.overlay.close({ reason: 'manual', source: 'menu-item', event })
}
</script>
<template>
  <button type="button" role="menuitem" @click="click"><slot /></button>
</template>

// packages/@fex-design/components/react/src/primitive/context-menu/context-menu-item.tsx
import type { ComponentProps } from "react"
import { useContextMenuContext } from "./context-menu-context"

export type ContextMenuItemProps = ComponentProps<"button">

export function ContextMenuItem(props: ContextMenuItemProps) {
  const { controller } = useContextMenuContext("ContextMenuItem")
  return (
    <button
      {...props}
      type={props.type ?? "button"}
      role={props.role ?? "menuitem"}
      onClick={(event) => {
        props.onClick?.(event)
        if (!event.defaultPrevented)
          controller.overlay.close({
            reason: "manual",
            source: "menu-item",
            event: event.nativeEvent,
          })
      }}
    />
  )
}
