// packages/@fex-design/react/src/primitive/separator/examples/list.tsx
import { Separator } from '@fex-design/react/primitive/separator'
import { Card } from '@fex-design/react/ui/card'
const items = [
  ['Workspace', 'Fex Design'],
  ['Plan', 'Team'],
  ['Region', 'Asia Pacific'],
]
export const ListDemo = () => (
  <Card title="List" description="Place separators between rows, not after the final item.">
    <div className="grid max-w-lg">
      {items.map(([label, value], index) => (
        <div key={label}>
          <div className="flex justify-between py-2">
            <span>{label}</span>
            <span className="text-muted-foreground">{value}</span>
          </div>
          {index < items.length - 1 && <Separator />}
        </div>
      ))}
    </div>
  </Card>
)

// packages/@fex-design/vue/src/primitive/separator/examples/list.vue
<script setup lang="ts">
import { Separator } from '@fex-design/vue/primitive/separator'
import Card from '@fex-design/vue/ui/card'
const items = [
  ['Workspace', 'Fex Design'],
  ['Plan', 'Team'],
  ['Region', 'Asia Pacific'],
]
</script>
<template>
  <Card title="List" description="Place separators between rows, not after the final item."
    ><div class="grid max-w-lg">
      <div v-for="([label, value], index) in items" :key="label">
        <div class="flex justify-between py-2">
          <span>{{ label }}</span
          ><span class="text-muted-foreground">{{ value }}</span>
        </div>
        <Separator v-if="index < items.length - 1" />
      </div></div
  ></Card>
</template>
