// apps/vue-app/src/pages/Watermark/restore-demo.vue
<script setup lang="ts">
import { Watermark } from '@fex-design/vue/primitive/watermark'
import { Button } from '@fex-design/vue/ui/button'
import Card from '@fex-design/vue/ui/card'

function removeWatermark() {
  document.querySelector('[data-demo="vue-watermark-restore"] [data-slot="watermark"]')?.remove()
}
</script>

<template>
  <Card title="Restore" description="Removing the generated watermark layer appends it back.">
    <div class="space-y-2">
      <Button variant="outline" @click="removeWatermark">Remove generated layer</Button>
      <Watermark
        :content="['FEX Admin', 'Do not distribute']"
        data-demo="vue-watermark-restore"
        class="h-56 rounded-md border border-border bg-background"
      >
        <div class="grid h-full place-items-center p-4 text-center text-sm text-muted-foreground">
          The controller observes direct child removal on this root and restores the layer.
        </div>
      </Watermark>
    </div>
  </Card>
</template>

// apps/svelte-app/src/routes/watermark/restore-demo.svelte
<script lang="ts">
  import Watermark from '@fex-design/svelte/primitive/watermark'
  import { Button } from '@fex-design/svelte/ui/button'
  import Card from '@fex-design/svelte/ui/card'

  function removeWatermark() {
    document.querySelector('[data-demo="svelte-watermark-restore"] [data-slot="watermark"]')?.remove()
  }
</script>

<Card title="Restore" description="Removing the generated watermark layer appends it back.">
  <div class="space-y-2">
    <Button variant="outline" onclick={removeWatermark}>Remove generated layer</Button>
    <Watermark
      content={['FEX Admin', 'Do not distribute']}
      data-demo="svelte-watermark-restore"
      class="h-56 rounded-md border border-border bg-background"
    >
      <div class="grid h-full place-items-center p-4 text-center text-sm text-muted-foreground">
        The controller observes direct child removal on this root and restores the layer.
      </div>
    </Watermark>
  </div>
</Card>
