// apps/vue-app/src/pages/Tooltip/style-demo.vue
<script setup lang="ts">
import {
  TooltipArrow,
  TooltipContent,
  TooltipPortal,
  TooltipRoot,
  TooltipTrigger,
} from '@fex-design/vue/primitive/tooltip'
import { Button } from '@fex-design/vue/ui/button'
</script>
<template>
  <div class="flex gap-2">
    <TooltipRoot
      ><TooltipTrigger v-slot="slot"
        ><Button v-bind="slot.props" :ref="slot.ref" variant="outline"
          >Custom color</Button
        ></TooltipTrigger
      ><TooltipPortal
        ><TooltipContent class="[--tooltip-background:#db2777] [--tooltip-foreground:white]"
          >One variable colors both surfaces<TooltipArrow /></TooltipContent></TooltipPortal></TooltipRoot
    ><TooltipRoot
      ><TooltipTrigger v-slot="slot"
        ><Button v-bind="slot.props" :ref="slot.ref" variant="outline"
          >Without arrow</Button
        ></TooltipTrigger
      ><TooltipPortal
        ><TooltipContent>No TooltipArrow is rendered</TooltipContent></TooltipPortal
      ></TooltipRoot
    >
  </div>
</template>

// apps/svelte-app/src/routes/tooltip/style-demo.svelte
<script lang="ts">
  import TooltipRoot from '@fex-design/svelte/primitive/tooltip'
  import TooltipArrow from '@fex-design/svelte/primitive/tooltip-arrow'
  import TooltipContent from '@fex-design/svelte/primitive/tooltip-content'
  import TooltipPortal from '@fex-design/svelte/primitive/tooltip-portal'
  import TooltipTrigger from '@fex-design/svelte/primitive/tooltip-trigger'
  import Button from '@fex-design/svelte/ui/button'
</script>
<div class="flex gap-2"><TooltipRoot><TooltipTrigger>{#snippet children(slot)}<Button {...slot.props} action={slot.action} variant="outline">Custom color</Button>{/snippet}</TooltipTrigger><TooltipPortal><TooltipContent class="[--tooltip-background:#db2777] [--tooltip-foreground:white]">One variable colors both surfaces<TooltipArrow /></TooltipContent></TooltipPortal></TooltipRoot><TooltipRoot><TooltipTrigger>{#snippet children(slot)}<Button {...slot.props} action={slot.action} variant="outline">Without arrow</Button>{/snippet}</TooltipTrigger><TooltipPortal><TooltipContent>No TooltipArrow is rendered</TooltipContent></TooltipPortal></TooltipRoot></div>
