// packages/@fex-design/components/react/src/primitive/context-menu/context-menu-portal.tsx
import { createPortal } from "react-dom"
import type { ReactNode } from "react"
import { useContextMenu } from "./use-context-menu"

export interface ContextMenuPortalProps {
  children?: ReactNode
  container?: HTMLElement | null
  forceMount?: boolean
}

export function ContextMenuPortal({ children, container, forceMount }: ContextMenuPortalProps) {
  const { overlay, snapshot } = useContextMenu("ContextMenuPortal")
  const popupContainer = container ?? overlay.resolvePopupContainer()
  if (!popupContainer || (!snapshot.overlay.mounted && !forceMount)) return null
  return createPortal(children, popupContainer)
}

// packages/@fex-design/components/solid/src/primitive/context-menu/context-menu-portal.tsx
import { Portal } from "solid-js/web"
import { Show, type ParentProps } from "solid-js"
import { useContextMenuContext } from "./context-menu-context"

export interface ContextMenuPortalProps {
  container?: HTMLElement | null
}

export function ContextMenuPortal(props: ParentProps<ContextMenuPortalProps>) {
  const context = useContextMenuContext("ContextMenuPortal")
  return (
    <Show when={context.snapshot().overlay.mounted}>
      <Portal
        mount={
          props.container ?? context.controller.overlay.resolvePopupContainer() ?? document.body
        }
      >
        {props.children}
      </Portal>
    </Show>
  )
}
