// packages/@fex-design/components/react/src/primitive/alert/alert-title.tsx
import { alertTitleClassName } from "@fex-design/components-styles/alert"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type AlertTitleProps = ComponentProps<"div">

export function AlertTitle({ className, ...props }: AlertTitleProps) {
  return <div data-slot="alert-title" className={cn(alertTitleClassName, className)} {...props} />
}

// packages/@fex-design/components/solid/src/primitive/alert/alert-title.tsx
import { alertTitleClassName } from "@fex-design/components-styles/alert"
import { cn } from "@fex-design/utils"
import type { JSX, ParentProps } from "solid-js"
import { splitProps } from "solid-js"

export type AlertTitleProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

export function AlertTitle(props: AlertTitleProps) {
  const [local, rest] = splitProps(props, ["class", "children"])
  return (
    <div {...rest} data-slot="alert-title" class={cn(alertTitleClassName, local.class)}>
      {local.children}
    </div>
  )
}
