// apps/svelte-app/src/routes/dropdown/+page.svelte
<script lang="ts">
  import Card from '@fex-design/svelte/ui/card'
  import BasicDemo from './basic-demo.svelte'
  import CustomPanelDemo from './custom-panel-demo.svelte'
  import CustomTriggerDemo from './custom-trigger-demo.svelte'
  import NestedDemo from './nested-demo.svelte'
</script>
<main class="min-h-screen bg-secondary-background px-2 md:px-6 py-4"><div class="mx-auto w-full max-w-5xl space-y-4"><header class="space-y-2"><a class="text-sm text-muted-foreground" href="/">Back home</a><div><h1 class="text-2xl font-semibold">Dropdown</h1><p class="mt-2 text-sm text-muted-foreground">Primitive composition of Popover and Menu.</p></div></header><div class="space-y-4"><Card title="Basic" description="A regular action menu."><BasicDemo /></Card><Card title="Nested menus" description="A parent item triggers another Popover."><NestedDemo /></Card><Card title="Custom panel" description="Composable additional content."><CustomPanelDemo /></Card><Card title="Custom trigger" description="The trigger snippet binds to the caller element."><CustomTriggerDemo /></Card></div></div></main>

// apps/vue-app/src/pages/Dropdown/index.vue
<script setup lang="ts">
import Card from '@fex-design/vue/ui/card'
import BasicDemo from './basic-demo.vue'
import CustomPanelDemo from './custom-panel-demo.vue'
import CustomTriggerDemo from './custom-trigger-demo.vue'
import NestedDemo from './nested-demo.vue'
</script>

<template><main class="min-h-screen bg-secondary-background px-2 md:px-6 py-4"><div class="mx-auto w-full max-w-5xl space-y-4"><header class="space-y-2"><RouterLink class="text-sm text-muted-foreground" to="/">Back home</RouterLink><div><h1 class="text-2xl font-semibold">Dropdown</h1><p class="mt-2 text-sm text-muted-foreground">Primitive composition of Popover and Menu.</p></div></header><div class="space-y-4"><Card title="Basic" description="A regular action menu."><BasicDemo /></Card><Card title="Nested menus" description="Each parent item triggers another Popover containing Menu."><NestedDemo /></Card><Card title="Custom panel" description="Composable additional content."><CustomPanelDemo /></Card><Card title="Custom trigger" description="Trigger slot binds to the caller element."><CustomTriggerDemo /></Card></div></div></main></template>
