// packages/@fex-design/components/react/src/primitive/avatar/examples/shape.tsx
import { Avatar, AvatarFallback } from '@fex-design/react/primitive/avatar'

export function ShapeExample() {
  return (
    <div className="flex items-center gap-3">
      <Avatar shape="circle">
        <AvatarFallback>CI</AvatarFallback>
      </Avatar>
      <Avatar shape="square">
        <AvatarFallback>SQ</AvatarFallback>
      </Avatar>
    </div>
  )
}

// packages/@fex-design/vue/src/primitive/avatar/examples/shape.vue
<script setup lang="ts">import { Avatar, AvatarFallback } from '@fex-design/vue/primitive/avatar'</script>
<template><div class="flex items-center gap-3"><Avatar shape="circle"><AvatarFallback>CI</AvatarFallback></Avatar><Avatar shape="square"><AvatarFallback>SQ</AvatarFallback></Avatar></div></template>
