// apps/react-app/src/pages/Avatar/group-demo.tsx
import { Avatar, AvatarGroup } from '@fex-design/react/ui/avatar'
import { Card } from '@fex-design/react/ui/card'

export function GroupDemo() {
  return (
    <Card title="Avatar group" description="Keep the first avatars visible and summarize the rest.">
      <AvatarGroup maxCount={3}>
        {['AM', 'BL', 'CS', 'DT', 'ER'].map((name) => <Avatar key={name}>{name}</Avatar>)}
      </AvatarGroup>
    </Card>
  )
}

// apps/solid-app/src/pages/Avatar/group-demo.tsx
import { Avatar, AvatarGroup } from '@fex-design/solid/ui/avatar'
import { Card } from '@fex-design/solid/ui/card'
import { For } from 'solid-js'
export function GroupDemo() {
  return (
    <Card title="Avatar group" description="Keep the first avatars visible and summarize the rest.">
      <AvatarGroup maxCount={3}>
        <For each={['AM', 'BL', 'CS', 'DT', 'ER']}>{(name) => <Avatar>{name}</Avatar>}</For>
      </AvatarGroup>
    </Card>
  )
}
