// apps/vue-app/src/pages/Bubble/actions-demo.vue
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from '@fex-design/vue/primitive/avatar'
import {
  Bubble,
  BubbleAction,
  BubbleActions,
  BubbleContent,
  BubbleReaction,
  BubbleReactions,
} from '@fex-design/vue/primitive/bubble'
import {
  Message,
  MessageAvatar,
  MessageBody,
  MessageContent,
} from '@fex-design/vue/primitive/message'
import Button from '@fex-design/vue/ui/button'
import Card from '@fex-design/vue/ui/card'
import { ref } from 'vue'
const liked = ref(false)
</script>
<template>
  <Card
    title="Action and reaction positions"
    description="side controls the top or bottom edge; align controls the logical start or end position."
    ><div class="mx-auto grid w-full max-w-2xl gap-8 py-8">
      <Message
        ><MessageAvatar
          ><Avatar
            ><AvatarImage src="/avatar-demo.svg" alt="Oliver" /><AvatarFallback
              >O</AvatarFallback
            ></Avatar
          ></MessageAvatar
        ><MessageBody
          ><MessageContent
            ><Bubble
              ><BubbleContent>Tests passed on the first try. All 142 of them.</BubbleContent
              ><BubbleActions side="top" align="end"
                ><BubbleAction>Pin</BubbleAction
                ><BubbleAction
                  ><template #render="{ props }"
                    ><Button v-bind="props" variant="ghost" size="xs">Copy</Button></template
                  ></BubbleAction
                ></BubbleActions
              ><BubbleReactions side="bottom" align="start"
                ><BubbleReaction aria-label="Helpful" :pressed="liked" @change="liked = $event"
                  >🎉</BubbleReaction
                ><BubbleReaction aria-label="Celebrate" :count="2"
                  >👏</BubbleReaction
                ></BubbleReactions
              ></Bubble
            ></MessageContent
          ></MessageBody
        ></Message
      ><Message side="end"
        ><MessageBody
          ><MessageContent
            ><Bubble variant="solid"
              ><BubbleContent>Are you sure I can run this command?</BubbleContent
              ><BubbleReactions side="top" align="end"
                ><BubbleReaction aria-label="Watching">👀</BubbleReaction></BubbleReactions
              ><BubbleActions side="bottom" align="end"
                ><BubbleAction>Yes, run it</BubbleAction
                ><BubbleAction>Cancel</BubbleAction></BubbleActions
              ></Bubble
            ></MessageContent
          ></MessageBody
        ></Message
      >
      <p class="text-center text-xs text-muted-foreground">
        Every part accepts class, so callers can replace the preset edge placement.
      </p>
    </div></Card
  >
</template>

// apps/solid-app/src/pages/Bubble/actions-demo.tsx
import { Avatar, AvatarFallback, AvatarImage } from '@fex-design/solid/primitive/avatar'
import {
  Bubble,
  BubbleAction,
  BubbleActions,
  BubbleContent,
  BubbleReaction,
  BubbleReactions,
} from '@fex-design/solid/primitive/bubble'
import {
  Message,
  MessageAvatar,
  MessageBody,
  MessageContent,
} from '@fex-design/solid/primitive/message'
import { Button } from '@fex-design/solid/ui/button'
import { Card } from '@fex-design/solid/ui/card'
import { createSignal } from 'solid-js'
export function ActionsDemo() {
  const [liked, setLiked] = createSignal(false)
  return (
    <Card
      title="Action and reaction positions"
      description="side controls the top or bottom edge; align controls the logical start or end position."
    >
      <div class="mx-auto grid w-full max-w-2xl gap-8 py-8">
        <Message>
          <MessageAvatar>
            <Avatar>
              <AvatarImage src="/avatar-demo.svg" alt="Oliver" />
              <AvatarFallback>O</AvatarFallback>
            </Avatar>
          </MessageAvatar>
          <MessageBody>
            <MessageContent>
              <Bubble>
                <BubbleContent>Tests passed on the first try. All 142 of them.</BubbleContent>
                <BubbleActions side="top" align="end">
                  <BubbleAction>Pin</BubbleAction>
                  <BubbleAction
                    render={({ props }) => (
                      <Button class={props.class as string} variant="ghost" size="xs">
                        Copy
                      </Button>
                    )}
                  />
                </BubbleActions>
                <BubbleReactions side="bottom" align="start">
                  <BubbleReaction aria-label="Helpful" pressed={liked()} onChange={setLiked}>
                    🎉
                  </BubbleReaction>
                  <BubbleReaction aria-label="Celebrate" count={2}>
                    👏
                  </BubbleReaction>
                </BubbleReactions>
              </Bubble>
            </MessageContent>
          </MessageBody>
        </Message>
        <Message side="end">
          <MessageBody>
            <MessageContent>
              <Bubble variant="solid">
                <BubbleContent>Are you sure I can run this command?</BubbleContent>
                <BubbleReactions side="top" align="end">
                  <BubbleReaction aria-label="Watching">👀</BubbleReaction>
                </BubbleReactions>
                <BubbleActions side="bottom" align="end">
                  <BubbleAction>Yes, run it</BubbleAction>
                  <BubbleAction>Cancel</BubbleAction>
                </BubbleActions>
              </Bubble>
            </MessageContent>
          </MessageBody>
        </Message>
        <p class="text-center text-xs text-muted-foreground">
          Every part accepts class, so callers can replace the preset edge placement.
        </p>
      </div>
    </Card>
  )
}
