// apps/react-app/src/pages/TimePicker/disabled-demo.tsx
import { Card } from '@fex-design/react/ui/card'
import { DemoTimePicker } from './demo-time-picker'
export function DisabledDemo() {
  return (
    <Card title="禁用与校验样式" description="disabled 阻止交互；invalid 只展示外部校验状态。">
      <div className="flex gap-3">
        <DemoTimePicker disabled defaultValue={{ hour: 8, minute: 0, second: 0 }} />
        <DemoTimePicker invalid />
      </div>
    </Card>
  )
}

// apps/svelte-app/src/routes/time-picker/disabled-demo.svelte
<script>
  import Card from "@fex-design/svelte/ui/card";
  import DemoTimePicker from "./demo-time-picker.svelte";
</script>

<Card title="禁用与校验样式"
  ><div class="flex gap-3">
    <DemoTimePicker
      disabled
      defaultValue={{ hour: 8, minute: 0, second: 0 }}
    /><DemoTimePicker invalid />
  </div></Card
>
