// packages/@fex-design/vue/src/primitive/popover/popover-arrow.vue
<script setup lang="ts">
import { popoverArrowClassName } from '@fex-design/styles/popover'
import { cn } from '@fex/utils'
import type { ComponentPublicInstance, HTMLAttributes } from 'vue'
import { computed, onBeforeUnmount } from 'vue'
import { usePopoverContext } from './context'

defineOptions({ name: 'PopoverArrow' })

const props = defineProps<{ class?: string; style?: HTMLAttributes['style'] }>()
const { arrowElement, overlay, snapshot } = usePopoverContext('PopoverArrow')
const arrowClass = computed(() => cn(popoverArrowClassName, props.class))
const arrowStyle = computed(() => {
  // 必须在 computed 中读取 snapshot.value.side，确保 Vue 建立响应式依赖。
  // 如果 const side = snapshot.value.side 后再使用，console 可能看到 core 已更新，但 DOM 箭头仍是旧方向。
  const sideStyle =
    snapshot.value.side === 'left' || snapshot.value.side === 'right'
      ? {
          top: 'var(--floating-arrow-y, 0px)',
        }
      : {
          left: 'var(--floating-arrow-x, 0px)',
        }

  return sideStyle
})

function setArrowElement(element: Element | ComponentPublicInstance | null) {
  // arrow 也是 Floating UI middleware 的输入，不只是展示 DOM。
  // ref 更新后必须同步给 core，才能重新计算 --floating-arrow-x/y。
  arrowElement.value = element instanceof HTMLDivElement ? element : null
  overlay.setArrowElement(arrowElement.value)
}

onBeforeUnmount(() => {
  arrowElement.value = null
  overlay.setArrowElement(null)
})
</script>

<template>
  <div
    v-if="snapshot.arrow"
    :ref="setArrowElement"
    data-slot="popover-arrow"
    :data-side="snapshot.side"
    :class="arrowClass"
    :style="[arrowStyle, props.style]"
  />
</template>

// packages/@fex-design/solid/src/primitive/popover/popover-arrow.tsx
import { onCleanup, Show, splitProps, type JSX } from 'solid-js'
import { cn } from '@fex/utils'
import { popoverArrowClassName } from '@fex-design/styles/popover'
import { usePopover } from './popover-context'

export type PopoverArrowProps = JSX.HTMLAttributes<HTMLDivElement>

export function PopoverArrow(props: PopoverArrowProps) {
  const [local, rest] = splitProps(props, ['class', 'style', 'ref'])
  const { arrowElement, overlay, snapshot } = usePopover('PopoverArrow')
  const sideStyle = () => {
    // sideStyle 必须在 JSX 中调用，才能追踪 snapshot().side。
    return snapshot().side === 'left' || snapshot().side === 'right'
      ? {
          top: 'var(--floating-arrow-y, 0px)',
        }
      : {
          left: 'var(--floating-arrow-x, 0px)',
        }
  }

  onCleanup(() => {
    arrowElement.current = null
    overlay.setArrowElement(null)
  })

  return (
    <Show when={snapshot().arrow}>
      <div
        {...rest}
        ref={(element) => {
          // arrow DOM 是 Floating UI arrow middleware 的输入，注册后 core 会重新计算箭头坐标。
          arrowElement.current = element
          if (typeof local.ref === 'function') local.ref(element)
          overlay.setArrowElement(element)
        }}
        data-slot="popover-arrow"
        data-side={snapshot().side}
        class={cn(popoverArrowClassName, local.class)}
        style={
          typeof local.style === 'string'
            ? `${Object.entries(sideStyle())
                .map(([key, value]) => `${key}:${value}`)
                .join(';')};${local.style}`
            : { ...sideStyle(), ...local.style }
        }
      />
    </Show>
  )
}
