// packages/@fex-design/svelte/src/primitive/color-picker/gradient-picker-track.svelte
<script lang="ts">
  import { formatLinearGradient } from "@fex-design/core/gradient/gradient";
  import { gradientPickerTrackClassName } from "@fex-design/styles/color-picker";
  import { cn } from "@fex/utils";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { useGradientPicker } from "./context";
  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
    children?: Snippet;
  }
  let { class: className, children, ...rest }: Props = $props();
  const picker = useGradientPicker(),
    snapshot = $derived(picker.snapshot()),
    background = $derived(formatLinearGradient(snapshot.value));
</script>

<div
  {...rest}
  class={cn(gradientPickerTrackClassName, className)}
  style:--gradient-picker-background={background}
  onpointerdown={(event) => {
    if (event.target !== event.currentTarget || snapshot.disabled) return;
    const rect = event.currentTarget.getBoundingClientRect();
    picker.controller.addStop((event.clientX - rect.left) / rect.width);
  }}
>
  {@render children?.()}
</div>

// packages/@fex-design/components/solid/src/primitive/color-picker/gradient-picker-track.tsx
import { formatLinearGradient } from '@fex-design/core/gradient/gradient'
import { gradientPickerTrackClassName } from '@fex-design/components-styles/color-picker'
import { cn } from '@fex-design/utils'
import { type JSX, type ParentProps } from 'solid-js'
import { useGradientPicker } from './color-picker-context'

export type GradientPickerTrackProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

export function GradientPickerTrack(props: GradientPickerTrackProps) {
  const picker = useGradientPicker()
  return (
    <div
      {...props}
      class={cn(gradientPickerTrackClassName, props.class)}
      style={{
        '--gradient-picker-background': formatLinearGradient(picker.snapshot().value),
        ...(props.style as JSX.CSSProperties),
      }}
      onPointerDown={(event) => {
        if (event.target !== event.currentTarget || picker.snapshot().disabled) return
        const rect = event.currentTarget.getBoundingClientRect()
        picker.controller.addStop((event.clientX - rect.left) / rect.width)
      }}
    >
      {props.children}
    </div>
  )
}
