// packages/@fex-design/vue/src/ui/avatar/avatar.vue
<script setup lang="ts">
import PrimitiveAvatar from '../../primitive/avatar/avatar.vue'
import AvatarImage from '../../primitive/avatar/avatar-image.vue'
import AvatarFallback from '../../primitive/avatar/avatar-fallback.vue'
import type { AvatarStyleProps } from '@fex-design/styles/avatar'
import type { AvatarClassNames, AvatarStyles } from '@fex-design/core/avatar/types'
import type { StyleValue } from 'vue'
defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{ src?: string; alt?: string; srcSet?: string; fallback?: string; size?: AvatarStyleProps['size']; shape?: AvatarStyleProps['shape']; classNames?: AvatarClassNames; styles?: AvatarStyles<StyleValue> }>(), { alt: '', size: 'md', shape: 'circle' })
</script>
<template>
  <PrimitiveAvatar v-bind="$attrs" :size="props.size" :shape="props.shape" :class="[$attrs.class, props.classNames?.root]" :style="[$attrs.style, props.styles?.root]">
    <AvatarImage v-if="props.src" :src="props.src" :alt="props.alt" :srcset="props.srcSet" :class="props.classNames?.image" :style="props.styles?.image" />
    <AvatarFallback :class="props.classNames?.fallback" :style="props.styles?.fallback">{{ props.fallback }}<slot v-if="props.fallback === undefined" /></AvatarFallback>
  </PrimitiveAvatar>
</template>

// packages/@fex-design/svelte/src/ui/avatar/avatar.svelte
<script lang="ts">
  import PrimitiveAvatar from '../../primitive/avatar/avatar.svelte'
  import AvatarImage from '../../primitive/avatar/avatar-image.svelte'
  import AvatarFallback from '../../primitive/avatar/avatar-fallback.svelte'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import type { AvatarClassNames, AvatarStyles } from '@fex-design/core/avatar/types'
  import { cn } from '@fex/utils'
  interface Props extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> { src?: string; alt?: string; srcset?: string; fallback?: Snippet; children?: Snippet; size?: 'sm' | 'md' | 'lg'; shape?: 'circle' | 'square'; classNames?: AvatarClassNames; styles?: AvatarStyles<string> }
  let { src, alt = '', srcset, fallback, children, class: className, style, classNames, styles, ...rest }: Props = $props()
</script>
<PrimitiveAvatar {...rest} class={cn(className, classNames?.root)} style={[style, styles?.root].filter(Boolean).join(';')}>
  {#if src}<AvatarImage {src} {alt} {srcset} class={classNames?.image} style={styles?.image} />{/if}
  <AvatarFallback class={classNames?.fallback} style={styles?.fallback}>{@render (fallback ?? children)?.()}</AvatarFallback>
</PrimitiveAvatar>
