// apps/vue-app/src/pages/DataTable/row-editing-demo.vue
<script setup lang="ts">
import { columnSizingFeature } from '@fex-design/core/data-table/features/column-sizing'
import type { DataTableColumnMeta } from '@fex-design/core/data-table/types'
import { DataTable, tableFeatures, type ColumnDef } from '@fex-design/vue/primitive/data-table'
import { useDataTable } from '@fex-design/vue/composables/use-data-table'
import { InputControl, InputRoot } from '@fex-design/vue/primitive/input'
import { Button } from '@fex-design/vue/ui/button'
import { h, ref, type Component } from 'vue'
import { people6, type Person } from './data'
import DemoSection from './demo-section.vue'
type F = {
  columnSizingFeature: typeof columnSizingFeature
  columnMeta: DataTableColumnMeta<F, Person>
}
const f: F = tableFeatures({ columnSizingFeature, columnMeta: {} })
const rows = ref(people6),
  draft = ref<Person | null>(null),
  R = InputRoot as Component,
  I = InputControl as Component,
  B = Button as Component
const edit = (field: 'name' | 'department' | 'status', row: Person, value: unknown) =>
  draft.value?.id === row.id
    ? h(R, { value: String(draft.value[field]) }, () =>
        h(I, {
          onInput: (event: Event) => {
            draft.value = { ...draft.value!, [field]: (event.target as HTMLInputElement).value }
          },
        }),
      )
    : String(value ?? '')
const columns: ColumnDef<F, Person>[] = [
  {
    accessorKey: 'name',
    header: 'Name',
    cell: ({ row, getValue }) => edit('name', row.original, getValue()),
  },
  {
    accessorKey: 'department',
    header: 'Department',
    cell: ({ row, getValue }) => edit('department', row.original, getValue()),
  },
  {
    accessorKey: 'status',
    header: 'Status',
    cell: ({ row, getValue }) => edit('status', row.original, getValue()),
  },
  {
    id: '__actions__',
    header: 'Actions',
    size: 180,
    cell: ({ row }) =>
      draft.value?.id === row.id
        ? h('span', { class: 'inline-flex gap-1.5' }, [
            h(B, { size: 'sm', onClick: save }, () => 'Save'),
            h(
              B,
              { size: 'sm', variant: 'outline', onClick: () => (draft.value = null) },
              () => 'Cancel',
            ),
          ])
        : h(
            B,
            { size: 'sm', variant: 'outline', onClick: () => (draft.value = { ...row.original }) },
            () => 'Edit row',
          ),
  },
]
const table = useDataTable({ features: f, data: rows.value, columns, getRowId: (r) => r.id })
function save() {
  if (!draft.value) return
  rows.value = rows.value.map((row) => (row.id === draft.value!.id ? draft.value! : row))
  draft.value = null
  table.setDataTableOptions({ features: f, data: rows.value, columns, getRowId: (r) => r.id })
}
</script>
<template>
  <DemoSection
    title="Row editing"
    description="Edit row creates one application-owned draft. Save replaces that row in the caller data; Cancel discards the draft without touching the table data."
    ><section class="space-y-1.5">
      <h3 class="text-sm font-medium text-foreground">Draft, save and cancel</h3>
      <DataTable :table="table" /></section
  ></DemoSection>
</template>

// apps/svelte-app/src/routes/data-table/row-editing-demo.svelte
<script lang="ts">
  import { columnSizingFeature } from "@fex-design/core/data-table/features/column-sizing";
  import type { DataTableColumnMeta } from "@fex-design/core/data-table/types";
  import {
    DataTable,
    tableFeatures,
    type ColumnDef,
  } from "@fex-design/svelte/primitive/data-table";
  import InputRoot from "@fex-design/svelte/primitive/input";
  import InputControl from "@fex-design/svelte/primitive/input-control";
  import { Button } from "@fex-design/svelte/ui/button";
  import { createDataTable } from "@fex-design/svelte/stores/create-data-table";
  import { people6, type Person } from "./data";
  import DemoSection from "./demo-section.svelte";
  import type { Cell } from "@fex-design/svelte/primitive/data-table";
  import { untrack } from "svelte";
  type Features = {
    columnSizingFeature: typeof columnSizingFeature;
    columnMeta: DataTableColumnMeta<Features, Person>;
  };
  const features: Features = tableFeatures({
    columnSizingFeature,
    columnMeta: {},
  });
  let rows = $state(people6),
    draft = $state<Person | null>(null);
  const columns: ColumnDef<Features, Person>[] = [
    { accessorKey: "name", header: "Name" },
    { accessorKey: "department", header: "Department" },
    { accessorKey: "status", header: "Status" },
    { id: "__actions__", header: "Actions", size: 180 },
  ];
  const table = createDataTable({
    features,
    data: untrack(() => rows),
    columns,
    getRowId: (row) => row.id,
  });
  function updateField(
    fieldName: "name" | "department" | "status",
    value: string,
  ) {
    if (draft) draft = { ...draft, [fieldName]: value };
  }
  function save() {
    if (!draft) return;
    rows = rows.map((row) => (row.id === draft!.id ? draft! : row));
    draft = null;
    table.setDataTableOptions({
      features,
      data: rows,
      columns,
      getRowId: (row) => row.id,
    });
  }
</script>

{#snippet cell(
  item: Cell<Features, Person>,
)}{#if item.column.id === "__actions__"}{#if draft?.id === item.row.id}<span
        class="inline-flex gap-1.5"
        ><Button size="sm" onclick={save}>Save</Button><Button
          size="sm"
          variant="outline"
          onclick={() => (draft = null)}>Cancel</Button
        ></span
      >{:else}<Button
        size="sm"
        variant="outline"
        onclick={() => (draft = { ...item.row.original })}>Edit row</Button
      >{/if}{:else if draft?.id === item.row.id}<InputRoot
      value={String(
        draft?.[item.column.id as "name" | "department" | "status"] ?? "",
      )}
      ><InputControl
        oninput={(event) =>
          updateField(
            item.column.id as "name" | "department" | "status",
            event.currentTarget.value,
          )}
      /></InputRoot
    >{:else}{String(item.getValue() ?? "")}{/if}{/snippet}
<DemoSection
  title="Row editing"
  description="Edit row creates one application-owned draft. Save replaces that row in the caller data; Cancel discards the draft without touching the table data."
  ><section class="space-y-1.5">
    <h3 class="text-sm font-medium text-foreground">Draft, save and cancel</h3>
    <DataTable {table} {cell} />
  </section></DemoSection
>
