// apps/vue-app/src/pages/DataTable/sorting-demo.vue
<script setup lang="ts">
import {
  createSortedRowModel,
  rowSortingFeature,
  type SortFn,
  type SortingState,
} from '@fex-design/core/data-table/features/row-sorting'
import type { DataTableColumnMeta } from '@fex-design/core/data-table/types'
import {
  DataTable,
  DataTableSortButton,
  tableFeatures,
  type ColumnDef,
} from '@fex-design/vue/primitive/data-table'
import { useDataTable } from '@fex-design/vue/composables/use-data-table'
import { h, type Component } from 'vue'
import { people, type Person } from './data'
import DemoSection from './demo-section.vue'
const modules = { rowSortingFeature, sortedRowModel: createSortedRowModel() }
type Features = typeof modules & { columnMeta: DataTableColumnMeta<Features, Person> }
const features: Features = tableFeatures({ ...modules, columnMeta: {} })
const textSort: SortFn<Features, Person> = (a, b, id) =>
  String(a.getValue(id)).localeCompare(String(b.getValue(id)))
const numberSort: SortFn<Features, Person> = (a, b, id) =>
  Number(a.getValue(id)) - Number(b.getValue(id))
function grid(kind: 'local' | 'server' | 'mixed', initialSorting: SortingState = []) {
  const SortButton = DataTableSortButton as Component
  const columns: ColumnDef<Features, Person>[] = [
    {
      accessorKey: 'name',
      header: ({ column }) => h(SortButton, { column }, () => 'Name'),
      meta: kind === 'server' ? {} : { sortFn: textSort },
    },
    {
      accessorKey: 'status',
      header: ({ column }) => h(SortButton, { column }, () => 'Status'),
      meta: kind === 'local' ? { sortFn: textSort } : {},
    },
    {
      accessorKey: 'visits',
      header: ({ column }) => h(SortButton, { column }, () => 'Visits'),
      meta: kind === 'server' ? {} : { sortFn: numberSort, align: 'right' },
    },
  ]
  const table = useDataTable({
    features,
    data: people.slice(0, 7),
    columns,
    getRowId: (r) => r.id,
    enableMultiSort: true,
    isMultiSortEvent: () => true,
    initialState: { sorting: initialSorting },
  })
  return {
    table,
    title: '',
    remote: () =>
      table.dataTableSnapshot.value.state.sorting.filter(
        (item) =>
          !columns.find(
            (column) => ('accessorKey' in column ? column.accessorKey : column.id) === item.id,
          )?.meta?.sortFn,
      ),
  }
}
const grids = [
  {
    ...grid('local', [
      { id: 'status', desc: false },
      { id: 'visits', desc: true },
    ]),
    title: 'All local multi-sort',
  },
  { ...grid('server'), title: 'All server' },
  { ...grid('mixed'), title: 'Mixed per column' },
  {
    ...grid('server', [
      { id: 'status', desc: false },
      { id: 'visits', desc: true },
    ]),
    title: 'Remote multi-sort: Status asc, Visits desc',
  },
]
</script>
<template>
  <DemoSection
    title="Column sorting"
    description="Multi-sort is supported for local columns as well: each click adds or changes a priority and the superscript shows that priority. Columns without meta.sortFn remain remote terms in the same sorting state, while their pass-through comparator leaves local row order unchanged."
    ><div class="grid gap-3 xl:grid-cols-2">
      <section v-for="item in grids" :key="item.title" class="space-y-1.5">
        <h3 class="text-sm font-medium text-foreground">{{ item.title }}</h3>
        <DataTable :table="item.table" />
        <p class="text-xs text-muted-foreground">
          Remote request sorting:
          {{ item.remote().length ? JSON.stringify(item.remote()) : 'none' }}
        </p>
      </section>
    </div></DemoSection
  >
</template>

// apps/svelte-app/src/routes/data-table/sorting-demo.svelte
<script lang="ts">
  import {
    createSortedRowModel,
    rowSortingFeature,
    type SortFn,
    type SortingState,
  } from "@fex-design/core/data-table/features/row-sorting";
  import type { DataTableColumnMeta } from "@fex-design/core/data-table/types";
  import {
    DataTable,
    DataTableSortButton,
    tableFeatures,
    type ColumnDef,
  } from "@fex-design/svelte/primitive/data-table";
  import { createDataTable } from "@fex-design/svelte/stores/create-data-table";
  import { people, type Person } from "./data";
  import DemoSection from "./demo-section.svelte";
  import ReactiveTableText from "./reactive-table-text.svelte";
  import type { Header } from "@fex-design/svelte/primitive/data-table";
  const modules = { rowSortingFeature, sortedRowModel: createSortedRowModel() };
  type Features = typeof modules & {
    columnMeta: DataTableColumnMeta<Features, Person>;
  };
  const features: Features = tableFeatures({ ...modules, columnMeta: {} });
  const textSort: SortFn<Features, Person> = (a, b, id) =>
    String(a.getValue(id)).localeCompare(String(b.getValue(id)));
  const numberSort: SortFn<Features, Person> = (a, b, id) =>
    Number(a.getValue(id)) - Number(b.getValue(id));
  function grid(
    kind: "local" | "server" | "mixed",
    initialSorting: SortingState = [],
  ) {
    const columns: ColumnDef<Features, Person>[] = [
      {
        accessorKey: "name",
        header: "Name",
        meta: kind === "server" ? {} : { sortFn: textSort },
      },
      {
        accessorKey: "status",
        header: "Status",
        meta: kind === "local" ? { sortFn: textSort } : {},
      },
      {
        accessorKey: "visits",
        header: "Visits",
        meta: kind === "server" ? {} : { sortFn: numberSort, align: "right" },
      },
    ];
    const table = createDataTable({
      features,
      data: people.slice(0, 7),
      columns,
      getRowId: (row) => row.id,
      enableMultiSort: true,
      isMultiSortEvent: () => true,
      initialState: { sorting: initialSorting },
    });
    return { table, columns };
  }
  const grids = [
    {
      ...grid("local", [
        { id: "status", desc: false },
        { id: "visits", desc: true },
      ]),
      title: "All local multi-sort",
    },
    { ...grid("server"), title: "All server" },
    { ...grid("mixed"), title: "Mixed per column" },
    {
      ...grid("server", [
        { id: "status", desc: false },
        { id: "visits", desc: true },
      ]),
      title: "Remote multi-sort: Status asc, Visits desc",
    },
  ];
  function remote(item: (typeof grids)[number]) {
    return item.table.store
      .get()
      .sorting.filter(
        (term) =>
          !item.columns.find(
            (column) =>
              ("accessorKey" in column ? column.accessorKey : column.id) ===
              term.id,
          )?.meta?.sortFn,
      );
  }
  function remoteText(item: (typeof grids)[number], revision: number) {
    void revision;
    const terms = remote(item);
    return `Remote request sorting: ${terms.length ? JSON.stringify(terms) : "none"}`;
  }
</script>

{#snippet header(item: Header<Features, Person>, revision: number)}
  {@const _revision = revision}
  <DataTableSortButton column={item.column}
    >{String(item.column.columnDef.header)}</DataTableSortButton
  >
{/snippet}

<DemoSection
  title="Column sorting"
  description="Multi-sort is supported for local columns as well: each click adds or changes a priority and the superscript shows that priority. Columns without meta.sortFn remain remote terms in the same sorting state, while their pass-through comparator leaves local row order unchanged."
>
  <div class="grid gap-3 xl:grid-cols-2">
    {#each grids as item (item.title)}<section class="space-y-1.5">
        <h3 class="text-sm font-medium text-foreground">{item.title}</h3>
        <DataTable table={item.table} {header} /><ReactiveTableText
          snapshot={item.table.dataTableSnapshot}
          text={(revision) => remoteText(item, revision)}
        />
      </section>{/each}
  </div>
</DemoSection>
