// packages/@fex-design/components/solid/src/primitive/card/card-footer.tsx
import { cardFooterClassName } from "@fex-design/components-styles/card"
import { cn } from "@fex-design/utils"
import type { JSX, ParentProps } from "solid-js"
import { splitProps } from "solid-js"

export type CardFooterProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

export function CardFooter(props: CardFooterProps) {
  const [local, rest] = splitProps(props, ["class", "children"])
  return (
    <div {...rest} data-slot="card-footer" class={cn(cardFooterClassName, local.class)}>
      {local.children}
    </div>
  )
}

// packages/@fex-design/svelte/src/primitive/card/card-footer.svelte
<script lang="ts">
  import { cardFooterClassName } from "@fex-design/styles/card";
  import { cn } from "@fex/utils";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  interface CardFooterProps extends Omit<
    HTMLAttributes<HTMLDivElement>,
    "class"
  > {
    class?: string;
    children?: Snippet;
  }

  let { class: className, children, ...rest }: CardFooterProps = $props();

  const classList = $derived(cn(cardFooterClassName, className));
</script>

<div {...rest} data-slot="card-footer" class={classList}>
  {@render children?.()}
</div>
