// apps/react-app/src/pages/Cascader/async-value-demo.tsx
import type { CascaderOption } from '@fex-design/core/cascader/types'
import useMount from '@fex-design/react/hooks/use-mount'
import { useState } from 'react'
import { regionOptions } from './data'
import { DemoCascader } from './demo-cascader'
import { DemoSection } from './demo-section'
export function AsyncValueDemo() {
  const [options, setOptions] = useState<readonly CascaderOption[]>([])
  const [loading, setLoading] = useState(true)
  useMount(() => {
    const timer = setTimeout(() => {
      setOptions(regionOptions)
      setLoading(false)
    }, 900)
    return () => clearTimeout(timer)
  })
  return (
    <DemoSection
      title="Asynchronous value display"
      description="The controlled path is retained while labels load, then resolves without emitting a user change."
    >
      <DemoCascader options={options} value={['zhejiang', 'hangzhou', 'xihu']} loading={loading} />
    </DemoSection>
  )
}

// apps/vue-app/src/pages/Cascader/async-value-demo.vue
<script setup lang="ts">
import type { CascaderOption } from '@fex-design/core/cascader/types'
import { onMounted, onUnmounted, ref } from 'vue'
import { regionOptions } from './data'
import DemoCascader from './demo-cascader.vue'
import Demo from './demo-section.vue'
const options = ref<readonly CascaderOption[]>([]),
  loading = ref(true)
let timer: ReturnType<typeof setTimeout>
onMounted(
  () =>
    (timer = setTimeout(() => {
      options.value = regionOptions
      loading.value = false
    }, 900)),
)
onUnmounted(() => clearTimeout(timer))
</script>
<template>
  <Demo
    title="Asynchronous value display"
    description="The path is retained while labels load, then resolves without a change event."
    ><DemoCascader :options="options" :value="['zhejiang', 'hangzhou', 'xihu']" :loading="loading"
  /></Demo>
</template>
