// apps/react-app/src/pages/AutoComplete/custom-demo.tsx
import {
  AutoCompleteContent,
  AutoCompleteList,
  AutoCompleteRoot,
  AutoCompleteTrigger,
} from '@fex-design/react/primitive/auto-complete'
import { Card } from '@fex-design/react/ui/card'
import { fieldNames, userSuggestions, type UserSuggestion } from './data'

export function CustomDemo() {
  return (
    <div className="grid gap-4 md:grid-cols-2">
      <Card
        title="Custom items and disabled suggestion"
        description="Original backend items drive richer rows; Alex is disabled."
      >
        <AutoCompleteRoot<UserSuggestion> items={userSuggestions} fieldNames={fieldNames}>
          <AutoCompleteTrigger placeholder="Custom suggestion rows" clearable status="warning" />
          <AutoCompleteContent>
            <div className="border-b border-border px-3 py-2 text-xs text-muted-foreground">
              People directory
            </div>
            <AutoCompleteList
              renderItem={(item, state) => {
                const user = item as UserSuggestion
                return (
                  <div className="min-w-0">
                    <div className="truncate font-medium">{user.name}</div>
                    <div className="truncate text-xs text-muted-foreground">
                      {user.department} · {user.email}
                      {state.disabled ? ' · unavailable' : ''}
                    </div>
                  </div>
                )
              }}
            />
          </AutoCompleteContent>
        </AutoCompleteRoot>
      </Card>
      <Card
        title="Validation and native props"
        description="Input validation styles and native form attributes are preserved."
      >
        <AutoCompleteRoot items={userSuggestions} fieldNames={fieldNames}>
          <AutoCompleteTrigger
            name="reviewer"
            required
            aria-describedby="reviewer-error"
            placeholder="Required reviewer"
            clearable
            invalid
            status="error"
          />
          <AutoCompleteContent />
        </AutoCompleteRoot>
        <p id="reviewer-error" className="mt-1.5 text-xs text-danger">
          Choose a reviewer or enter a new name.
        </p>
      </Card>
    </div>
  )
}

// apps/svelte-app/src/routes/auto-complete/custom-demo.svelte
<script lang="ts">
  import AutoCompleteRoot from "@fex-design/svelte/primitive/auto-complete";
  import AutoCompleteContent from "@fex-design/svelte/primitive/auto-complete-content";
  import AutoCompleteList from "@fex-design/svelte/primitive/auto-complete-list";
  import AutoCompleteTrigger from "@fex-design/svelte/primitive/auto-complete-trigger";
  import Card from "@fex-design/svelte/ui/card";
  import { fieldNames, users } from "./data";
</script>

<div class="grid gap-4 md:grid-cols-2">
  <Card
    title="Custom items and disabled suggestion"
    description="Original backend items drive richer rows; Alex is disabled."
  >
    <AutoCompleteRoot items={users} {fieldNames}>
      <AutoCompleteTrigger
        placeholder="Custom suggestion rows"
        clearable
        status="warning"
      />
      <AutoCompleteContent>
        <div
          class="border-b border-border px-3 py-2 text-xs text-muted-foreground"
        >
          People directory
        </div>
        <AutoCompleteList>
          {#snippet item(user, state)}
            <div>
              <div class="font-medium">{user.name}</div>
              <div class="text-xs text-muted-foreground">
                {user.department} · {user.email}{state.disabled
                  ? " · unavailable"
                  : ""}
              </div>
            </div>
          {/snippet}
        </AutoCompleteList>
      </AutoCompleteContent>
    </AutoCompleteRoot>
  </Card>
  <Card
    title="Validation and native props"
    description="Input validation styles and native form attributes are preserved."
  >
    <AutoCompleteRoot items={users} {fieldNames}>
      <AutoCompleteTrigger
        name="reviewer"
        required
        aria-describedby="reviewer-error-svelte"
        placeholder="Required reviewer"
        clearable
        invalid
        status="error"
      />
      <AutoCompleteContent />
    </AutoCompleteRoot>
    <p id="reviewer-error-svelte" class="mt-1.5 text-xs text-danger">
      Choose a reviewer or enter a new name.
    </p>
  </Card>
</div>
