// packages/@fex-design/components/react/src/primitive/slider/slider-mark.tsx
import {
  convertValueToPercentage,
  isSliderMarkActive,
  isSliderReversed,
} from '@fex-design/core/slider/utils'
import { sliderMarkClassName } from '@fex-design/components-styles/slider'
import { cn } from '@fex-design/utils'
import { type HTMLAttributes, type Ref } from 'react'
import { useSliderContext } from './slider-context'

function position(percent: number, vertical: boolean, reversed: boolean) {
  const value = reversed ? 100 - percent : percent
  return vertical ? { bottom: `${value}%` } : { left: `${value}%` }
}

export interface SliderMarkProps extends HTMLAttributes<HTMLSpanElement> {
  value: number
  ref?: Ref<HTMLSpanElement>
}

export function SliderMark({ value, ref, className, style, children, ...props }: SliderMarkProps) {
  const { snapshot } = useSliderContext('SliderMark')
  const percent = convertValueToPercentage(value, snapshot.min, snapshot.max)
  const reversed = isSliderReversed(snapshot.orientation, snapshot.direction, snapshot.reverse)
  const visualPercent = reversed ? 100 - percent : percent
  const active = isSliderMarkActive(snapshot.values, value)
  const placement = position(percent, snapshot.orientation === 'vertical', reversed)
  return (
    <span
      {...props}
      ref={ref}
      data-slot="slider-mark"
      data-active={active ? 'true' : 'false'}
      data-edge={visualPercent === 0 ? 'start' : visualPercent === 100 ? 'end' : undefined}
      data-orientation={snapshot.orientation}
      className={cn(sliderMarkClassName, className)}
      style={{ ...placement, ...style }}
    >
      <span>{children}</span>
    </span>
  )
}

// packages/@fex-design/components/solid/src/primitive/slider/slider-mark.tsx
import {
  convertValueToPercentage,
  isSliderMarkActive,
  isSliderReversed,
} from '@fex-design/core/slider/utils'
import { sliderMarkClassName } from '@fex-design/components-styles/slider'
import { cn } from '@fex-design/utils'
import { splitProps, type JSX } from 'solid-js'
import { useSliderContext } from './slider-context'

export interface SliderMarkProps extends JSX.HTMLAttributes<HTMLSpanElement> {
  value: number
}

export function SliderMark(props: SliderMarkProps) {
  const [local, rest] = splitProps(props, ['value', 'class', 'style', 'children'])
  const { snapshot } = useSliderContext('SliderMark')
  const visual = () => {
    const percent = convertValueToPercentage(local.value, snapshot().min, snapshot().max)
    return isSliderReversed(snapshot().orientation, snapshot().direction, snapshot().reverse)
      ? 100 - percent
      : percent
  }
  const placement = () =>
    snapshot().orientation === 'vertical' ? { bottom: `${visual()}%` } : { left: `${visual()}%` }
  return (
    <span
      {...rest}
      data-slot="slider-mark"
      data-active={isSliderMarkActive(snapshot().values, local.value) ? 'true' : 'false'}
      data-edge={visual() === 0 ? 'start' : visual() === 100 ? 'end' : undefined}
      data-orientation={snapshot().orientation}
      class={cn(sliderMarkClassName, local.class)}
      style={{ ...placement(), ...(typeof local.style === 'object' ? local.style : {}) }}
    >
      <span>{local.children}</span>
    </span>
  )
}
