// packages/@fex-design/components/solid/src/primitive/alert/alert-description.tsx
import { alertDescriptionClassName } from "@fex-design/components-styles/alert"
import { cn } from "@fex-design/utils"
import type { JSX, ParentProps } from "solid-js"
import { splitProps } from "solid-js"

export type AlertDescriptionProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

export function AlertDescription(props: AlertDescriptionProps) {
  const [local, rest] = splitProps(props, ["class", "children"])
  return (
    <div {...rest} data-slot="alert-description" class={cn(alertDescriptionClassName, local.class)}>
      {local.children}
    </div>
  )
}

// packages/@fex-design/components/react/src/primitive/alert/alert-description.tsx
import { alertDescriptionClassName } from "@fex-design/components-styles/alert"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type AlertDescriptionProps = ComponentProps<"div">

export function AlertDescription({ className, ...props }: AlertDescriptionProps) {
  return (
    <div
      data-slot="alert-description"
      className={cn(alertDescriptionClassName, className)}
      {...props}
    />
  )
}
