// packages/@fex-design/components/vue/src/ui/progress/progress-info.vue
<script setup lang="ts">
import { CheckIcon } from '@fex-design/vue/icons/check'
import type { ProgressStatus, ProgressVariant } from '@fex-design/core/progress/types'
import type { ProgressProps } from './types'

defineOptions({ name: 'ProgressInfo' })
const props = defineProps<{
  percentage: number | null
  value: number | null
  status: ProgressStatus
  variant: ProgressVariant
  format?: ProgressProps['format']
}>()
</script>

<template>
  <slot :percent="percentage === null ? null : Math.round(percentage * 100)" :value="value">
    <template v-if="format">{{ format(percentage === null ? null : Math.round(percentage * 100), value) }}</template>
    <CheckIcon v-else-if="status === 'success' && variant !== 'line'" class="size-6 text-success" />
    <span v-else-if="status === 'success' && percentage !== null && percentage >= 1"
      class="inline-flex size-4 items-center justify-center rounded-full bg-success text-[10px] text-white">
      <CheckIcon class="size-3" />
    </span>
    <template v-else>{{ percentage === null ? '' : `${Math.round(percentage * 100)}%` }}</template>
  </slot>
</template>

// packages/@fex-design/components/react/src/ui/progress/progress-info.tsx
import { CheckIcon } from '@fex-design/react/icons/check'
import type { normalizeProgressValue } from '@fex-design/core/progress/progress'
import type { ProgressProps } from './types'

interface ProgressInfoProps {
  normalized: ReturnType<typeof normalizeProgressValue>
  status: ProgressProps['status']
  variant: ProgressProps['variant']
  format: ProgressProps['format']
}

export function ProgressInfo({ normalized, status, variant, format }: ProgressInfoProps) {
  const isSuccess = status === 'success'
  if (format) {
    return format(
      normalized.percentage !== null ? Math.round(normalized.percentage * 100) : null,
      normalized.value,
    )
  }
  if (isSuccess && variant !== 'line') {
    return <CheckIcon className="size-6 text-success" />
  }
  if (isSuccess && normalized.percentage !== null && normalized.percentage >= 1) {
    return (
      <span className="inline-flex size-4 items-center justify-center rounded-full bg-success text-[10px] text-white">
        <CheckIcon className="size-3" />
      </span>
    )
  }
  return normalized.percentage !== null ? `${Math.round(normalized.percentage * 100)}%` : ''
}
