// packages/@fex-design/components/react/src/primitive/listbox/listbox-group.tsx
import type { ComponentProps } from 'react'
import { useListboxContext } from './listbox-context'

export function ListboxGroup({ className, ...props }: ComponentProps<'div'>) {
  const context = useListboxContext('ListboxGroup')
  return (
    <div
      {...props}
      role="group"
      data-slot="listbox-group"
      data-orientation={context.orientation}
      className={className}
    />
  )
}

// packages/@fex-design/components/solid/src/primitive/listbox/listbox-group.tsx
import { type JSX, type ParentProps } from 'solid-js'
import { useListboxContext } from './listbox-context'

export function ListboxGroup(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement>>) {
  const context = useListboxContext('ListboxGroup')
  return (
    <div {...props} role="group" data-slot="listbox-group" data-orientation={context.orientation} />
  )
}
