// packages/@fex-design/components/react/src/primitive/dialog/dialog-description.tsx
import { dialogDescriptionClassName } from "@fex-design/components-styles/dialog"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"
import { useDialog } from "./use-dialog"

export type DialogDescriptionProps = ComponentProps<"p">

export function DialogDescription({ className, ...props }: DialogDescriptionProps) {
  const { descriptionId } = useDialog("DialogDescription")
  return (
    <p
      {...props}
      id={descriptionId}
      data-slot="dialog-description"
      className={cn(dialogDescriptionClassName, className)}
    />
  )
}

// packages/@fex-design/components/solid/src/primitive/dialog/dialog-description.tsx
import { dialogDescriptionClassName } from "@fex-design/components-styles/dialog"
import { cn } from "@fex-design/utils"
import { splitProps, type ParentProps } from "solid-js"
import { useDialog } from "./dialog-context"

export type DialogDescriptionProps = ParentProps<{ class?: string }>

export function DialogDescription(props: DialogDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  const { descriptionId } = useDialog("DialogDescription")
  return (
    <p
      {...rest}
      id={descriptionId}
      data-slot="dialog-description"
      class={cn(dialogDescriptionClassName, local.class)}
    >
      {local.children}
    </p>
  )
}
