// packages/@fex-design/vue/src/primitive/input-number/input-number-increment.vue
<script setup lang="ts">
import { inputNumberIncrementClassName } from '@fex-design/styles/input-number'
import { cn } from '@fex/utils'
import { inject } from 'vue'
import { Button } from '../button/button'
import PlusIcon from '../../icon/plus-icon.vue'
import { inputNumberContextKey } from './context'
defineOptions({ name: 'InputNumberIncrement' })
const props = defineProps<{ class?: string; disabled?: boolean }>()
const inputNumber = inject(inputNumberContextKey)
if (!inputNumber) throw new Error('InputNumberIncrement must be used inside InputNumberRoot.')
</script>
<template>
  <Button
    variant="text"
    data-slot="input-number-increment"
    data-action="increment"
    aria-label="Increase value"
    :disabled="props.disabled || !inputNumber.canIncrement.value"
    :class="cn(inputNumberIncrementClassName, props.class)"
    @pointerdown.prevent
    @click="inputNumber.increment"
    ><slot><PlusIcon /></slot
  ></Button>
</template>

// packages/@fex-design/angular/src/primitive/input-number/input-number-increment.ts
import { ChangeDetectionStrategy, Component, HostListener, inject } from '@angular/core'
import { inputNumberIncrementClassName } from '@fex-design/styles/input-number'
import { buttonClassName } from '@fex-design/styles/button'
import { cn } from '@fex/utils'
import { PlusIcon } from '../../icon/plus'
import { createHostClassName } from '../../signals/host-class'
import { InputNumberRoot } from './input-number-root'
@Component({
  selector: 'button[inputNumberIncrement]',
  standalone: true,
  imports: [PlusIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    type: 'button',
    'data-slot': 'input-number-increment',
    'data-action': 'increment',
    'aria-label': 'Increase value',
    '[disabled]': '!root.inputNumber.canIncrement()',
  },
  template: '<ng-content><plus-icon /></ng-content>',
})
export class InputNumberIncrement {
  readonly root = inject(InputNumberRoot)
  protected readonly hostClassName = createHostClassName(() =>
    cn(buttonClassName({ variant: 'text' }), inputNumberIncrementClassName),
  )
  @HostListener('pointerdown', ['$event']) pointerdown(event: PointerEvent) {
    event.preventDefault()
  }
  @HostListener('click', ['$event']) click(event: MouseEvent) {
    if (!event.defaultPrevented) this.root.inputNumber.increment(event)
  }
}
