// apps/react-app/src/pages/Steps/disabled-demo.tsx
import { useState } from 'react'
import { Steps, type StepValue } from '@fex-design/react/primitive/steps'
import { Card } from '@fex-design/react/ui/card'
import { StepList } from './step-list'
export function DisabledDemo() {
  const [value, setValue] = useState<StepValue>('account')
  return (
    <Card
      title="Disabled"
      description="Disabled nodes cannot be selected and are skipped by keyboard navigation."
    >
      <Steps navigation current={value} onChange={setValue}>
        <StepList disabled />
      </Steps>
      <p className="mt-2 text-sm text-muted-foreground">Current value: {String(value)}</p>
    </Card>
  )
}

// apps/solid-app/src/pages/Steps/disabled-demo.tsx
import { createSignal } from 'solid-js'
import { Steps, type StepValue } from '@fex-design/solid/primitive/steps'
import { Card } from '@fex-design/solid/ui/card'
import { StepList } from './step-list'
export function DisabledDemo() {
  const [value, setValue] = createSignal<StepValue>('account')
  return (
    <Card
      title="Disabled"
      description="Disabled nodes cannot be selected and are skipped by keyboard navigation."
    >
      <Steps navigation current={value()} onChange={setValue}>
        <StepList disabled />
      </Steps>
      <p class="mt-2 text-sm text-muted-foreground">Current value: {String(value())}</p>
    </Card>
  )
}
