// apps/vue-app/src/pages/Dropdown/custom-panel-demo.vue
<script setup lang="ts">
import { DropdownContent, DropdownRoot, DropdownTrigger } from '@fex-design/vue/primitive/dropdown'
import { PopoverPortal } from '@fex-design/vue/primitive/popover'
import Checkbox from '@fex-design/vue/ui/checkbox'
import { triggerClassName } from './demo-classes'
</script>

<template>
  <DropdownRoot
    ><DropdownTrigger v-slot="slot"
      ><button v-bind="slot.props" :ref="slot.ref" :class="triggerClassName">
        Filters
      </button></DropdownTrigger
    ><PopoverPortal
      ><DropdownContent role="dialog" class="p-3"
        ><div class="w-64 space-y-3">
          <h3 class="text-sm font-medium">Quick filters</h3>
          <p class="text-xs text-muted-foreground">Content can host an additional custom panel.</p>
          <div class="flex items-center gap-2 text-sm">
            <Checkbox id="vue-filter-active" default-checked /><label for="vue-filter-active"
              >Only active records</label
            >
          </div>
          <div class="flex items-center gap-2 text-sm">
            <Checkbox id="vue-filter-assigned" default-checked /><label for="vue-filter-assigned"
              >Assigned to me</label
            >
          </div>
        </div></DropdownContent
      ></PopoverPortal
    ></DropdownRoot
  >
</template>

// apps/angular-app/src/pages/dropdown/custom-panel-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  DropdownContent,
  DropdownRoot,
  DropdownTrigger,
} from '@fex-design/angular/primitive/dropdown'
import { PopoverPortal } from '@fex-design/angular/primitive/popover'
import { Checkbox } from '@fex-design/angular/ui/checkbox'
import { triggerClassName } from './demo-classes'

@Component({
  selector: 'app-dropdown-custom-panel-demo',
  standalone: true,
  imports: [DropdownRoot, DropdownTrigger, DropdownContent, PopoverPortal, Checkbox],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './custom-panel-demo.component.html',
})
export class DropdownCustomPanelDemoComponent {
  protected readonly triggerClassName = triggerClassName
}

<fex-dropdown
  ><button fexDropdownTrigger [class]="triggerClassName">Filters</button
  ><fex-popover-portal
    ><fex-dropdown-content role="dialog" class="p-3"
      ><div class="w-64 space-y-3">
        <h3 class="text-sm font-medium">Quick filters</h3>
        <p class="text-xs text-muted-foreground">Content can host an additional custom panel.</p>
        <div class="flex items-center gap-2 text-sm">
          <button id="angular-filter-active" fexCheckbox [defaultChecked]="true"></button
          ><label for="angular-filter-active">Only active records</label>
        </div>
        <div class="flex items-center gap-2 text-sm">
          <button id="angular-filter-assigned" fexCheckbox [defaultChecked]="true"></button
          ><label for="angular-filter-assigned">Assigned to me</label>
        </div>
      </div></fex-dropdown-content
    ></fex-popover-portal
  ></fex-dropdown
>
