// apps/svelte-app/src/routes/rate/integer-demo.svelte
<script lang="ts">
  import Rate from '@fex-design/svelte/primitive/rate'
  import Card from '@fex-design/svelte/ui/card'
  let value = $state(3)
</script>
<Card title="Default integer" description="The default step is 1, so pointer and keyboard input select whole values."><div class="grid gap-1.5"><Rate {value} onValueChange={(next) => value = next} aria-label="Integer rating" /><p class="text-sm text-muted-foreground">Current value: {value}</p></div></Card>

// apps/react-app/src/pages/Rate/integer-demo.tsx
import { Rate } from '@fex-design/react/primitive/rate'
import { Card } from '@fex-design/react/ui/card'
import { useState } from 'react'

export function IntegerDemo() {
  const [value, setValue] = useState(3)

  return (
    <Card
      title="Default integer"
      description="The default step is 1, so pointer and keyboard input select whole values."
    >
      <div className="grid gap-1.5">
        <Rate value={value} onValueChange={setValue} aria-label="Integer rating" />
        <p className="text-sm text-muted-foreground">Current value: {value}</p>
      </div>
    </Card>
  )
}
