// packages/@fex-design/components/react/src/primitive/qrcode/qrcode-context.ts
import type { QrCodeModel } from '@fex-design/core/qrcode'
import { createContext, use } from 'react'

export interface QrCodeContextValue {
  model: QrCodeModel
}

export const QrCodeContext = createContext<QrCodeContextValue | null>(null)

export function useQrCode(component = 'useQrCode') {
  const context = use(QrCodeContext)
  if (!context) {
    throw new Error(component + ' must be used inside QrCodeRoot.')
  }
  return context
}

// packages/@fex-design/components/solid/src/primitive/qrcode/qrcode-context.ts
import type { QrCodeModel } from '@fex-design/core/qrcode'
import { createContext, useContext, type Accessor } from 'solid-js'

export interface QrCodeContextValue {
  model: Accessor<QrCodeModel>
}

export const QrCodeContext = createContext<QrCodeContextValue>()

export function useQrCode(component = 'useQrCode') {
  const context = useContext(QrCodeContext)
  if (!context) {
    throw new Error(component + ' must be used inside QrCodeRoot.')
  }
  return context
}
