// packages/@fex-design/vue/src/primitive/data-table/data-table.vue
﻿<script setup lang="ts" generic="TFeatures extends TableFeatures, TData extends RowData">
import type { DataTableColumnMeta } from '@fex-design/core/data-table/types'
import {
  getDataTableColumnLayout,
  getDataTableHeaderLayout,
  getDataTableRenderedCells,
  getDataTableRenderedRows,
  getDataTableRowLayout,
  getDataTableSizingLayout,
  getDataTableVirtualRows,
  getDataTableVisibleLeafColumnCount,
  getDataTableVisibleLeafColumns,
  type DataTableColumnLayoutSource,
  type DataTablePinningTableSource,
  type DataTableRenderingTableSource,
  type DataTableRowRenderingSource,
} from '@fex-design/core/data-table/layout'
import {
  dataTableAlignClassName,
  dataTableBodyClassName,
  dataTableCellClassName,
  dataTableCellContentClassName,
  dataTableEmptyClassName,
  dataTableGroupedRowClassName,
  dataTableHeaderCellClassName,
  dataTableHeaderClassName,
  dataTableHeaderContentClassName,
  dataTableHeaderRowClassName,
  dataTableHeaderSeparatorClassName,
  dataTableLoadingClassName,
  dataTablePinnedBottomEdgeClassName,
  dataTablePinnedBottomRowClassName,
  dataTablePinnedCellClassName,
  dataTablePinnedEndClassName,
  dataTablePinnedEndEdgeClassName,
  dataTablePinnedHeaderCellClassName,
  dataTablePinnedRowClassName,
  dataTablePinnedStartClassName,
  dataTablePinnedStartEdgeClassName,
  dataTablePinnedTopEdgeClassName,
  dataTablePinnedTopRowClassName,
  dataTableResizeHandleClassName,
  dataTableRootClassName,
  dataTableRowClassName,
  dataTableClassName,
  dataTableViewportClassName,
  dataTableVirtualSpacerClassName,
} from '@fex-design/styles/data-table'
import { cn } from '@fex/utils'
import type { Cell, Header, Row, RowData, TableFeatures } from '@tanstack/table-core'
import { useVirtualizer } from '@tanstack/vue-virtual'
import { computed, provide, shallowRef, useAttrs } from 'vue'
import type { VueDataTable } from '../../composables/use-data-table'
import { DataTableTemplate } from './data-table-template'
import { dataTableRevisionKey } from './data-table-context'

defineOptions({ inheritAttrs: false })
interface DataTableClass {
  root?: string
  viewport?: string
  table?: string
  header?: string
  headerRow?: string
  headerCell?: string
  body?: string
  row?: string
  cell?: string
  empty?: string
  loading?: string
}
type NativePartProps = Record<string, unknown>
const props = withDefaults(
  defineProps<{
    table: VueDataTable<TFeatures, TData>
    partClass?: DataTableClass
    density?: 'compact' | 'default' | 'comfortable'
    striped?: boolean
    border?: boolean
    loading?: boolean
    loadingContent?: string
    emptyContent?: string
    virtual?: { height: number; estimateRowHeight?: number; overscan?: number }
    getHeaderProps?: (header: Header<TFeatures, TData>) => NativePartProps
    getCellProps?: (cell: Cell<TFeatures, TData>) => NativePartProps
    getRowProps?: (row: Row<TFeatures, TData>) => NativePartProps
  }>(),
  {
    density: 'default',
    striped: false,
    border: false,
    loading: false,
    loadingContent: 'Loading…',
    emptyContent: 'No data',
  },
)
const attrs = useAttrs()
type RenderColumn = ReturnType<VueDataTable<TFeatures, TData>['getAllLeafColumns']>[number] &
  DataTableColumnLayoutSource
type RenderCell = Cell<TFeatures, TData> & { column: RenderColumn }
type RenderRow = Row<TFeatures, TData> & DataTableRowRenderingSource<RenderCell>
type RenderTable = VueDataTable<TFeatures, TData> &
  DataTableRenderingTableSource<RenderRow, RenderColumn>
const renderTable = props.table as unknown as RenderTable
const pinningTable = props.table as unknown as DataTablePinningTableSource
const snapshot = computed(() => props.table.dataTableSnapshot.value)
const revision = computed(() => snapshot.value.revision)
provide(dataTableRevisionKey, revision)
const renderedRows = computed(() => {
  void revision.value
  return [...getDataTableRenderedRows(renderTable)]
})
const virtualRows = computed(() => {
  void revision.value
  return [...getDataTableVirtualRows(renderTable)]
})
const viewportElement = shallowRef<HTMLDivElement | null>(null)
const virtualizer = useVirtualizer(
  computed(() => ({
    count: props.virtual ? virtualRows.value.length : 0,
    getScrollElement: () => viewportElement.value,
    estimateSize: () => props.virtual?.estimateRowHeight ?? 40,
    overscan: props.virtual?.overscan ?? 8,
  })),
)
const rows = computed(() =>
  props.virtual
    ? virtualizer.value
        .getVirtualItems()
        .map((item) => virtualRows.value[item.index])
        .filter((row): row is RenderRow => row !== undefined)
    : renderedRows.value,
)
const virtualTop = computed(() => virtualizer.value.getVirtualItems()[0]?.start ?? 0)
const virtualBottom = computed(() => {
  const last = virtualizer.value.getVirtualItems().at(-1)
  return last ? Math.max(0, virtualizer.value.getTotalSize() - last.end) : 0
})
const columns = computed(() => {
  void revision.value
  return [...getDataTableVisibleLeafColumns(renderTable)]
})
const headerGroups = computed(() => {
  void revision.value
  return [...props.table.getHeaderGroups()]
})
const sizingLayout = computed(() => {
  void snapshot.value
  return getDataTableSizingLayout(props.table)
})
const tableWidth = computed(() => sizingLayout.value.tableWidth)
const rootStyle = computed(() => ({
  '--data-table-header-height': 'var(--data-table-row-height)',
  width: sizingLayout.value.rootWidth,
  ...(typeof attrs.style === 'object' && attrs.style !== null ? attrs.style : {}),
}))
const layoutStyle = (style: ReturnType<typeof getDataTableColumnLayout>['style']) => ({
  position: style.position,
  width: style.width === undefined ? undefined : `${style.width}px`,
  insetInlineStart:
    style.insetInlineStart === undefined ? undefined : `${style.insetInlineStart}px`,
  insetInlineEnd: style.insetInlineEnd === undefined ? undefined : `${style.insetInlineEnd}px`,
  top: style.top,
  bottom: style.bottom,
  zIndex: style.zIndex,
  backgroundColor: style.backgroundColor ? `var(--${style.backgroundColor})` : undefined,
  boxShadow: style.boxShadow,
})
const metaOf = (column: { columnDef: { meta?: unknown } }) =>
  column.columnDef.meta as DataTableColumnMeta | undefined
const rowSource = (row: RenderRow) => row
const isGrouped = (row: RenderRow) =>
  'getIsGrouped' in row && typeof row.getIsGrouped === 'function' && row.getIsGrouped()
const isExpanded = (row: RenderRow) =>
  'getIsExpanded' in row && typeof row.getIsExpanded === 'function' && row.getIsExpanded()
type ResizableHeader = Header<TFeatures, TData> & {
  column: Header<TFeatures, TData>['column'] & {
    getCanResize?: () => boolean
    getIsResizing?: () => boolean
    resetSize?: () => void
  }
  getResizeHandler?: () => (event: MouseEvent | TouchEvent) => void
}
const resizable = (header: Header<TFeatures, TData>) => header as ResizableHeader
const headerProps = (header: Header<TFeatures, TData>) => props.getHeaderProps?.(header) ?? {}
const cellProps = (cell: Cell<TFeatures, TData>) => props.getCellProps?.(cell) ?? {}
const rowProps = (row: Row<TFeatures, TData>) => props.getRowProps?.(row) ?? {}
const objectStyle = (style: unknown) => (typeof style === 'object' && style !== null ? style : {})
const nativePartClass = (value: unknown) => (typeof value === 'string' ? value : undefined)
</script>

<template>
  <div
    v-bind="attrs"
    data-slot="data-table"
    :data-loading="props.loading || undefined"
    :class="
      cn(
        dataTableRootClassName({
          density: props.density,
          striped: props.striped,
          bordered: props.border,
        }),
        props.partClass?.root,
      )
    "
    :style="rootStyle"
  >
    <div
      ref="viewportElement"
      data-slot="data-table-viewport"
      :class="cn(dataTableViewportClassName, props.partClass?.viewport)"
      :style="props.virtual ? { height: `${props.virtual.height}px` } : undefined"
    >
      <table
        :class="cn(dataTableClassName, props.partClass?.table)"
        :style="{ width: tableWidth === undefined ? '100%' : `${tableWidth}px` }"
      >
        <colgroup v-if="tableWidth !== undefined">
          <col
            v-for="column in columns"
            :key="column.id"
            :style="{
              width: column.getSize?.() === undefined ? undefined : `${column.getSize?.()}px`,
            }"
          />
        </colgroup>
        <thead :class="cn(dataTableHeaderClassName, props.partClass?.header)">
          <tr
            v-for="headerGroup in headerGroups"
            :key="headerGroup.id"
            :class="
              cn(
                dataTableHeaderRowClassName({ bordered: props.border }),
                props.partClass?.headerRow,
              )
            "
          >
            <th
              v-for="(header, index) in headerGroup.headers"
              v-bind="headerProps(header)"
              :key="header.id"
              :colspan="header.colSpan"
              :class="
                cn(
                  dataTableHeaderCellClassName,
                  getDataTableHeaderLayout(header, pinningTable).pinned &&
                    dataTablePinnedCellClassName,
                  getDataTableHeaderLayout(header, pinningTable).pinned &&
                    dataTablePinnedHeaderCellClassName,
                  getDataTableHeaderLayout(header, pinningTable).pinned === 'start' &&
                    dataTablePinnedStartClassName,
                  getDataTableHeaderLayout(header, pinningTable).pinned === 'end' &&
                    dataTablePinnedEndClassName,
                  getDataTableHeaderLayout(header, pinningTable).isStartEdge &&
                    dataTablePinnedStartEdgeClassName,
                  getDataTableHeaderLayout(header, pinningTable).isEndEdge &&
                    dataTablePinnedEndEdgeClassName,
                  !props.border &&
                    headerGroup.headers.slice(index + 1).some((item) => !item.isPlaceholder) &&
                    dataTableHeaderSeparatorClassName,
                  metaOf(header.column)?.align &&
                    dataTableAlignClassName[metaOf(header.column)!.align!],
                  metaOf(header.column)?.headerClassName,
                  props.partClass?.headerCell,
                  nativePartClass(headerProps(header).class),
                )
              "
              :style="{
                ...layoutStyle(getDataTableHeaderLayout(header, pinningTable).style),
                ...objectStyle(headerProps(header).style),
              }"
            >
              <div
                v-if="!header.isPlaceholder"
                data-slot="data-table-header-content"
                :class="dataTableHeaderContentClassName"
              >
                <DataTableTemplate
                  :template="header.column.columnDef.header"
                  :context="header.getContext()"
                  :revision="revision"
                />
              </div>
              <span
                v-if="header.colSpan === 1 && resizable(header).column.getCanResize?.()"
                role="separator"
                tabindex="0"
                :aria-label="`Resize ${header.column.id}`"
                :data-resizing="resizable(header).column.getIsResizing?.() || undefined"
                :class="dataTableResizeHandleClassName"
                @dblclick="resizable(header).column.resetSize?.()"
                @mousedown="resizable(header).getResizeHandler?.()($event)"
                @touchstart="resizable(header).getResizeHandler?.()($event)"
              />
            </th>
          </tr>
        </thead>
        <tbody :class="cn(dataTableBodyClassName, props.partClass?.body)">
          <tr v-if="props.virtual && virtualTop > 0" aria-hidden="true">
            <td
              :colspan="Math.max(1, getDataTableVisibleLeafColumnCount(renderTable))"
              :class="dataTableVirtualSpacerClassName"
              :style="{ height: `${virtualTop}px` }"
            />
          </tr>
          <template v-if="rows.length">
            <template v-for="row in rows" :key="row.id">
              <tr
                v-bind="rowProps(row)"
                :data-pinned="row.getIsPinned?.() || undefined"
                :data-grouped="isGrouped(rowSource(row)) || undefined"
                :class="
                  cn(
                    dataTableRowClassName,
                    row.getIsPinned?.() && dataTablePinnedRowClassName,
                    row.getIsPinned?.() === 'top' && dataTablePinnedTopRowClassName,
                    row.getIsPinned?.() === 'bottom' && dataTablePinnedBottomRowClassName,
                    getDataTableRowLayout(row, pinningTable).edge === 'top' &&
                      dataTablePinnedTopEdgeClassName,
                    getDataTableRowLayout(row, pinningTable).edge === 'bottom' &&
                      dataTablePinnedBottomEdgeClassName,
                    isGrouped(rowSource(row)) && dataTableGroupedRowClassName,
                    props.partClass?.row,
                    nativePartClass(rowProps(row).class),
                  )
                "
                :style="{
                  ...layoutStyle(getDataTableRowLayout(row, pinningTable).style),
                  ...objectStyle(rowProps(row).style),
                }"
              >
                <td
                  v-if="isGrouped(rowSource(row)) && $slots.groupRow"
                  :colspan="Math.max(1, getDataTableVisibleLeafColumnCount(renderTable))"
                  :class="cn(dataTableCellClassName, props.partClass?.cell)"
                >
                  <slot name="groupRow" :row="row" />
                </td>
                <td
                  v-for="cell in isGrouped(rowSource(row)) && $slots.groupRow
                    ? []
                    : getDataTableRenderedCells(rowSource(row))"
                  v-bind="cellProps(cell)"
                  :key="cell.id"
                  :class="
                    cn(
                      dataTableCellClassName,
                      getDataTableColumnLayout(cell.column, pinningTable).pinned &&
                        dataTablePinnedCellClassName,
                      getDataTableColumnLayout(cell.column, pinningTable).pinned === 'start' &&
                        dataTablePinnedStartClassName,
                      getDataTableColumnLayout(cell.column, pinningTable).pinned === 'end' &&
                        dataTablePinnedEndClassName,
                      getDataTableColumnLayout(cell.column, pinningTable).isStartEdge &&
                        dataTablePinnedStartEdgeClassName,
                      getDataTableColumnLayout(cell.column, pinningTable).isEndEdge &&
                        dataTablePinnedEndEdgeClassName,
                      metaOf(cell.column)?.align &&
                        dataTableAlignClassName[metaOf(cell.column)!.align!],
                      metaOf(cell.column)?.cellClassName,
                      props.partClass?.cell,
                      nativePartClass(cellProps(cell).class),
                    )
                  "
                  :style="{
                    ...layoutStyle(getDataTableColumnLayout(cell.column, pinningTable).style),
                    ...objectStyle(cellProps(cell).style),
                  }"
                >
                  <div :class="dataTableCellContentClassName">
                    <DataTableTemplate
                      :template="cell.column.columnDef.cell"
                      :context="cell.getContext()"
                      :revision="revision"
                    />
                  </div>
                </td>
              </tr>
              <tr
                v-if="isExpanded(rowSource(row)) && $slots.subComponent"
                :class="dataTableRowClassName"
              >
                <td :colspan="getDataTableVisibleLeafColumnCount(renderTable)">
                  <slot name="subComponent" :row="row" />
                </td>
              </tr>
            </template>
          </template>
          <tr v-else>
            <td
              :colspan="Math.max(1, getDataTableVisibleLeafColumnCount(renderTable))"
              :class="cn(dataTableEmptyClassName, props.partClass?.empty)"
            >
              {{ props.emptyContent }}
            </td>
          </tr>
          <tr v-if="props.virtual && virtualBottom > 0" aria-hidden="true">
            <td
              :colspan="Math.max(1, getDataTableVisibleLeafColumnCount(renderTable))"
              :class="dataTableVirtualSpacerClassName"
              :style="{ height: `${virtualBottom}px` }"
            />
          </tr>
        </tbody>
      </table>
    </div>
    <div v-if="props.loading" :class="cn(dataTableLoadingClassName, props.partClass?.loading)">
      {{ props.loadingContent }}
    </div>
  </div>
</template>

// packages/@fex-design/svelte/src/primitive/data-table/data-table.svelte
<script
  lang="ts"
  generics="TFeatures extends TableFeatures, TData extends RowData"
>
  import type { DataTableColumnMeta } from "@fex-design/core/data-table/types";
  import {
    getDataTableColumnLayout,
    getDataTableHeaderLayout,
    getDataTableRenderedCells,
    getDataTableRenderedRows,
    getDataTableRowLayout,
    getDataTableSizingLayout,
    getDataTableVirtualRows,
    getDataTableVisibleLeafColumnCount,
    getDataTableVisibleLeafColumns,
    type DataTableColumnLayoutSource,
    type DataTablePinningTableSource,
    type DataTableRenderingTableSource,
    type DataTableRowRenderingSource,
  } from "@fex-design/core/data-table/layout";
  import {
    dataTableAlignClassName,
    dataTableBodyClassName,
    dataTableCellClassName,
    dataTableCellContentClassName,
    dataTableEmptyClassName,
    dataTableGroupedRowClassName,
    dataTableHeaderCellClassName,
    dataTableHeaderClassName,
    dataTableHeaderContentClassName,
    dataTableHeaderRowClassName,
    dataTableHeaderSeparatorClassName,
    dataTableLoadingClassName,
    dataTablePinnedBottomEdgeClassName,
    dataTablePinnedBottomRowClassName,
    dataTablePinnedCellClassName,
    dataTablePinnedEndClassName,
    dataTablePinnedEndEdgeClassName,
    dataTablePinnedHeaderCellClassName,
    dataTablePinnedRowClassName,
    dataTablePinnedStartClassName,
    dataTablePinnedStartEdgeClassName,
    dataTablePinnedTopEdgeClassName,
    dataTablePinnedTopRowClassName,
    dataTableResizeHandleClassName,
    dataTableRootClassName,
    dataTableRowClassName,
    dataTableClassName,
    dataTableViewportClassName,
    dataTableVirtualSpacerClassName,
  } from "@fex-design/styles/data-table";
  import { cn } from "@fex/utils";
  import type {
    Cell,
    Header,
    Row,
    RowData,
    TableFeatures,
  } from "@tanstack/table-core";
  import { createVirtualizer } from "@tanstack/svelte-virtual";
  import { untrack, type Snippet } from "svelte";
  import type {
    HTMLAttributes,
    HTMLTdAttributes,
    HTMLThAttributes,
  } from "svelte/elements";

  import type { SvelteDataTable } from "../../stores/create-data-table";

  interface DataTableClass {
    root?: string;
    viewport?: string;
    table?: string;
    header?: string;
    headerRow?: string;
    headerCell?: string;
    body?: string;
    row?: string;
    cell?: string;
    empty?: string;
    loading?: string;
  }

  interface Props extends Omit<
    HTMLAttributes<HTMLDivElement>,
    "class" | "children"
  > {
    table: SvelteDataTable<TFeatures, TData>;
    class?: DataTableClass;
    density?: "compact" | "default" | "comfortable";
    striped?: boolean;
    border?: boolean;
    loading?: boolean;
    loadingContent?: string;
    emptyContent?: string;
    virtual?: { height: number; estimateRowHeight?: number; overscan?: number };
    header?: Snippet<[Header<TFeatures, TData>, number]>;
    cell?: Snippet<[Cell<TFeatures, TData>, number]>;
    groupRow?: Snippet<[Row<TFeatures, TData>, number]>;
    subComponent?: Snippet<[Row<TFeatures, TData>, number]>;
    getHeaderProps?: (header: Header<TFeatures, TData>) => HTMLThAttributes;
    getCellProps?: (cell: Cell<TFeatures, TData>) => HTMLTdAttributes;
    getRowProps?: (
      row: Row<TFeatures, TData>,
    ) => HTMLAttributes<HTMLTableRowElement>;
    headerAction?: PartAction<Header<TFeatures, TData>>;
    cellAction?: PartAction<Cell<TFeatures, TData>>;
    rowAction?: PartAction<Row<TFeatures, TData>>;
  }

  type PartAction<TItem> = (
    node: HTMLElement,
    item: TItem,
  ) => { update?: (item: TItem) => void; destroy?: () => void } | void;

  let {
    table,
    class: classes,
    density = "default",
    striped = false,
    border = false,
    loading = false,
    loadingContent = "Loading…",
    emptyContent = "No data",
    virtual,
    header,
    cell,
    groupRow,
    subComponent,
    getHeaderProps,
    getCellProps,
    getRowProps,
    headerAction,
    cellAction,
    rowAction,
    style,
    ...rest
  }: Props = $props();

  type RenderColumn = ReturnType<typeof table.getAllLeafColumns>[number] &
    DataTableColumnLayoutSource;
  type RenderCell = Cell<TFeatures, TData> & { column: RenderColumn };
  type RenderRow = Row<TFeatures, TData> &
    DataTableRowRenderingSource<RenderCell>;
  type RenderTable = SvelteDataTable<TFeatures, TData> &
    DataTableRenderingTableSource<RenderRow, RenderColumn>;

  // svelte-ignore state_referenced_locally -- a DataTable table/controller is intentionally stable.
  const renderTable = table as unknown as RenderTable;
  // svelte-ignore state_referenced_locally -- pinning layout reads the same stable controller.
  const pinningTable = table as unknown as DataTablePinningTableSource;
  // svelte-ignore state_referenced_locally -- subscriptions belong to the stable controller.
  const snapshot = table.dataTableSnapshot;
  let viewportElement = $state<HTMLDivElement | null>(null);
  const virtualizer = createVirtualizer<HTMLDivElement, HTMLTableRowElement>({
    count: 0,
    getScrollElement: () => viewportElement,
    estimateSize: () => virtual?.estimateRowHeight ?? 40,
    overscan: 8,
  });

  const renderedRows = $derived.by(() => {
    void $snapshot;
    return [...getDataTableRenderedRows(renderTable)];
  });
  const virtualRows = $derived.by(() => {
    void $snapshot;
    return [...getDataTableVirtualRows(renderTable)];
  });
  $effect(() => {
    // The virtualizer store is both the command target and a notification
    // source. Reading it reactively here would make setOptions retrigger this
    // same effect until Svelte reaches its update-depth guard.
    untrack(() => $virtualizer).setOptions({
      count: virtual ? virtualRows.length : 0,
      getScrollElement: () => viewportElement,
      estimateSize: () => virtual?.estimateRowHeight ?? 40,
      overscan: virtual?.overscan ?? 8,
    });
  });
  const rows = $derived(
    virtual
      ? $virtualizer
          .getVirtualItems()
          .map((item) => virtualRows[item.index])
          .filter((row): row is RenderRow => row !== undefined)
      : renderedRows,
  );
  const virtualTop = $derived($virtualizer.getVirtualItems()[0]?.start ?? 0);
  const virtualBottom = $derived.by(() => {
    const last = $virtualizer.getVirtualItems().at(-1);
    return last ? Math.max(0, $virtualizer.getTotalSize() - last.end) : 0;
  });
  const columns = $derived.by(() => {
    void $snapshot;
    return [...getDataTableVisibleLeafColumns(renderTable)];
  });
  const headerGroups = $derived.by(() => {
    void $snapshot;
    return [...table.getHeaderGroups()];
  });
  const sizingLayout = $derived.by(() => {
    void $snapshot;
    return getDataTableSizingLayout(table);
  });
  const tableWidth = $derived(sizingLayout.tableWidth);

  function renderTemplate(
    template: unknown,
    context: unknown,
    revision: number,
  ) {
    void revision;
    return typeof template === "function" ? template(context) : template;
  }
  function text(value: unknown) {
    return value === undefined || value === null ? "" : String(value);
  }
  function metaOf(column: { columnDef: { meta?: unknown } }) {
    return column.columnDef.meta as DataTableColumnMeta | undefined;
  }
  function layoutStyle(
    layout: ReturnType<typeof getDataTableColumnLayout>["style"],
  ) {
    return {
      position: layout.position,
      width: layout.width === undefined ? undefined : `${layout.width}px`,
      insetInlineStart:
        layout.insetInlineStart === undefined
          ? undefined
          : `${layout.insetInlineStart}px`,
      insetInlineEnd:
        layout.insetInlineEnd === undefined
          ? undefined
          : `${layout.insetInlineEnd}px`,
      top: layout.top,
      bottom: layout.bottom,
      zIndex: layout.zIndex,
      backgroundColor: layout.backgroundColor
        ? `var(--${layout.backgroundColor})`
        : undefined,
      boxShadow: layout.boxShadow,
    };
  }
  function styleToString(value: Record<string, string | number | undefined>) {
    return Object.entries(value)
      .filter(
        (entry): entry is [string, string | number] => entry[1] !== undefined,
      )
      .map(
        ([key, item]) =>
          `${key.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`)}:${item}`,
      )
      .join(";");
  }
  function mergedStyle(
    layout: ReturnType<typeof getDataTableColumnLayout>["style"],
    nativeStyle: string | null | undefined,
  ) {
    const layoutValue = styleToString(layoutStyle(layout));
    return nativeStyle ? `${layoutValue};${nativeStyle}` : layoutValue;
  }
  function isGrouped(row: RenderRow) {
    return (
      "getIsGrouped" in row &&
      typeof row.getIsGrouped === "function" &&
      row.getIsGrouped()
    );
  }
  function isExpanded(row: RenderRow) {
    return (
      "getIsExpanded" in row &&
      typeof row.getIsExpanded === "function" &&
      row.getIsExpanded()
    );
  }
  function headerLayoutOf(item: Header<TFeatures, TData>, revision: number) {
    void revision;
    return getDataTableHeaderLayout(item, pinningTable);
  }
  function rowLayoutOf(row: RenderRow, revision: number) {
    void revision;
    return getDataTableRowLayout(row, pinningTable);
  }
  function cellsOf(row: RenderRow, revision: number) {
    void revision;
    return [...getDataTableRenderedCells(row)];
  }
  function columnSizeOf(column: RenderColumn, revision: number) {
    void revision;
    return column.getSize?.();
  }
  function cellLayoutOf(item: Cell<TFeatures, TData>, revision: number) {
    void revision;
    return getDataTableColumnLayout(item.column, pinningTable);
  }
  function rowPinned(row: RenderRow, revision: number) {
    void revision;
    return row.getIsPinned?.() ?? false;
  }
  function headerPropsOf(item: Header<TFeatures, TData>, revision: number) {
    void revision;
    return getHeaderProps?.(item) ?? {};
  }
  function cellPropsOf(item: Cell<TFeatures, TData>, revision: number) {
    void revision;
    return getCellProps?.(item) ?? {};
  }
  function rowPropsOf(row: Row<TFeatures, TData>, revision: number) {
    void revision;
    return getRowProps?.(row) ?? {};
  }
  type ResizableHeader = Header<TFeatures, TData> & {
    column: Header<TFeatures, TData>["column"] & {
      getCanResize?: () => boolean;
      getIsResizing?: () => boolean;
      resetSize?: () => void;
    };
    getResizeHandler?: () => (event: MouseEvent | TouchEvent) => void;
  };
  const resizable = (value: Header<TFeatures, TData>) =>
    value as ResizableHeader;
  const resizeHandle = (
    node: HTMLElement,
    initialHeader: Header<TFeatures, TData>,
  ) => {
    let currentHeader = initialHeader;
    let cleanupPointerSession: (() => void) | undefined;
    const onPointerDown = (event: PointerEvent) => {
      if (event.button !== 0) return;
      event.preventDefault();
      const ownerDocument = node.ownerDocument;
      const onPointerMove = (moveEvent: PointerEvent) => {
        ownerDocument.dispatchEvent(
          new MouseEvent("mousemove", { clientX: moveEvent.clientX }),
        );
      };
      const onPointerUp = (upEvent: PointerEvent) => {
        cleanupPointerSession?.();
        ownerDocument.dispatchEvent(
          new MouseEvent("mouseup", { clientX: upEvent.clientX }),
        );
      };
      cleanupPointerSession?.();
      cleanupPointerSession = () => {
        ownerDocument.removeEventListener("pointermove", onPointerMove);
        ownerDocument.removeEventListener("pointerup", onPointerUp);
        ownerDocument.removeEventListener("pointercancel", onPointerUp);
        cleanupPointerSession = undefined;
      };
      ownerDocument.addEventListener("pointermove", onPointerMove);
      ownerDocument.addEventListener("pointerup", onPointerUp);
      ownerDocument.addEventListener("pointercancel", onPointerUp);
      resizable(currentHeader).getResizeHandler?.()(
        event as unknown as MouseEvent,
      );
    };
    node.addEventListener("pointerdown", onPointerDown);
    return {
      update(nextHeader: Header<TFeatures, TData>) {
        currentHeader = nextHeader;
      },
      destroy() {
        cleanupPointerSession?.();
        node.removeEventListener("pointerdown", onPointerDown);
      },
    };
  };
  function applyHeaderAction(
    node: HTMLElement,
    item: Header<TFeatures, TData>,
  ) {
    return headerAction?.(node, item);
  }
  function applyCellAction(node: HTMLElement, item: Cell<TFeatures, TData>) {
    return cellAction?.(node, item);
  }
  function applyRowAction(node: HTMLElement, item: Row<TFeatures, TData>) {
    return rowAction?.(node, item);
  }
</script>

<div
  {...rest}
  data-slot="data-table"
  data-loading={loading || undefined}
  class={cn(
    dataTableRootClassName({ density, striped, bordered: border }),
    classes?.root,
  )}
  style={`--data-table-header-height:var(--data-table-row-height);${sizingLayout.rootWidth ? `width:${sizingLayout.rootWidth};` : ""}${style ?? ""}`}
>
  <div
    bind:this={viewportElement}
    data-slot="data-table-viewport"
    class={cn(dataTableViewportClassName, classes?.viewport)}
    style:height={virtual ? `${virtual.height}px` : undefined}
  >
    <table
      class={cn(dataTableClassName, classes?.table)}
      style:width={tableWidth === undefined ? "100%" : `${tableWidth}px`}
    >
      {#if tableWidth !== undefined}
        <colgroup>
          {#each columns as column (column.id)}
            <col
              style:width={columnSizeOf(column, $snapshot.revision) ===
              undefined
                ? undefined
                : `${columnSizeOf(column, $snapshot.revision)}px`}
            />
          {/each}
        </colgroup>
      {/if}
      <thead class={cn(dataTableHeaderClassName, classes?.header)}>
        {#each headerGroups as headerGroup (headerGroup.id)}
          <tr
            class={cn(
              dataTableHeaderRowClassName({ bordered: border }),
              classes?.headerRow,
            )}
          >
            {#each headerGroup.headers as item, index (item.id)}
              {@const nativeProps = headerPropsOf(item, $snapshot.revision)}
              {@const layout = headerLayoutOf(item, $snapshot.revision)}
              <th
                {...nativeProps}
                use:applyHeaderAction={item}
                colspan={item.colSpan}
                class={cn(
                  dataTableHeaderCellClassName,
                  layout.pinned && dataTablePinnedCellClassName,
                  layout.pinned && dataTablePinnedHeaderCellClassName,
                  layout.pinned === "start" && dataTablePinnedStartClassName,
                  layout.pinned === "end" && dataTablePinnedEndClassName,
                  layout.isStartEdge && dataTablePinnedStartEdgeClassName,
                  layout.isEndEdge && dataTablePinnedEndEdgeClassName,
                  !border &&
                    headerGroup.headers
                      .slice(index + 1)
                      .some((next) => !next.isPlaceholder) &&
                    dataTableHeaderSeparatorClassName,
                  metaOf(item.column)?.align &&
                    dataTableAlignClassName[metaOf(item.column)!.align!],
                  metaOf(item.column)?.headerClassName,
                  classes?.headerCell,
                  nativeProps.class,
                )}
                style={mergedStyle(layout.style, nativeProps.style)}
              >
                {#if !item.isPlaceholder}
                  <div
                    data-slot="data-table-header-content"
                    class={dataTableHeaderContentClassName}
                  >
                    {#key $snapshot.revision}
                      {#if header}{@render header(
                          item,
                          $snapshot.revision,
                        )}{:else}{text(
                          renderTemplate(
                            item.column.columnDef.header,
                            item.getContext(),
                            $snapshot.revision,
                          ),
                        )}{/if}
                    {/key}
                  </div>
                {/if}
                {#if item.colSpan === 1 && resizable(item).column.getCanResize?.()}
                  <button
                    type="button"
                    use:resizeHandle={item}
                    aria-label={`Resize ${item.column.id}`}
                    data-resizing={resizable(item).column.getIsResizing?.() ||
                      undefined}
                    class={dataTableResizeHandleClassName}
                    ondblclick={() => resizable(item).column.resetSize?.()}
                  ></button>
                {/if}
              </th>
            {/each}
          </tr>
        {/each}
      </thead>
      <tbody class={cn(dataTableBodyClassName, classes?.body)}>
        {#if virtual && virtualTop > 0}
          <tr aria-hidden="true"
            ><td
              colspan={Math.max(
                1,
                getDataTableVisibleLeafColumnCount(renderTable),
              )}
              class={dataTableVirtualSpacerClassName}
              style:height={`${virtualTop}px`}
            ></td></tr
          >
        {/if}
        {#if rows.length}
          {#each rows as row (row.id)}
            {@const nativeRowProps = rowPropsOf(row, $snapshot.revision)}
            {@const rowLayout = rowLayoutOf(row, $snapshot.revision)}
            {@const pinned = rowPinned(row, $snapshot.revision)}
            <tr
              {...nativeRowProps}
              use:applyRowAction={row}
              data-pinned={pinned || undefined}
              data-grouped={isGrouped(row) || undefined}
              class={cn(
                dataTableRowClassName,
                pinned && dataTablePinnedRowClassName,
                pinned === "top" && dataTablePinnedTopRowClassName,
                pinned === "bottom" && dataTablePinnedBottomRowClassName,
                rowLayout.edge === "top" && dataTablePinnedTopEdgeClassName,
                rowLayout.edge === "bottom" &&
                  dataTablePinnedBottomEdgeClassName,
                isGrouped(row) && dataTableGroupedRowClassName,
                classes?.row,
                nativeRowProps.class,
              )}
              style={mergedStyle(rowLayout.style, nativeRowProps.style)}
            >
              {#if $snapshot.revision >= 0 && isGrouped(row) && groupRow}
                <td
                  colspan={Math.max(
                    1,
                    getDataTableVisibleLeafColumnCount(renderTable),
                  )}
                  class={cn(dataTableCellClassName, classes?.cell)}
                >
                  {#key $snapshot.revision}{@render groupRow(
                      row,
                      $snapshot.revision,
                    )}{/key}
                </td>
              {:else}
                {#each cellsOf(row, $snapshot.revision) as item (item.id)}
                  {@const nativeCellProps = cellPropsOf(
                    item,
                    $snapshot.revision,
                  )}
                  {@const cellLayout = cellLayoutOf(item, $snapshot.revision)}
                  <td
                    {...nativeCellProps}
                    use:applyCellAction={item}
                    class={cn(
                      dataTableCellClassName,
                      cellLayout.pinned && dataTablePinnedCellClassName,
                      cellLayout.pinned === "start" &&
                        dataTablePinnedStartClassName,
                      cellLayout.pinned === "end" &&
                        dataTablePinnedEndClassName,
                      cellLayout.isStartEdge &&
                        dataTablePinnedStartEdgeClassName,
                      cellLayout.isEndEdge && dataTablePinnedEndEdgeClassName,
                      metaOf(item.column)?.align &&
                        dataTableAlignClassName[metaOf(item.column)!.align!],
                      metaOf(item.column)?.cellClassName,
                      classes?.cell,
                      nativeCellProps.class,
                    )}
                    style={mergedStyle(cellLayout.style, nativeCellProps.style)}
                  >
                    <div class={dataTableCellContentClassName}>
                      {#key $snapshot.revision}
                        {#if cell}{@render cell(
                            item,
                            $snapshot.revision,
                          )}{:else}{text(
                            renderTemplate(
                              item.column.columnDef.cell,
                              item.getContext(),
                              $snapshot.revision,
                            ) ?? item.getValue(),
                          )}{/if}
                      {/key}
                    </div>
                  </td>
                {/each}
              {/if}
            </tr>
            {#if $snapshot.revision >= 0 && isExpanded(row) && subComponent}
              <tr class={dataTableRowClassName}
                ><td colspan={getDataTableVisibleLeafColumnCount(renderTable)}
                  >{#key $snapshot.revision}{@render subComponent(
                      row,
                      $snapshot.revision,
                    )}{/key}</td
                ></tr
              >
            {/if}
          {/each}
        {:else}
          <tr
            ><td
              colspan={Math.max(
                1,
                getDataTableVisibleLeafColumnCount(renderTable),
              )}
              class={cn(dataTableEmptyClassName, classes?.empty)}
              >{emptyContent}</td
            ></tr
          >
        {/if}
        {#if virtual && virtualBottom > 0}
          <tr aria-hidden="true"
            ><td
              colspan={Math.max(
                1,
                getDataTableVisibleLeafColumnCount(renderTable),
              )}
              class={dataTableVirtualSpacerClassName}
              style:height={`${virtualBottom}px`}
            ></td></tr
          >
        {/if}
      </tbody>
    </table>
  </div>
  {#if loading}<div class={cn(dataTableLoadingClassName, classes?.loading)}>
      {loadingContent}
    </div>{/if}
</div>
