// apps/vue-app/src/pages/Transfer/one-way-demo.vue
<script setup lang="ts">
import { ChevronRightIcon } from '@fex-design/vue/icon/chevron'
import { TrashIcon } from '@fex-design/vue/icon/trash'
import { SwitchRoot, SwitchThumb } from '@fex-design/vue/primitive/switch'
import { Transfer } from '@fex-design/vue/primitive/transfer'
import Button from '@fex-design/vue/ui/button'
import Card from '@fex-design/vue/ui/card'
import { ref } from 'vue'
import { fieldNames, members } from './data'
const disabled = ref(false)
const targetKeys = ref<readonly (string | number)[]>(['susan', 'katherine'])
</script>
<template>
  <Card
    title="One-way composition"
    description="A custom action area only moves records to the target; target rows remove themselves through the same Transfer controller."
    ><div class="space-y-2">
      <Transfer
        :items="members"
        :field-names="fieldNames"
        :target-keys="targetKeys"
        :disabled="disabled"
        :title="{ source: 'Source', target: 'Target' }"
        @change="targetKeys = $event"
        ><template #actions="{ controller, snapshot }"
          ><Button
            variant="outline"
            size="icon"
            aria-label="Move selected to target"
            :disabled="!snapshot.sourceCheckedKeys.length"
            @click="controller.moveToTarget()"
            ><ChevronRightIcon /></Button></template
        ><template #targetHeader="{ api }"
          ><span class="font-medium">Target</span
          ><span class="ml-auto text-muted-foreground">{{ api.items.length }} items</span></template
        ><template #targetBody="{ api }"
          ><div class="space-y-1">
            <div
              v-for="item in api.items"
              :key="item.id"
              class="flex min-h-8 items-center gap-2 px-2 text-sm"
            >
              <span class="min-w-0 flex-1 truncate">{{ item.name }}</span
              ><Button
                variant="ghost"
                size="icon-xs"
                :aria-label="`Remove ${item.name}`"
                v-bind="disabled || item.disabled ? { disabled: true } : {}"
                @click="
                  api.setCheckedKeys([item.id])
                  api.controller.moveToSource()
                "
                ><TrashIcon
              /></Button>
            </div></div></template></Transfer
      ><label class="flex w-fit items-center gap-2 text-sm text-muted-foreground"
        ><SwitchRoot
          :checked="disabled"
          aria-label="Disable one-way Transfer"
          @checked-change="disabled = $event"
          ><template #default="{ checked }"
            ><SwitchThumb :checked="checked" /></template></SwitchRoot
        >Disabled</label
      >
    </div></Card
  >
</template>

// apps/solid-app/src/pages/Transfer/one-way-demo.tsx
import { ChevronRightIcon } from '@fex-design/solid/icon/chevron'
import { TrashIcon } from '@fex-design/solid/icon/trash'
import { SwitchRoot, SwitchThumb } from '@fex-design/solid/primitive/switch'
import { Transfer } from '@fex-design/solid/primitive/transfer'
import { Button } from '@fex-design/solid/ui/button'
import { Card } from '@fex-design/solid/ui/card'
import { createSignal, For } from 'solid-js'
import { fieldNames, members } from './data'
export function OneWayDemo() {
  const [disabled, setDisabled] = createSignal(false),
    [targetKeys, setTargetKeys] = createSignal<readonly (string | number)[]>(['susan', 'katherine'])
  return (
    <Card
      title="One-way composition"
      description="A custom action area only moves records to the target; target rows remove themselves through the same Transfer controller."
    >
      <div class="space-y-2">
        <Transfer
          items={members}
          fieldNames={fieldNames}
          targetKeys={targetKeys()}
          onChange={setTargetKeys}
          disabled={disabled()}
          title={{ source: 'Source', target: 'Target' }}
          actions={(controller, snapshot) => (
            <Button
              variant="outline"
              size="icon"
              aria-label="Move selected to target"
              disabled={!snapshot.sourceCheckedKeys.length}
              onClick={controller.moveToTarget}
            >
              <ChevronRightIcon />
            </Button>
          )}
          panels={{
            target: {
              header: (api) => (
                <>
                  <span class="font-medium">Target</span>
                  <span class="ml-auto text-muted-foreground">{api.items.length} items</span>
                </>
              ),
              body: (api) => (
                <div class="space-y-1">
                  <For each={api.items}>
                    {(item) => (
                      <div class="flex min-h-8 items-center gap-2 px-2 text-sm">
                        <span class="min-w-0 flex-1 truncate">{item.name}</span>
                        <Button
                          variant="ghost"
                          size="icon-xs"
                          aria-label={`Remove ${item.name}`}
                          disabled={disabled() || item.disabled}
                          onClick={() => {
                            api.setCheckedKeys([item.id])
                            api.controller.moveToSource()
                          }}
                        >
                          <TrashIcon />
                        </Button>
                      </div>
                    )}
                  </For>
                </div>
              ),
            },
          }}
        />
        <label class="flex w-fit items-center gap-2 text-sm text-muted-foreground">
          <SwitchRoot
            checked={disabled()}
            onChange={setDisabled}
            aria-label="Disable one-way Transfer"
          >
            <SwitchThumb />
          </SwitchRoot>
          Disabled
        </label>
      </div>
    </Card>
  )
}
