// apps/react-app/src/pages/Tree/search-demo.tsx
import { createTreeController } from '@fex-design/core/tree/create-tree-controller'
import { expansionFeature, searchFeature } from '@fex-design/core'
import type { SearchFeatureApi } from '@fex-design/core/tree/features/search'
import { InputControl, InputRoot } from '@fex-design/react/primitive/input'
import { useState } from 'react'
import { departmentFieldNames, departmentTreeData, type DepartmentNode } from './data'
import { DemoTree } from './demo-tree'
import { TreeDemoSection } from './demo-section'
import { highlightTreeTitle } from './highlight-tree-title'

const searchController = createTreeController<DepartmentNode>({
  treeData: departmentTreeData,
  fieldNames: departmentFieldNames,
  isLeaf: (node) => node.childCount === 0,
  features: [
    expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
    searchFeature(),
  ],
})

export function SearchTreeDemo() {
  const [keyword, setKeyword] = useState('')
  const subtree: readonly DepartmentNode[] =
    searchController.getFeature<SearchFeatureApi<DepartmentNode>>('search')?.getSubtree({
      keyword,
      filterTreeNode: (node, value) => node.name.toLowerCase().includes(value.toLowerCase()),
    }) ?? []
  const showingSearchTree = Boolean(keyword.trim())

  return (
    <TreeDemoSection
      title="Search data and custom title rendering"
      description="The core returns filtered tree data; title rendering decides how a keyword is highlighted."
    >
      <InputRoot value={keyword} className="mb-2 max-w-sm">
        <InputControl
          onChange={(event) => setKeyword(event.target.value)}
          placeholder="Search departments"
        />
      </InputRoot>
      <div hidden={showingSearchTree}>
        <DemoTree<DepartmentNode>
          controller={searchController}
          treeData={departmentTreeData}
          fieldNames={departmentFieldNames}
          isLeaf={(node) => node.childCount === 0}
          features={[
            expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
          ]}
          className="max-w-xl rounded-md border border-border bg-background p-1.5"
        />
      </div>
      {showingSearchTree ? (
        <DemoTree<DepartmentNode>
          treeData={subtree}
          fieldNames={departmentFieldNames}
          isLeaf={(node) => node.childCount === 0}
          features={[
            expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
          ]}
          searchKeyword={keyword}
          titleRender={({ item, searchKeyword }) =>
            highlightTreeTitle(item.node.name, searchKeyword)
          }
          className="max-w-xl rounded-md border border-border bg-background p-1.5"
        />
      ) : null}
    </TreeDemoSection>
  )
}

// apps/solid-app/src/pages/Tree/search-demo.tsx
import { expansionFeature, searchFeature } from '@fex-design/core'
import { createTreeController } from '@fex-design/core/tree/create-tree-controller'
import type { SearchFeatureApi } from '@fex-design/core/tree/features/search'
import { InputControl, InputRoot } from '@fex-design/solid/primitive/input'
import { Card } from '@fex-design/solid/ui/card'
import { createMemo, createSignal, Show } from 'solid-js'
import { DemoTree } from './demo-tree'
import { departmentFieldNames, departmentTreeData, type DepartmentNode } from './data'
const controller = createTreeController<DepartmentNode>({
  treeData: departmentTreeData,
  fieldNames: departmentFieldNames,
  isLeaf: (n) => n.childCount === 0,
  features: [
    expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
    searchFeature(),
  ],
})
export function SearchDemo() {
  const [keyword, setKeyword] = createSignal('')
  const subtree = createMemo(
    () =>
      controller.getFeature<SearchFeatureApi<DepartmentNode>>('search')?.getSubtree({
        keyword: keyword(),
        filterTreeNode: (n, v) => n.name.toLowerCase().includes(v.toLowerCase()),
      }) ?? [],
  )
  const highlight = (title: string) => {
    const index = title.toLowerCase().indexOf(keyword().toLowerCase())
    return index < 0 ? (
      title
    ) : (
      <>
        {title.slice(0, index)}
        <mark class="rounded-sm bg-warning/20 px-0.5 text-inherit">
          {title.slice(index, index + keyword().length)}
        </mark>
        {title.slice(index + keyword().length)}
      </>
    )
  }
  return (
    <Card
      title="Search data and custom title rendering"
      description="The core returns filtered tree data; title rendering decides how a keyword is highlighted."
    >
      <InputRoot value={keyword()} class="mb-2 max-w-sm">
        <InputControl
          onInput={(e) => setKeyword(e.currentTarget.value)}
          placeholder="Search departments"
        />
      </InputRoot>
      <div hidden={Boolean(keyword().trim())}>
        <DemoTree<DepartmentNode>
          controller={controller}
          treeData={departmentTreeData}
          fieldNames={departmentFieldNames}
          isLeaf={(n) => n.childCount === 0}
          features={[
            expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
          ]}
          class="max-w-xl rounded-md border border-border bg-background p-1.5"
        />
      </div>
      <Show when={Boolean(keyword().trim())}>
        <DemoTree<DepartmentNode>
          treeData={subtree()}
          fieldNames={departmentFieldNames}
          isLeaf={(n) => n.childCount === 0}
          features={[
            expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
          ]}
          searchKeyword={keyword()}
          titleRender={({ item }) => highlight(String(item.node.name))}
          class="max-w-xl rounded-md border border-border bg-background p-1.5"
        />
      </Show>
    </Card>
  )
}
