// apps/vue-app/src/pages/ColorPicker/demo-card.vue
<script setup lang="ts">
import { ColorPickerRoot } from '@fex-design/vue/primitive/color-picker'
import Card from '@fex-design/vue/ui/card'
import { ref } from 'vue'
import PickerSurface from './picker-surface.vue'
const props = withDefaults(
  defineProps<{
    title: string
    description: string
    controlled?: boolean
    alpha?: boolean
    clear?: boolean
    text?: boolean
    hover?: boolean
    disabled?: boolean
    inline?: boolean
    oklch?: boolean
  }>(),
  { alpha: true },
)
const value = ref<string | null>('#1677FF')
</script>
<template>
  <Card :title="title" :description="description"
    ><ColorPickerRoot
      :value="controlled ? value : undefined"
      default-value="#1677FF"
      :disabled="disabled"
      @change="
        (next) => {
          if (controlled) value = next?.toString('oklch') ?? null
        }
      "
      ><PickerSurface
        :alpha="alpha"
        :clear="clear"
        :text="text"
        :hover="hover"
        :inline="inline"
        :oklch="oklch" /></ColorPickerRoot
    ><code v-if="controlled" class="mt-2 block text-xs text-muted-foreground">{{
      value
    }}</code></Card
  >
</template>

// apps/svelte-app/src/routes/color-picker/demo-card.svelte
<script lang="ts">
  import { ColorPickerRoot } from "@fex-design/svelte/primitive/color-picker";
  import Card from "@fex-design/svelte/ui/card";
  import PickerSurface from "./picker-surface.svelte";
  let {
    title,
    description,
    controlled = false,
    alpha = true,
    clear = false,
    text = false,
    hover = false,
    disabled = false,
    inline = false,
    oklch = false,
  }: {
    title: string;
    description: string;
    controlled?: boolean;
    alpha?: boolean;
    clear?: boolean;
    text?: boolean;
    hover?: boolean;
    disabled?: boolean;
    inline?: boolean;
    oklch?: boolean;
  } = $props();
  let value = $state<string | null>("#1677FF");
</script>

<Card {title} {description}
  ><ColorPickerRoot
    value={controlled ? value : undefined}
    defaultValue="#1677FF"
    {disabled}
    onChange={(next) => {
      if (controlled) value = next?.toString("oklch") ?? null;
    }}
    ><PickerSurface
      {alpha}
      {clear}
      {text}
      {hover}
      {inline}
      {oklch}
    /></ColorPickerRoot
  >{#if controlled}<code class="mt-2 block text-xs text-muted-foreground"
      >{value}</code
    >{/if}</Card
>
