// packages/@fex-design/components/solid/src/primitive/table/table-row.tsx
import { tableRowClassName } from "@fex-design/components-styles/table"
import { cn } from "@fex-design/utils"
import type { JSX, ParentProps } from "solid-js"
import { splitProps } from "solid-js"

export type TableRowProps = ParentProps<JSX.HTMLAttributes<HTMLTableRowElement>>

export function TableRow(props: TableRowProps) {
  const [local, rest] = splitProps(props, ["class", "children"])
  return <tr {...rest} data-slot="table-row" class={cn(tableRowClassName, local.class)}>{local.children}</tr>
}

// packages/@fex-design/components/react/src/primitive/table/table-row.tsx
import { tableRowClassName } from "@fex-design/components-styles/table"
import { cn } from "@fex-design/utils"
import type { ComponentProps } from "react"

export type TableRowProps = ComponentProps<"tr">

export function TableRow({ className, ...props }: TableRowProps) {
  return <tr data-slot="table-row" className={cn(tableRowClassName, className)} {...props} />
}
