// packages/@fex-design/components/angular/src/primitive/table/table.ts
import {
  tableBodyClassName,
  tableCaptionClassName,
  tableCellClassName,
  tableClassName,
  tableContainerClassName,
  tableFooterClassName,
  tableHeadClassName,
  tableHeaderClassName,
  tableRowClassName,
} from '@fex-design/components-styles/table'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { createHostClassName } from '@fex-design/angular/signals/host-class'

@Component({
  selector: 'fex-table-container',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'containerClassName', 'data-slot': 'table-container' },
  template: '<ng-content />',
})
export class TableContainer {
  protected readonly containerClassName = tableContainerClassName
}

@Component({
  selector: 'table[fexTable]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table',
  },
  template: '<ng-content />',
})
export class Table {
  protected readonly hostClassName = createHostClassName(tableClassName)
}

@Component({
  selector: 'thead[fexTableHeader]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-header',
  },
  template: '<ng-content />',
})
export class TableHeader {
  protected readonly hostClassName = createHostClassName(tableHeaderClassName)
}

@Component({
  selector: 'tbody[fexTableBody]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-body',
  },
  template: '<ng-content />',
})
export class TableBody {
  protected readonly hostClassName = createHostClassName(tableBodyClassName)
}

@Component({
  selector: 'tfoot[fexTableFooter]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-footer',
  },
  template: '<ng-content />',
})
export class TableFooter {
  protected readonly hostClassName = createHostClassName(tableFooterClassName)
}

@Component({
  selector: 'tr[fexTableRow]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-row',
  },
  template: '<ng-content />',
})
export class TableRow {
  protected readonly hostClassName = createHostClassName(tableRowClassName)
}

@Component({
  selector: 'th[fexTableHead]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-head',
  },
  template: '<ng-content />',
})
export class TableHead {
  protected readonly hostClassName = createHostClassName(tableHeadClassName)
}

@Component({
  selector: 'td[fexTableCell]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-cell',
  },
  template: '<ng-content />',
})
export class TableCell {
  protected readonly hostClassName = createHostClassName(tableCellClassName)
}

@Component({
  selector: 'caption[fexTableCaption]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'table-caption',
  },
  template: '<ng-content />',
})
export class TableCaption {
  protected readonly hostClassName = createHostClassName(tableCaptionClassName)
}

// packages/@fex-design/components/react/src/primitive/table/table.tsx
import {
  tableBodyClassName,
  tableCaptionClassName,
  tableCellClassName,
  tableClassName,
  tableContainerClassName,
  tableFooterClassName,
  tableHeadClassName,
  tableHeaderClassName,
  tableRowClassName,
} from '@fex-design/components-styles/table'
import { cn } from '@fex-design/utils'
import type { ComponentProps } from 'react'

export function Table({ className, ...props }: ComponentProps<'table'>) {
  return (
    <div data-slot="table-container" className={tableContainerClassName}>
      <table data-slot="table" className={cn(tableClassName, className)} {...props} />
    </div>
  )
}

export function TableHeader({ className, ...props }: ComponentProps<'thead'>) {
  return (
    <thead data-slot="table-header" className={cn(tableHeaderClassName, className)} {...props} />
  )
}

export function TableBody({ className, ...props }: ComponentProps<'tbody'>) {
  return <tbody data-slot="table-body" className={cn(tableBodyClassName, className)} {...props} />
}

export function TableFooter({ className, ...props }: ComponentProps<'tfoot'>) {
  return (
    <tfoot data-slot="table-footer" className={cn(tableFooterClassName, className)} {...props} />
  )
}

export function TableRow({ className, ...props }: ComponentProps<'tr'>) {
  return <tr data-slot="table-row" className={cn(tableRowClassName, className)} {...props} />
}

export function TableHead({ className, ...props }: ComponentProps<'th'>) {
  return <th data-slot="table-head" className={cn(tableHeadClassName, className)} {...props} />
}

export function TableCell({ className, ...props }: ComponentProps<'td'>) {
  return <td data-slot="table-cell" className={cn(tableCellClassName, className)} {...props} />
}

export function TableCaption({ className, ...props }: ComponentProps<'caption'>) {
  return (
    <caption
      data-slot="table-caption"
      className={cn(tableCaptionClassName, className)}
      {...props}
    />
  )
}
