// apps/react-app/src/pages/Bubble/links-buttons-demo.tsx
import { Bubble, BubbleContent } from '@fex-design/react/primitive/bubble'
import { Button } from '@fex-design/react/ui/button'
import { Card } from '@fex-design/react/ui/card'
export function LinksButtonsDemo() {
  return (
    <Card
      title="Links and buttons"
      description="BubbleContent render keeps the bubble surface while callers choose the actual interactive element."
    >
      <div className="grid gap-2">
        <Bubble>
          <BubbleContent
            render={({ props }) => (
              <Button {...props} variant="secondary">
                I forgot my password
              </Button>
            )}
          />
        </Bubble>
        <Bubble>
          <BubbleContent
            render={({ props }) => (
              <a {...props} href="#subscription">
                I need help with my subscription
              </a>
            )}
          />
        </Bubble>
      </div>
    </Card>
  )
}

// apps/angular-app/src/pages/bubble/links-buttons-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { Bubble, BubbleContent } from '@fex-design/angular/primitive/bubble'
import { Button } from '@fex-design/angular/ui/button'
import Card from '@fex-design/angular/ui/card'
export
@Component({
  selector: 'fex-bubble-links-buttons-demo',
  standalone: true,
  imports: [Card, Bubble, BubbleContent, Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './links-buttons-demo.component.html',
})
class BubbleLinksButtonsDemoComponent {}

<fex-card
  title="Links and buttons"
  description="BubbleContent keeps the bubble surface while callers choose the actual interactive element."
  ><div class="grid gap-2">
    <fex-bubble
      ><button fexBubbleContent button variant="secondary">I forgot my password</button></fex-bubble
    ><fex-bubble
      ><a fexBubbleContent href="#subscription">I need help with my subscription</a></fex-bubble
    >
  </div></fex-card
>
