// apps/solid-app/src/pages/Cascader/demo-section.tsx
import { Card } from '@fex-design/solid/ui/card'
import type { ParentProps } from 'solid-js'
export function DemoSection(props: ParentProps<{ title: string; description: string }>) {
  return (
    <Card title={props.title} description={props.description}>
      <div class="max-w-xl space-y-2">{props.children}</div>
    </Card>
  )
}

// apps/react-app/src/pages/Cascader/demo-section.tsx
import { Card } from '@fex-design/react/ui/card'
import type { ReactNode } from 'react'
export function DemoSection(props: { title: string; description: string; children: ReactNode }) {
  return (
    <Card title={props.title} description={props.description}>
      <div className="max-w-xl space-y-2">{props.children}</div>
    </Card>
  )
}
