// apps/solid-app/src/pages/Cascader/lazy-load-demo.tsx
import type { CascaderOption } from '@fex-design/core/cascader/types'
import { createSignal } from 'solid-js'
import { lazyInitialOptions } from './data'
import { DemoCascader } from './demo-cascader'
import { DemoSection } from './demo-section'
export function LazyLoadDemo() {
  const [options, setOptions] = createSignal(lazyInitialOptions)
  async function load(path: readonly CascaderOption[]) {
    await new Promise((resolve) => setTimeout(resolve, 700))
    const key = String(path.at(-1)?.value)
    setOptions((current) =>
      current.map((item) =>
        item.value === key
          ? {
              ...item,
              children:
                key === 'asia'
                  ? [{ value: 'china', label: '中国', isLeaf: false }]
                  : [{ value: 'france', label: '法国' }],
            }
          : item,
      ),
    )
    if (key === 'china')
      setOptions((current) =>
        current.map((item) =>
          item.value === 'asia'
            ? {
                ...item,
                children: [
                  {
                    value: 'china',
                    label: '中国',
                    children: [{ value: 'hangzhou', label: '杭州' }],
                  },
                ],
              }
            : item,
        ),
      )
  }
  return (
    <DemoSection
      title="Lazy load"
      description="Unresolved nodes load one path and reject duplicate requests."
    >
      <DemoCascader options={options()} loadData={load} />
    </DemoSection>
  )
}

// apps/react-app/src/pages/Cascader/lazy-load-demo.tsx
import type { CascaderOption } from '@fex-design/core/cascader/types'
import { useState } from 'react'
import { lazyInitialOptions } from './data'
import { DemoCascader } from './demo-cascader'
import { DemoSection } from './demo-section'
export function LazyLoadDemo() {
  const [options, setOptions] = useState(lazyInitialOptions)
  async function load(path: readonly CascaderOption[]) {
    await new Promise((resolve) => setTimeout(resolve, 700))
    const key = String(path.at(-1)?.value)
    setOptions((current) =>
      current.map((item) =>
        item.value === key
          ? {
              ...item,
              children:
                key === 'asia'
                  ? [{ value: 'china', label: '中国', isLeaf: false }]
                  : [{ value: 'france', label: '法国' }],
            }
          : item,
      ),
    )
    if (key === 'china')
      setOptions((current) =>
        current.map((item) =>
          item.value === 'asia'
            ? {
                ...item,
                children: [
                  {
                    value: 'china',
                    label: '中国',
                    children: [{ value: 'hangzhou', label: '杭州' }],
                  },
                ],
              }
            : item,
        ),
      )
  }
  return (
    <DemoSection
      title="Lazy load"
      description="Expanding an unresolved node loads only that path and prevents duplicate requests."
    >
      <DemoCascader options={options} loadData={load} />
    </DemoSection>
  )
}
