// packages/@fex-design/angular/src/primitive/input-number/use-input-number.ts
import type {
  InputNumberConstraints,
  InputNumberFormatter,
  InputNumberParser,
} from '@fex-design/core/input-number/types'
import {
  defaultInputNumberFormatter,
  defaultInputNumberParser,
  isInputNumberOutOfRange,
  normalizeInputNumber,
  parseInputNumber,
  stepInputNumber,
} from '@fex-design/core/input-number/value'
import { computed, effect, signal, type Signal } from '@angular/core'
export interface UseInputNumberOptions extends InputNumberConstraints {
  controlled?: boolean | undefined
  value?: number | undefined
  defaultValue?: number | undefined
  parser?: InputNumberParser | undefined
  formatter?: InputNumberFormatter | undefined
  disabled?: boolean | undefined
  readOnly?: boolean | undefined
  keyboard?: boolean | undefined
  onChange?: ((event: Event, value: number | undefined) => void) | undefined
}
export function useInputNumber(options: Signal<UseInputNumberOptions>) {
  const internalValue = signal(options().defaultValue)
  const value = computed(() => (options().controlled ? options().value : internalValue()))
  const draft = signal(
    (options().formatter ?? defaultInputNumberFormatter)(value(), { userTyping: false, input: '' }),
  )
  const parser = () => options().parser ?? defaultInputNumberParser
  const formatter = () => options().formatter ?? defaultInputNumberFormatter
  const constraints = () => ({
    min: options().min,
    max: options().max,
    step: options().step,
    precision: options().precision,
  })
  let editing = false
  // Synchronize caller-owned controlled values into the editable text buffer outside active typing.
  effect(() => {
    const next = value()
    if (!editing) draft.set(formatter()(next, { userTyping: false, input: '' }))
  })
  const setValue = (next: number | undefined) => {
    if (!options().controlled) internalValue.set(next)
  }
  const commit = (next: number | undefined) => {
    const normalized = next === undefined ? undefined : normalizeInputNumber(next, constraints())
    setValue(normalized)
    draft.set(formatter()(normalized, { userTyping: false, input: draft() }))
    return normalized
  }
  const changeBy = (event: Event, direction: 'increment' | 'decrement') => {
    const next = commit(
      stepInputNumber(parseInputNumber(draft(), parser()) ?? value(), direction, constraints()),
    )
    options().onChange?.(event, next)
  }
  return {
    value,
    draft,
    min: computed(() => options().min),
    max: computed(() => options().max),
    formattedValue: computed(() => formatter()(value(), { userTyping: false, input: draft() })),
    outOfRange: computed(() => isInputNumberOutOfRange(value(), constraints())),
    canClear: computed(() => value() !== undefined && !options().disabled && !options().readOnly),
    canIncrement: computed(
      () =>
        !options().disabled &&
        !options().readOnly &&
        (options().max === undefined || value() === undefined || value()! < options().max!),
    ),
    canDecrement: computed(
      () =>
        !options().disabled &&
        !options().readOnly &&
        (options().min === undefined || value() === undefined || value()! > options().min!),
    ),
    initialize(next: number | undefined) {
      if (options().controlled) return
      internalValue.set(next)
      draft.set(formatter()(next, { userTyping: false, input: '' }))
    },
    input(text: string, event: Event) {
      editing = true
      draft.set(text)
      const next = parseInputNumber(text, parser())
      if (text.trim() === '' || next !== undefined) {
        setValue(next)
        options().onChange?.(event, next)
      }
    },
    blur(event: Event) {
      const before = value()
      const next = commit(parseInputNumber(draft(), parser()) ?? before)
      editing = false
      if (next !== before) options().onChange?.(event, next)
    },
    keydown(event: KeyboardEvent) {
      if (options().keyboard === false || options().disabled || options().readOnly) return
      if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
        event.preventDefault()
        changeBy(event, event.key === 'ArrowUp' ? 'increment' : 'decrement')
      }
    },
    clear(event: Event) {
      commit(undefined)
      options().onChange?.(event, undefined)
    },
    increment: (event: Event) => changeBy(event, 'increment'),
    decrement: (event: Event) => changeBy(event, 'decrement'),
    commit,
  }
}
export type UseInputNumberReturn = ReturnType<typeof useInputNumber>

// packages/@fex-design/react/src/primitive/input-number/use-input-number.ts
import {
  defaultInputNumberFormatter,
  defaultInputNumberParser,
  isInputNumberOutOfRange,
  normalizeInputNumber,
  parseInputNumber,
  stepInputNumber,
} from '@fex-design/core/input-number/value'
import type {
  InputNumberConstraints,
  InputNumberFormatter,
  InputNumberParser,
} from '@fex-design/core/input-number/types'
import { useState, type KeyboardEvent } from 'react'
import { useControllableState } from '../../hooks/use-controllable-state'
import { useMemoizedFn } from '../../hooks/use-memoized-fn'
import useUpdateEffect from '../../hooks/use-update-effect'

export interface UseInputNumberOptions extends InputNumberConstraints {
  controlled?: boolean | undefined
  value?: number | undefined
  defaultValue?: number | undefined
  parser?: InputNumberParser | undefined
  formatter?: InputNumberFormatter | undefined
  disabled?: boolean | undefined
  readOnly?: boolean | undefined
  keyboard?: boolean | undefined
  onChange?: ((event: Event, value: number | undefined) => void) | undefined
}

export function useInputNumber(options: UseInputNumberOptions = {}) {
  const {
    value,
    defaultValue,
    parser = defaultInputNumberParser,
    formatter = defaultInputNumberFormatter,
    disabled = false,
    readOnly = false,
    keyboard = true,
    onChange,
  } = options
  const constraints: InputNumberConstraints = {
    min: options.min,
    max: options.max,
    step: options.step,
    precision: options.precision,
  }
  const [currentValue, setCurrentValue] = useControllableState<number | undefined>(
    { value, defaultValue },
    { trigger: 'onChange', isControlled: () => options.controlled ?? value !== undefined },
  )
  const format = useMemoizedFn(
    (nextValue: number | undefined, userTyping: boolean, input: string) =>
      formatter(nextValue, { userTyping, input }),
  )
  const [draft, setDraft] = useState(() => format(currentValue, false, ''))
  const [userTyping, setUserTyping] = useState(false)

  // The editable text buffer follows external controlled values only while the user is not typing.
  useUpdateEffect(() => {
    if (!userTyping) setDraft(format(currentValue, false, draft))
  }, [currentValue, format, userTyping])

  const parse = useMemoizedFn((text: string) => parseInputNumber(text, parser))
  const input = useMemoizedFn((text: string, event: Event) => {
    setUserTyping(true)
    setDraft(text)
    const nextValue = parse(text)
    if (text.trim() === '' || nextValue !== undefined) {
      setCurrentValue(nextValue)
      onChange?.(event, nextValue)
    }
    return nextValue
  })
  const commit = useMemoizedFn((nextValue: number | undefined) => {
    const normalized =
      nextValue === undefined ? undefined : normalizeInputNumber(nextValue, constraints)
    setCurrentValue(normalized)
    setUserTyping(false)
    setDraft(format(normalized, false, draft))
    return normalized
  })
  const stepBy = useMemoizedFn((direction: 'increment' | 'decrement') =>
    commit(stepInputNumber(parse(draft) ?? currentValue, direction, constraints)),
  )
  const clear = useMemoizedFn(() => commit(undefined))

  const changeBy = useMemoizedFn((event: Event, direction: 'increment' | 'decrement') => {
    const next = stepBy(direction)
    onChange?.(event, next)
    return next
  })

  const blur = useMemoizedFn((event: Event) => {
    const before = currentValue
    const next = commit(parse(draft) ?? before)
    if (next !== before) onChange?.(event, next)
  })

  const keydown = useMemoizedFn((event: KeyboardEvent<HTMLInputElement>) => {
    if (!keyboard || disabled || readOnly) return
    if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
      event.preventDefault()
      changeBy(event.nativeEvent, event.key === 'ArrowUp' ? 'increment' : 'decrement')
    }
  })

  return {
    value: currentValue,
    min: options.min,
    max: options.max,
    draft,
    formattedValue: format(currentValue, false, draft),
    userTyping,
    disabled,
    readOnly,
    outOfRange: isInputNumberOutOfRange(currentValue, constraints),
    canClear: currentValue !== undefined && !disabled && !readOnly,
    canIncrement:
      !disabled &&
      !readOnly &&
      (options.max === undefined || currentValue === undefined || currentValue < options.max),
    canDecrement:
      !disabled &&
      !readOnly &&
      (options.min === undefined || currentValue === undefined || currentValue > options.min),
    input,
    commit,
    increment: (event: Event) => changeBy(event, 'increment'),
    decrement: (event: Event) => changeBy(event, 'decrement'),
    clear: (event?: Event) => {
      const next = clear()
      if (event) onChange?.(event, next)
      return next
    },
    blur,
    keydown,
    parseDraft: () => parse(draft),
  }
}

export type UseInputNumberReturn = ReturnType<typeof useInputNumber>
