// packages/@fex-design/react/src/primitive/badge/examples/group.tsx
import { Badge, BadgeGroup } from '@fex-design/react/primitive/badge'
export function Group() {
  return (
    <BadgeGroup maxCount={3}>
      {['React', 'Vue', 'Solid', 'Svelte', 'Angular'].map((item) => (
        <Badge key={item} color="info">
          {item}
        </Badge>
      ))}
    </BadgeGroup>
  )
}

// packages/@fex-design/vue/src/ui/badge/examples/group.vue
<script setup lang="ts">
import { Badge, BadgeGroup } from '@fex-design/vue/ui/badge'
const items = ['Vue', 'React', 'Solid', 'Svelte', 'Angular']
</script>
<template>
  <BadgeGroup :max-count="3"
    ><Badge v-for="item in items" :key="item" color="info">{{ item }}</Badge></BadgeGroup
  >
</template>
