// packages/@fex-design/components/solid/src/primitive/progress/progress-track.tsx
import { progressLineClassName } from '@fex-design/components-styles/progress'
import { cn } from '@fex-design/utils'
import { splitProps, type JSX } from 'solid-js'
import { useProgressContext } from './progress-context'

export type ProgressTrackProps = JSX.HTMLAttributes<HTMLDivElement>

export function ProgressTrack(props: ProgressTrackProps) {
  const [local, others] = splitProps(props, ['class', 'style', 'children'])
  const context = useProgressContext('ProgressTrack')
  const style = () => typeof local.style === 'string'
    ? `height: ${context().thickness}px; ${local.style}`
    : { height: `${context().thickness}px`, ...local.style }
  return (
    <div {...others} data-slot="progress-track" data-status={context().status}
      class={cn(progressLineClassName, local.class)} style={style()}>
      {local.children}
    </div>
  )
}

// packages/@fex-design/components/react/src/primitive/progress/progress-track.tsx
import { progressLineClassName } from '@fex-design/components-styles/progress'
import { cn } from '@fex-design/utils'
import { type ComponentProps, type Ref } from 'react'
import { useProgressContext } from './progress-context'

export interface ProgressTrackProps extends ComponentProps<'div'> {
  ref?: Ref<HTMLDivElement>
}
export function ProgressTrack({
  ref,
  className,
  style,
  children,
  ...props
}: ProgressTrackProps) {
  const context = useProgressContext('ProgressTrack')
  return (
    <div
      {...props}
      ref={ref}
      data-slot="progress-track"
      data-status={context.status}
      className={cn(progressLineClassName, className)}
      style={{ height: context.thickness, ...style }}
    >
      {children}
    </div>
  )
}
