// apps/vue-app/src/pages/DataTable/sizing-demo.vue
<script setup lang="ts">
import {
  columnResizingFeature,
  columnSizingFeature,
} from '@fex-design/core/data-table/features/column-sizing'
import type { DataTableColumnMeta } from '@fex-design/core/data-table/types'
import { DataTable, tableFeatures, type ColumnDef } from '@fex-design/vue/primitive/data-table'
import { useDataTable } from '@fex-design/vue/composables/use-data-table'
import { people5, type Person } from './data'
import DemoSection from './demo-section.vue'
const m = { columnSizingFeature, columnResizingFeature }
type F = typeof m & { columnMeta: DataTableColumnMeta<F, Person> }
const f: F = tableFeatures({ ...m, columnMeta: {} })
const columns: ColumnDef<F, Person>[] = [
  { accessorKey: 'name', header: 'Name', size: 220, minSize: 140, maxSize: 320 },
  { accessorKey: 'department', header: 'Department', size: 180, minSize: 120 },
  { accessorKey: 'status', header: 'Status', size: 130, enableResizing: false },
  { accessorKey: 'progress', header: 'Progress', size: 140 },
]
const change = useDataTable({
  features: f,
  data: people5,
  columns,
  getRowId: (r) => r.id,
  columnResizeMode: 'onChange',
})
const end = useDataTable({
  features: f,
  data: people5,
  columns,
  getRowId: (r) => r.id,
  columnResizeMode: 'onEnd',
})
</script>
<template>
  <DemoSection
    title="Column sizing and resizing"
    description="Sizing and resizing remain separate v9 features. Drag a header separator; double-click resets the column. Status demonstrates per-column resize disablement."
    ><div class="grid gap-3 xl:grid-cols-2">
      <section class="space-y-1.5">
        <h3 class="text-sm font-medium text-foreground">Resize on change</h3>
        <DataTable :table="change" />
      </section>
      <section class="space-y-1.5">
        <h3 class="text-sm font-medium text-foreground">Resize on end + bordered table</h3>
        <DataTable :table="end" border />
      </section></div
  ></DemoSection>
</template>

// apps/react-app/src/pages/DataTable/sizing-demo.tsx
import {
  columnResizingFeature,
  columnSizingFeature,
} from '@fex-design/core/data-table/features/column-sizing'
import type { DataTableColumnMeta } from '@fex-design/core/data-table/types'
import type { TableFeatures } from '@fex-design/react/primitive/data-table'
import {
  DataTable,
  tableFeatures,
  useDataTable,
  type ColumnDef,
} from '@fex-design/react/primitive/data-table'
import { DataTableDemoSection, DemoBranch } from './demo-section'
import { people5, type Person } from './data'

const sizingFeatures = tableFeatures({
  columnSizingFeature,
  columnResizingFeature,
  columnMeta: {} as DataTableColumnMeta<TableFeatures, Person>,
})

function SizingGrid({
  direction,
  border = false,
}: {
  direction: 'onChange' | 'onEnd'
  border?: boolean
}) {
  const columns: ColumnDef<typeof sizingFeatures, Person>[] = [
    { accessorKey: 'name', header: 'Name', size: 220, minSize: 140, maxSize: 320 },
    { accessorKey: 'department', header: 'Department', size: 180, minSize: 120 },
    { accessorKey: 'status', header: 'Status', size: 130, enableResizing: false },
    { accessorKey: 'progress', header: 'Progress', size: 140 },
  ]
  const table = useDataTable({
    features: sizingFeatures,
    data: people5,
    columns,
    getRowId: (row) => row.id,
    columnResizeMode: direction,
  })
  return <DataTable table={table} border={border} />
}

export function SizingDataTableDemo() {
  return (
    <DataTableDemoSection
      title="Column sizing and resizing"
      description="Sizing and resizing remain separate v9 features. Drag a header separator; double-click resets the column. Status demonstrates per-column resize disablement."
    >
      <div className="grid gap-3 xl:grid-cols-2">
        <DemoBranch title="Resize on change">
          <SizingGrid direction="onChange" />
        </DemoBranch>
        <DemoBranch title="Resize on end + bordered table">
          <SizingGrid direction="onEnd" border />
        </DemoBranch>
      </div>
    </DataTableDemoSection>
  )
}
