// apps/svelte-app/src/routes/qrcode/color-demo.svelte
<script lang="ts">
  import { QrCodeBackground, QrCodeModules, QrCodeRoot, QrCodeSvg } from '@fex-design/svelte/primitive/qrcode'
  import Card from '@fex-design/svelte/ui/card'
</script>

<Card title="自定义颜色" description="color 和 bgColor 进入 core 模型，再由渲染部件消费。">
  <div class="flex flex-wrap gap-3">
    <QrCodeRoot value="https://fex.design/qrcode/blue" size={160} color="#075985" bgColor="#f0f9ff">
      <QrCodeSvg><QrCodeBackground /><QrCodeModules /></QrCodeSvg>
    </QrCodeRoot>
    <QrCodeRoot value="https://fex.design/qrcode/green" size={160} color="#166534" bgColor="#f0fdf4">
      <QrCodeSvg><QrCodeBackground /><QrCodeModules /></QrCodeSvg>
    </QrCodeRoot>
  </div>
</Card>

// apps/react-app/src/pages/QRCode/color-demo.tsx
import { QrCode } from '@fex-design/react/primitive/qrcode'
import { Card } from '@fex-design/react/ui/card'

export function ColorDemo() {
  return (
    <Card title="自定义颜色" description="color 和 bgColor 进入 core 模型，再由渲染部件消费。">
      <div className="flex flex-wrap gap-3">
        <QrCode.Root value="https://fex.design/qrcode/blue" size={160} color="#075985" bgColor="#f0f9ff">
          <QrCode.Svg>
            <QrCode.Background />
            <QrCode.Modules />
          </QrCode.Svg>
        </QrCode.Root>
        <QrCode.Root value="https://fex.design/qrcode/green" size={160} color="#166534" bgColor="#f0fdf4">
          <QrCode.Svg>
            <QrCode.Background />
            <QrCode.Modules />
          </QrCode.Svg>
        </QrCode.Root>
      </div>
    </Card>
  )
}
