// apps/solid-app/src/pages/QRCode/overlay-demo.tsx
import { createSignal } from 'solid-js'
import { QrCode } from '@fex-design/solid/primitive/qrcode'
import Button from '@fex-design/solid/ui/button'
import Card from '@fex-design/solid/ui/card'

export function OverlayDemo() {
  const [expired, setExpired] = createSignal(true)

  return (
    <Card title="Overlay" description="Overlay 不参与二维码生成，可组合加载、失效和自定义操作状态。">
      <div class="flex flex-wrap items-center gap-2">
        <QrCode.Root value="https://fex.design/overlay" size={176}>
          <QrCode.Svg>
            <QrCode.Background />
            <QrCode.Modules />
          </QrCode.Svg>
          {expired() ? (
            <QrCode.Overlay>
              <Button size="sm" onClick={() => setExpired(false)}>
                Refresh
              </Button>
            </QrCode.Overlay>
          ) : null}
        </QrCode.Root>
        <Button variant="outline" onClick={() => setExpired((value) => !value)}>
          Toggle overlay
        </Button>
      </div>
    </Card>
  )
}

// apps/react-app/src/pages/QRCode/overlay-demo.tsx
import { useState } from 'react'
import { QrCode } from '@fex-design/react/primitive/qrcode'
import { Button } from '@fex-design/react/ui/button'
import { Card } from '@fex-design/react/ui/card'

export function OverlayDemo() {
  const [expired, setExpired] = useState(true)

  return (
    <Card
      title="Overlay"
      description="Overlay 不参与二维码生成，可组合加载、失效和自定义操作状态。"
    >
      <div className="flex flex-wrap items-center gap-2">
        <QrCode.Root value="https://fex.design/overlay" size={176}>
          <QrCode.Svg>
            <QrCode.Background />
            <QrCode.Modules />
          </QrCode.Svg>
          {expired ? (
            <QrCode.Overlay>
              <Button size="sm" onClick={() => setExpired(false)}>
                Refresh
              </Button>
            </QrCode.Overlay>
          ) : null}
        </QrCode.Root>
        <Button variant="outline" onClick={() => setExpired((value) => !value)}>
          Toggle overlay
        </Button>
      </div>
    </Card>
  )
}
