// apps/vue-app/src/pages/Breadcrumb/capsule-breadcrumb.vue
<script setup lang="ts">
import Breadcrumb, {
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
} from '@fex-design/vue/primitive/breadcrumb'
</script>
<template>
  <Breadcrumb class="p-1"
    ><BreadcrumbList
      class="w-max items-center gap-0 rounded-full text-muted-foreground overflow-hidden"
      ><BreadcrumbItem class="group z-[3] -mr-4.5"
        ><BreadcrumbLink
          class="inline-flex items-center gap-0.5 px-4 border border-border rounded-full bg-muted-background hover:bg-hover-background group-not-first:pl-6"
          href="/"
          >Workspace</BreadcrumbLink
        ></BreadcrumbItem
      ><BreadcrumbItem class="group z-[2] -mr-4.5"
        ><BreadcrumbLink
          class="inline-flex items-center gap-0.5 px-4 pl-6 border border-border rounded-full bg-muted-background hover:bg-hover-background"
          href="/projects"
          >Projects</BreadcrumbLink
        ></BreadcrumbItem
      ><BreadcrumbItem class="group z-[1]"
        ><BreadcrumbPage
          class="inline-flex items-center gap-0.5 px-4 pl-6 border border-border rounded-full bg-muted-background hover:bg-hover-background"
          >Quarterly plan</BreadcrumbPage
        ></BreadcrumbItem
      ></BreadcrumbList
    ></Breadcrumb
  >
</template>

// apps/angular-app/src/pages/breadcrumb/capsule-breadcrumb.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
} from '@fex-design/angular/primitive/breadcrumb'
@Component({
  selector: 'app-breadcrumb-capsule',
  standalone: true,
  imports: [RouterLink, Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage],
  templateUrl: './capsule-breadcrumb.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CapsuleBreadcrumbComponent {}

<fex-breadcrumb class="p-1"
  ><fex-breadcrumb-list
    class="w-max items-center gap-0 rounded-full text-muted-foreground overflow-hidden"
    ><fex-breadcrumb-item class="group z-[3] -mr-4.5"
      ><a
        fexBreadcrumbLink
        class="inline-flex items-center gap-0.5 px-4 border border-border rounded-full bg-muted-background hover:bg-hover-background group-not-first:pl-6"
        routerLink="/"
        >Workspace</a
      ></fex-breadcrumb-item
    ><fex-breadcrumb-item class="group z-[2] -mr-4.5"
      ><a
        fexBreadcrumbLink
        class="inline-flex items-center gap-0.5 px-4 pl-6 border border-border rounded-full bg-muted-background hover:bg-hover-background"
        routerLink="/projects"
        >Projects</a
      ></fex-breadcrumb-item
    ><fex-breadcrumb-item class="group z-[1]"
      ><fex-breadcrumb-page
        class="inline-flex items-center gap-0.5 px-4 pl-6 border border-border rounded-full bg-muted-background hover:bg-hover-background"
        >Quarterly plan</fex-breadcrumb-page
      ></fex-breadcrumb-item
    ></fex-breadcrumb-list
  ></fex-breadcrumb
>
