// packages/@fex-design/components/vue/src/ui/radio/radio.vue
<script setup lang="ts">
import {
  radioItemClassName,
  radioLabelClassName,
  type RadioStyleProps,
} from '@fex-design/components-styles/radio'
import { cn } from '@fex-design/utils'
import { computed, useAttrs, useId, type PropType, type StyleValue } from 'vue'
import { Radio as PrimitiveRadio, type RadioValue } from '@fex-design/vue/primitive/radio/radio'
defineOptions({ name: 'Radio', inheritAttrs: false })
const props = defineProps({
  value: { type: [String, Number] as PropType<RadioValue>, required: true },
  disabled: { type: Boolean, default: false },
  size: String as PropType<RadioStyleProps['size']>,
  classNames: Object as PropType<{ root?: string; control?: string; label?: string }>,
  styles: Object as PropType<{ root?: StyleValue; control?: StyleValue; label?: StyleValue }>,
})
const attrs = useAttrs()
const generatedId = useId()
const controlId = computed(() => (attrs.id as string | undefined) ?? generatedId)
const controlAttrs = computed(() => {
  const { class: _class, style: _style, id: _id, ...rest } = attrs
  return rest
})
</script>
<template>
  <div
    :class="cn(radioItemClassName, attrs.class as string | undefined, props.classNames?.root)"
    :style="[attrs.style as StyleValue, props.styles?.root]"
  >
    <PrimitiveRadio
      v-bind="controlAttrs"
      :id="controlId"
      :value="props.value"
      :disabled="props.disabled"
      :size="props.size"
      :class="props.classNames?.control"
      :style="props.styles?.control"
    />
    <label
      v-if="$slots.default"
      :for="controlId"
      :class="cn(radioLabelClassName, props.classNames?.label)"
      :style="props.styles?.label"
      ><slot
    /></label>
  </div>
</template>

// packages/@fex-design/components/svelte/src/ui/radio/radio.svelte
<script module lang="ts">
  let radioId = 0;
</script>

<script lang="ts">
  import {
    radioItemClassName,
    radioLabelClassName,
    type RadioStyleProps,
  } from "@fex-design/components-styles/radio";
  import { cn } from "@fex-design/utils";
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import PrimitiveRadio from '@fex-design/svelte/primitive/radio/radio.svelte';
  import type { RadioValue } from '@fex-design/svelte/primitive/radio/context';
  interface Props extends Omit<
    HTMLButtonAttributes,
    "children" | "type" | "value"
  > {
    value: RadioValue;
    size?: RadioStyleProps["size"];
    children?: Snippet;
    classNames?: { root?: string; control?: string; label?: string };
    styles?: { root?: string; control?: string; label?: string };
  }
  let {
    id = `radio-${++radioId}`,
    value,
    disabled,
    size,
    children,
    class: className,
    style,
    classNames,
    styles,
    ...rest
  }: Props = $props();
</script>

<div
  class={cn(radioItemClassName, className, classNames?.root)}
  style={[style, styles?.root].filter(Boolean).join(";")}
>
  <PrimitiveRadio
    {...rest}
    {id}
    {value}
    {disabled}
    {size}
    class={classNames?.control}
    style={styles?.control}
  />
  {#if children}
    <label
      for={id}
      class={cn(radioLabelClassName, classNames?.label)}
      style={styles?.label}
    >
      {@render children()}
    </label>
  {/if}
</div>
