// apps/solid-app/src/pages/Drawer/placement-demo.tsx
import { createSignal } from 'solid-js'
import {
  Drawer,
  DrawerBody,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerMask,
  DrawerPortal,
  DrawerTrigger,
} from '@fex-design/solid/primitive/drawer'
import { RadioGroup, Radio } from '@fex-design/solid/primitive/radio'
import { Button } from '@fex-design/solid/ui/button'
export function PlacementDemo() {
  const [placement, setPlacement] = createSignal<'top' | 'right' | 'bottom' | 'left'>('right')
  return (
    <div class="space-y-3">
      <RadioGroup
        value={placement()}
        orientation="horizontal"
        onValueChange={(value) => setPlacement(value as typeof placement)}
      >
        {(['top', 'right', 'bottom', 'left'] as const).map((item) => (
          <label class="inline-flex cursor-pointer items-center gap-2">
            <Radio value={item} />
            <span>{item}</span>
          </label>
        ))}
      </RadioGroup>
      <Drawer placement={placement()}>
        <DrawerTrigger>
          {(slot) => (
            <Button {...slot.props} ref={slot.ref}>
              Open {placement()}
            </Button>
          )}
        </DrawerTrigger>
        <DrawerPortal>
          <DrawerMask />
          <DrawerContent aria-label="Placement drawer">
            <DrawerHeader>
              {placement()}
              <DrawerClose />
            </DrawerHeader>
            <DrawerBody>Direction demo.</DrawerBody>
          </DrawerContent>
        </DrawerPortal>
      </Drawer>
    </div>
  )
}

// apps/vue-app/src/pages/Drawer/placement-demo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { DrawerRoot, DrawerTrigger, DrawerPortal, DrawerMask, DrawerContent, DrawerHeader, DrawerBody, DrawerClose } from '@fex-design/vue/primitive/drawer'
import { RadioGroup, Radio } from '@fex-design/vue/primitive/radio'
import { Button } from '@fex-design/vue/ui/button'
const placement = ref<'top' | 'right' | 'bottom' | 'left'>('right')
</script>
<template>
  <div class="space-y-3">
    <RadioGroup :value="placement" orientation="horizontal" @value-change="value => placement = value as typeof placement">
      <label v-for="item in ['top','right','bottom','left']" :key="item" class="inline-flex items-center gap-2 text-sm text-foreground"><Radio :value="item" /><span>{{ item }}</span></label>
    </RadioGroup>
    <DrawerRoot :placement="placement"><DrawerTrigger v-slot="{ props }"><Button v-bind="props">Open {{ placement }}</Button></DrawerTrigger><DrawerPortal><DrawerMask/><DrawerContent :aria-label="`${placement} drawer`"><DrawerHeader>{{ placement }} drawer<DrawerClose /></DrawerHeader><DrawerBody>Direction is controlled by the radio group.</DrawerBody></DrawerContent></DrawerPortal></DrawerRoot>
  </div>
</template>
