// apps/solid-app/src/pages/Drawer/preset-demo.tsx
import { For } from 'solid-js'
import {
  Drawer,
  DrawerBody,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerMask,
  DrawerPortal,
  DrawerTrigger,
} from '@fex-design/solid/primitive/drawer'
import { Button } from '@fex-design/solid/ui/button'
export function PresetDemo() {
  return (
    <div class="flex gap-2">
      <For each={['sm', 'md', 'lg', 'xl', 'full'] as const}>
        {(size) => (
          <Drawer size={size}>
            <DrawerTrigger>
              {(slot) => (
                <Button {...slot.props} ref={slot.ref} variant="outline">
                  {size}
                </Button>
              )}
            </DrawerTrigger>
            <DrawerPortal>
              <DrawerMask />
              <DrawerContent>
                <DrawerHeader>
                  {size}
                  <DrawerClose />
                </DrawerHeader>
                <DrawerBody>Preset width: {size}</DrawerBody>
              </DrawerContent>
            </DrawerPortal>
          </Drawer>
        )}
      </For>
    </div>
  )
}

// apps/vue-app/src/pages/Drawer/preset-demo.vue
<script setup lang="ts">
import {
  DrawerRoot,
  DrawerTrigger,
  DrawerPortal,
  DrawerMask,
  DrawerContent,
  DrawerHeader,
  DrawerBody,
  DrawerClose,
} from '@fex-design/vue/primitive/drawer'
import { Button } from '@fex-design/vue/ui/button'
const sizes = ['sm', 'md', 'lg', 'xl', 'full'] as const
</script>
<template>
  <div class="flex gap-2">
    <DrawerRoot v-for="size in sizes" :key="size" :size="size"
      ><DrawerTrigger v-slot="{ props }"
        ><Button v-bind="props" variant="outline">{{ size }}</Button></DrawerTrigger
      ><DrawerPortal
        ><DrawerMask /><DrawerContent :size="size"
          ><DrawerHeader>{{ size }}<DrawerClose /></DrawerHeader
          ><DrawerBody>Preset width: {{ size }}</DrawerBody></DrawerContent
        ></DrawerPortal
      ></DrawerRoot
    >
  </div>
</template>
