// apps/angular-app/src/pages/timeline/basic-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  Timeline,
  TimelineContent,
  TimelineIndicator,
  TimelineItem,
  TimelineOpposite,
} from '@fex-design/angular/primitive/timeline'
import { Card } from '@fex-design/angular/ui/card'
@Component({
  selector: 'fex-timeline-basic-demo',
  standalone: true,
  imports: [Card, Timeline, TimelineItem, TimelineIndicator, TimelineContent, TimelineOpposite],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block' },
  templateUrl: './basic-demo.component.html',
})
export class BasicDemoComponent {}

<fex-card
  title="Basic"
  description="A semantic ordered list with content, time and connecting lines."
  ><fex-timeline aria-label="Release history"
    ><fex-timeline-item status="completed"
      ><fex-timeline-opposite>09:00</fex-timeline-opposite
      ><fex-timeline-indicator /><fex-timeline-content
        ><strong>Build completed</strong>
        <p class="text-muted-foreground">Artifacts are ready.</p></fex-timeline-content
      ></fex-timeline-item
    ><fex-timeline-item status="current"
      ><fex-timeline-opposite>09:20</fex-timeline-opposite
      ><fex-timeline-indicator /><fex-timeline-content
        ><strong>Deploying</strong>
        <p class="text-muted-foreground">Rolling out to production.</p></fex-timeline-content
      ></fex-timeline-item
    ><fex-timeline-item status="pending"
      ><fex-timeline-opposite>Next</fex-timeline-opposite
      ><fex-timeline-indicator /><fex-timeline-content
        ><strong>Verification</strong>
        <p class="text-muted-foreground">Waiting for deployment.</p></fex-timeline-content
      ></fex-timeline-item
    ></fex-timeline
  ></fex-card
>

// apps/vue-app/src/pages/Timeline/basic-demo.vue
<script setup lang="ts">
import {
  Timeline,
  TimelineContent,
  TimelineIndicator,
  TimelineItem,
  TimelineOpposite,
} from '@fex-design/vue/primitive/timeline'
import Card from '@fex-design/vue/ui/card'
</script>
<template>
  <Card title="Basic" description="A semantic ordered list with content, time and connecting lines."
    ><Timeline aria-label="Release history"
      ><TimelineItem status="completed"
        ><TimelineOpposite>09:00</TimelineOpposite><TimelineIndicator /><TimelineContent
          ><strong>Build completed</strong>
          <p class="text-muted-foreground">Artifacts are ready.</p></TimelineContent
        ></TimelineItem
      ><TimelineItem status="current"
        ><TimelineOpposite>09:20</TimelineOpposite><TimelineIndicator /><TimelineContent
          ><strong>Deploying</strong>
          <p class="text-muted-foreground">Rolling out to production.</p></TimelineContent
        ></TimelineItem
      ><TimelineItem status="pending"
        ><TimelineOpposite>Next</TimelineOpposite><TimelineIndicator /><TimelineContent
          ><strong>Verification</strong>
          <p class="text-muted-foreground">Waiting for deployment.</p></TimelineContent
        ></TimelineItem
      ></Timeline
    ></Card
  >
</template>
