// packages/@fex-design/react/src/primitive/button/examples/effects.tsx
import { PlusIcon } from '@fex-design/react/icon/plus'
import { Button, ButtonIcon } from '@fex-design/react/primitive/button'
import { buttonClassName } from '@fex-design/styles/button'

const effects = [
  'expand-icon',
  'ring-hover',
  'shine-hover',
  'gooey-start',
  'gooey-end',
  'underline',
  'hover-underline',
  'press',
] as const

export function EffectsExample() {
  return (
    <div className="flex flex-wrap items-center gap-3">
      {effects.map((effect) => (
        <Button key={effect} className={buttonClassName({ effect })} data-effect={effect}>
          <ButtonIcon>
            <PlusIcon />
          </ButtonIcon>
          {effect}
        </Button>
      ))}
    </div>
  )
}

// packages/@fex-design/vue/src/primitive/button/examples/effects.vue
<script setup lang="ts">
import { PlusIcon } from '@fex-design/vue/icon/plus'
import { Button, ButtonIcon } from '@fex-design/vue/primitive/button'
import { buttonClassName } from '@fex-design/styles/button'
const effectNames = [
  'expand-icon',
  'ring-hover',
  'shine-hover',
  'gooey-start',
  'gooey-end',
  'underline',
  'hover-underline',
  'press',
] as const
const effects = effectNames.map((effect) => ({ effect, className: buttonClassName({ effect }) }))
</script>
<template>
  <div class="flex flex-wrap items-center gap-3">
    <Button
      v-for="item in effects"
      :key="item.effect"
      :class="item.className"
      :data-effect="item.effect"
    >
      <ButtonIcon><PlusIcon /></ButtonIcon>{{ item.effect }}
    </Button>
  </div>
</template>
