// packages/@fex-design/components/solid/src/primitive/input/input-addon-after.tsx
import { inputAddonAfterClassName } from "@fex-design/components-styles/input"
import { cn } from "@fex-design/utils"
import type { JSX, ParentProps } from "solid-js"

export type InputAddonAfterProps = ParentProps<JSX.HTMLAttributes<HTMLSpanElement>>

export function InputAddonAfter(props: InputAddonAfterProps) {
  return (
    <span {...props} data-slot="input-addon-after" class={cn(inputAddonAfterClassName, props.class)}>
      {props.children}
    </span>
  )
}

// packages/@fex-design/components/svelte/src/primitive/input/input-addon-after.svelte
<script lang="ts">
  import { inputAddonAfterClassName } from "@fex-design/components-styles/input";
  import { cn } from "@fex-design/utils";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  interface Props extends Omit<HTMLAttributes<HTMLSpanElement>, "class"> {
    class?: string;
    children?: Snippet;
  }
  let { class: className, children, ...rest }: Props = $props();
</script>

<span
  {...rest}
  data-slot="input-addon-after"
  class={cn(inputAddonAfterClassName, className)}>{@render children?.()}</span
>
