// packages/@fex-design/vue/src/ui/skeleton/examples/image.vue
<script setup lang="ts">import { SkeletonImage, SkeletonText } from '@fex-design/vue/ui/skeleton'</script>
<template><div class="flex w-full max-w-xl items-start gap-4"><SkeletonImage class="h-28 w-40 shrink-0" /><div class="grid min-w-0 flex-1 gap-3"><SkeletonText class="w-2/5" /><SkeletonText /><SkeletonText /><SkeletonText class="w-4/5" /></div></div></template>

// packages/@fex-design/svelte/src/ui/skeleton/examples/image.svelte
<script lang="ts">import { SkeletonImage, SkeletonText } from '@fex-design/svelte/ui/skeleton'</script>
<div class="flex w-full max-w-xl items-start gap-4"><SkeletonImage class="h-28 w-40 shrink-0" /><div class="grid min-w-0 flex-1 gap-3"><SkeletonText class="w-2/5" /><SkeletonText /><SkeletonText /><SkeletonText class="w-4/5" /></div></div>
