// packages/@fex-design/components/solid/src/primitives/create-data-table.ts
import { createDataTableController } from '@fex-design/core/data-table/create-data-table-controller'
import type { DataTableController } from '@fex-design/core/data-table/create-data-table-controller'
import type { RowData, Table, TableFeatures, TableOptions } from '@tanstack/table-core'
import type { Accessor } from 'solid-js'
import { createCoreStoreSignal } from './create-core-store-signal'

export type SolidDataTable<TFeatures extends TableFeatures, TData extends RowData> = Table<
  TFeatures,
  TData
> & {
  readonly dataTableSnapshot: Accessor<
    ReturnType<DataTableController<TFeatures, TData>['getSnapshot']>
  >
  setDataTableOptions: (options: TableOptions<TFeatures, TData>) => void
}

export function createDataTable<TFeatures extends TableFeatures, TData extends RowData>(
  options: TableOptions<TFeatures, TData>,
): SolidDataTable<TFeatures, TData> {
  const controller = createDataTableController(options)
  const dataTableSnapshot = createCoreStoreSignal(controller)

  return Object.assign(controller.table, {
    dataTableSnapshot,
    setDataTableOptions: controller.setOptions,
  })
}

// packages/@fex-design/components/angular/src/signals/create-data-table.ts
import { createDataTableController } from '@fex-design/core/data-table/create-data-table-controller'
import type { DataTableControllerSnapshot } from '@fex-design/core/data-table/create-data-table-controller'
import type { RowData, Table, TableFeatures, TableOptions } from '@tanstack/table-core'
import type { Signal } from '@angular/core'

import { createCoreStoreSignal } from './core-store-signal'

export type AngularDataTable<
  TFeatures extends TableFeatures = TableFeatures,
  TData extends RowData = RowData,
> = Table<TFeatures, TData> & {
  readonly dataTableSnapshot: Signal<DataTableControllerSnapshot<TFeatures, TData>>
  setDataTableOptions: (options: TableOptions<TFeatures, TData>) => void
}

export function createDataTable<TFeatures extends TableFeatures, TData extends RowData>(
  options: TableOptions<TFeatures, TData>,
): AngularDataTable<TFeatures, TData> {
  const controller = createDataTableController(options)
  return Object.assign(controller.table, {
    dataTableSnapshot: createCoreStoreSignal(controller),
    setDataTableOptions: controller.setOptions,
  })
}
