// apps/angular-app/src/pages/cascader/sync-value-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { regionOptions } from './data'
import { SimpleCascaderDemo } from './simple-demo.component'
export
@Component({
  selector: 'fex-cascader-sync-value-demo',
  standalone: true,
  imports: [SimpleCascaderDemo],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template:
    '<fex-cascader-simple-demo title="Synchronous value display" description="Options and initial path resolve together." [options]="options" [defaultValue]="value" />',
})
class SyncValueDemo {
  readonly options = regionOptions
  readonly value = ['jiangsu', 'suzhou', 'industrial-park', 'loufeng']
}

// apps/solid-app/src/pages/Cascader/sync-value-demo.tsx
import { regionOptions } from './data'
import { DemoCascader } from './demo-cascader'
import { DemoSection } from './demo-section'
export function SyncValueDemo() {
  return (
    <DemoSection
      title="Synchronous value display"
      description="Options and initial path resolve together."
    >
      <DemoCascader
        options={regionOptions}
        defaultValue={['jiangsu', 'suzhou', 'industrial-park', 'loufeng']}
      />
    </DemoSection>
  )
}
