// packages/@fex-design/components/react/src/ui/spinner/spinner.tsx
import type { SpinnerContainerOptions, SpinnerOptions } from '@fex-design/core/spinner/types'
import { spinnerContainerClassName } from '@fex-design/components-styles/spinner'
import { cn } from '@fex-design/utils'
import type { ComponentProps, CSSProperties, ReactNode } from 'react'
import {
  Spinner,
  SpinnerContainer as PrimitiveSpinnerContainer,
  SpinnerOverlay,
  SpinnerText,
} from '@fex-design/react/primitive/spinner/spinner'

export { Spinner }

export interface SpinnerContainerProps
  extends
    Omit<ComponentProps<'div'>, 'children'>,
    SpinnerContainerOptions<ReactNode, CSSProperties>,
    SpinnerOptions {
  children?: ReactNode
}

export function SpinnerContainer({
  children,
  className,
  indicator,
  classNames,
  size = 'md',
  styles,
  spinning,
  text,
  ...props
}: SpinnerContainerProps) {
  if (spinning === undefined) {
    return (
      <Spinner size={size} className={cn(className, classNames?.spinner)} style={styles?.spinner}>
        {indicator}
      </Spinner>
    )
  }
  return (
    <PrimitiveSpinnerContainer
      {...props}
      aria-busy={spinning}
      className={cn(spinnerContainerClassName, className, classNames?.root)}
      style={styles?.root}
    >
      {children}
      {spinning ? (
        <SpinnerOverlay
          className={cn(classNames?.overlay, text && 'flex-col')}
          style={styles?.overlay}
        >
          <Spinner size={size} className={classNames?.spinner} style={styles?.spinner}>
            {indicator}
          </Spinner>
          {text ? (
            <SpinnerText className={classNames?.text} style={styles?.text}>
              {text}
            </SpinnerText>
          ) : null}
        </SpinnerOverlay>
      ) : null}
    </PrimitiveSpinnerContainer>
  )
}

// packages/@fex-design/components/angular/src/ui/spinner/spinner.ts
import { ChangeDetectionStrategy, Component, input, type TemplateRef } from '@angular/core'
import type { SpinnerClassNames, SpinnerSize, SpinnerStyles } from '@fex-design/core/spinner/types'
import { spinnerContainerClassName } from '@fex-design/components-styles/spinner'
import { cn } from '@fex-design/utils'
import { Spinner, SpinnerOverlay, SpinnerText } from '@fex-design/angular/primitive/spinner'
import { createHostClassName } from '@fex-design/angular/signals/host-class'

@Component({
  selector: 'div[spinnerContainer]',
  standalone: true,
  imports: [Spinner, SpinnerOverlay, SpinnerText],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    '[style]': 'styles().root',
    '[attr.aria-busy]': 'spinning() ?? null',
    'data-slot': 'spinner-container',
  },
  templateUrl: './spinner.html',
})
export class SpinnerContainer {
  readonly spinning = input<boolean | undefined>()
  readonly size = input<SpinnerSize>('md')
  readonly text = input<string | undefined>()
  readonly indicator = input<TemplateRef<unknown> | undefined>()
  readonly classNames = input<SpinnerClassNames>({})
  readonly styles = input<SpinnerStyles<string>>({})
  protected readonly hostClassName = createHostClassName(() =>
    cn(spinnerContainerClassName, this.classNames().root),
  )
  protected readonly overlayClassName = () =>
    cn(this.classNames().overlay, this.text() && 'flex-col')
}

export { Spinner }
