// packages/@fex-design/components/vue/src/primitive/input-number/input-number-decrement.vue
<script setup lang="ts">
import { inputNumberDecrementClassName } from '@fex-design/components-styles/input-number'
import { cn } from '@fex-design/utils'
import { inject } from 'vue'
import { Button } from '../button'
import MinusIcon from '@fex-design/vue/icons/minus-icon.vue'
import { inputNumberContextKey } from './context'
defineOptions({ name: 'InputNumberDecrement' })
const props = defineProps<{ class?: string; disabled?: boolean }>()
const inputNumber = inject(inputNumberContextKey)
if (!inputNumber) throw new Error('InputNumberDecrement must be used inside InputNumberRoot.')
</script>
<template>
  <Button
    variant="text"
    data-slot="input-number-decrement"
    data-action="decrement"
    aria-label="Decrease value"
    :disabled="props.disabled || !inputNumber.canDecrement.value"
    :class="cn(inputNumberDecrementClassName, props.class)"
    @pointerdown.prevent
    @click="inputNumber.decrement"
    ><slot><MinusIcon /></slot
  ></Button>
</template>

// packages/@fex-design/components/angular/src/primitive/input-number/input-number-decrement.ts
import { ChangeDetectionStrategy, Component, HostListener, inject } from '@angular/core'
import { inputNumberDecrementClassName } from '@fex-design/components-styles/input-number'
import { buttonClassName } from '@fex-design/components-styles/button'
import { cn } from '@fex-design/utils'
import { MinusIcon } from '@fex-design/angular/icons/minus'
import { createHostClassName } from '@fex-design/angular/signals/host-class'
import { InputNumberRoot } from './input-number-root'
@Component({
  selector: 'button[inputNumberDecrement]',
  standalone: true,
  imports: [MinusIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    type: 'button',
    'data-slot': 'input-number-decrement',
    'data-action': 'decrement',
    'aria-label': 'Decrease value',
    '[disabled]': '!root.inputNumber.canDecrement()',
  },
  template: '<ng-content><minus-icon /></ng-content>',
})
export class InputNumberDecrement {
  readonly root = inject(InputNumberRoot)
  protected readonly hostClassName = createHostClassName(() =>
    cn(buttonClassName({ variant: 'text' }), inputNumberDecrementClassName),
  )
  @HostListener('pointerdown', ['$event']) pointerdown(event: PointerEvent) {
    event.preventDefault()
  }
  @HostListener('click', ['$event']) click(event: MouseEvent) {
    if (!event.defaultPrevented) this.root.inputNumber.decrement(event)
  }
}
