// packages/@fex-design/components/react/src/primitive/input-otp/input-otp-separator.tsx
import { inputOTPSeparatorClassName } from "@fex-design/components-styles/input-otp"
import { cn } from "@fex-design/utils"
import type { HTMLAttributes } from "react"

export type InputOTPSeparatorProps = HTMLAttributes<HTMLSpanElement>

export function InputOTPSeparator({ className, children, ...props }: InputOTPSeparatorProps) {
  return (
    <span
      {...props}
      aria-hidden="true"
      data-slot="input-otp-separator"
      className={cn(inputOTPSeparatorClassName, className)}
    >
      {children ?? "–"}
    </span>
  )
}

// packages/@fex-design/components/solid/src/primitive/input-otp/input-otp-separator.tsx
import { inputOTPSeparatorClassName } from "@fex-design/components-styles/input-otp"
import { cn } from "@fex-design/utils"
import { splitProps, type JSX, type ParentProps } from "solid-js"

export type InputOTPSeparatorProps = ParentProps<JSX.HTMLAttributes<HTMLSpanElement>>

export function InputOTPSeparator(props: InputOTPSeparatorProps) {
  const [local, rest] = splitProps(props, ["class", "children"])
  return (
    <span
      {...rest}
      aria-hidden="true"
      data-slot="input-otp-separator"
      class={cn(inputOTPSeparatorClassName, local.class)}
    >
      {local.children ?? "–"}
    </span>
  )
}
