// apps/svelte-app/src/routes/time-picker/demo-time-picker.svelte
<script lang="ts">
  import { analyzeTimeFormat } from "@fex-design/core/date/utils";
  import CalendarIcon from "@fex-design/svelte/icon/calendar";
  import ClockIcon from "@fex-design/svelte/icon/clock";
  import {
    TimePickerContent,
    TimePickerHourColumn,
    TimePickerMinuteColumn,
    TimePickerPanel,
    TimePickerPeriodColumn,
    TimePickerRoot,
    TimePickerSecondColumn,
    TimePickerTrigger,
    type DisabledTime,
    type TimeValue,
  } from "@fex-design/svelte/primitive/time-picker";
  import { Button } from "@fex-design/svelte/ui/button";
  let {
    value,
    defaultValue = null,
    onchange,
    use12Hours = false,
    format,
    step,
    disabledTime,
    disabled = false,
    invalid = false,
    prefix,
    calendarSuffix = false,
    panelExtra = false,
  }: {
    value?: TimeValue | null;
    defaultValue?: TimeValue | null;
    onchange?: (value: TimeValue | null) => void;
    use12Hours?: boolean;
    format?: string;
    step?: { hour?: number; minute?: number; second?: number };
    disabledTime?: DisabledTime;
    disabled?: boolean;
    invalid?: boolean;
    prefix?: string;
    calendarSuffix?: boolean;
    panelExtra?: boolean;
  } = $props();
  let open = $state(false);
  const pattern = $derived(format ?? (use12Hours ? "hh:mm:ss A" : "HH:mm:ss"));
  const columns = $derived(analyzeTimeFormat(pattern, use12Hours).columns);
</script>

<TimePickerRoot
  {value}
  {defaultValue}
  {use12Hours}
  {disabled}
  {disabledTime}
  format={pattern}
  {open}
  onOpenChange={(next) => (open = next)}
  onchange={(next) => onchange?.(next)}
  placement="bottomLeft"
>
  <TimePickerTrigger class="w-56" {invalid}>
    {#snippet prefix()}{#if prefix}<span>{prefix}</span>{/if}{/snippet}
    {#snippet suffix()}{#if calendarSuffix}<CalendarIcon
          class="size-4"
        />{:else}<ClockIcon class="size-4" />{/if}{/snippet}
  </TimePickerTrigger>
  <TimePickerContent>
    <TimePickerPanel
      >{#each columns as column (column.unit)}{#if column.unit === "hour"}<TimePickerHourColumn
            step={step?.hour}
          />{:else if column.unit === "minute"}<TimePickerMinuteColumn
            step={step?.minute}
          />{:else if column.unit === "second"}<TimePickerSecondColumn
            step={step?.second}
          />{:else}<TimePickerPeriodColumn />{/if}{/each}</TimePickerPanel
    >
    {#if panelExtra}<div class="border-t border-border p-1.5 text-sm">
        <button type="button" class="text-primary">选择当前时间</button>
      </div>{/if}
    <div class="flex justify-end border-t border-border p-1.5">
      <Button size="sm" variant="ghost" onclick={() => (open = false)}
        >确定</Button
      >
    </div>
  </TimePickerContent>
</TimePickerRoot>

// apps/react-app/src/pages/TimePicker/demo-time-picker.tsx
import { analyzeTimeFormat } from '@fex-design/core/date/utils'
import {
  TimePickerContent,
  TimePickerHourColumn,
  TimePickerMinuteColumn,
  TimePickerPanel,
  TimePickerPeriodColumn,
  TimePickerRoot,
  TimePickerSecondColumn,
  TimePickerTrigger,
  type DisabledTime,
  type TimeValue,
} from '@fex-design/react/primitive/time-picker'
import { Button } from '@fex-design/react/ui/button'
import { useState, type ReactNode } from 'react'

export interface DemoTimePickerProps {
  value?: TimeValue | null
  defaultValue?: TimeValue | null
  onChange?: (value: TimeValue | null) => void
  use12Hours?: boolean
  format?: string
  step?: { hour?: number; minute?: number; second?: number }
  disabledTime?: DisabledTime
  disabled?: boolean
  invalid?: boolean
  prefix?: ReactNode
  suffix?: ReactNode
  panelExtra?: ReactNode
}

export function DemoTimePicker({
  value,
  defaultValue = null,
  onChange,
  use12Hours = false,
  format,
  step,
  disabledTime,
  disabled = false,
  invalid = false,
  prefix,
  suffix,
  panelExtra,
}: DemoTimePickerProps) {
  const [open, setOpen] = useState(false)
  const resolvedFormat = format ?? (use12Hours ? 'hh:mm:ss A' : 'HH:mm:ss')
  const columns = analyzeTimeFormat(resolvedFormat, use12Hours).columns

  return (
    <TimePickerRoot
      value={value}
      defaultValue={defaultValue}
      onChange={(next) => onChange?.(next)}
      open={open}
      onOpenChange={setOpen}
      format={resolvedFormat}
      use12Hours={use12Hours}
      disabled={disabled}
      disabledTime={disabledTime}
      placement="bottomLeft"
    >
      <TimePickerTrigger
        className="w-56"
        invalid={invalid}
        prefix={prefix}
        suffix={suffix}
        inputProps={{ 'aria-label': 'Time' }}
      />
      <TimePickerContent>
        <TimePickerPanel>
          {columns.map((column) => {
            if (column.unit === 'hour') return <TimePickerHourColumn key="hour" step={step?.hour} />
            if (column.unit === 'minute')
              return <TimePickerMinuteColumn key="minute" step={step?.minute} />
            if (column.unit === 'second')
              return <TimePickerSecondColumn key="second" step={step?.second} />
            return <TimePickerPeriodColumn key="period" />
          })}
        </TimePickerPanel>
        {panelExtra ? (
          <div className="border-t border-border p-1.5 text-sm">{panelExtra}</div>
        ) : null}
        <div className="flex justify-end border-t border-border p-1.5">
          <Button size="sm" variant="ghost" onClick={() => setOpen(false)}>
            确定
          </Button>
        </div>
      </TimePickerContent>
    </TimePickerRoot>
  )
}
