// packages/@fex-design/components/react/src/primitive/calendar/calendar-week-header.tsx
import type { ComponentProps } from 'react'
import { useCalendarContext } from './calendar-context'

export interface CalendarWeekHeaderProps extends ComponentProps<'div'> {
  labels?: readonly string[]
}

export function CalendarWeekHeader({
  labels = ['日', '一', '二', '三', '四', '五', '六'],
  className,
  ...props
}: CalendarWeekHeaderProps) {
  const context = useCalendarContext('CalendarWeekHeader')
  const orderedLabels = labels.map((_, index) => labels[(index + context.weekStartsOn) % 7] ?? '')

  return (
    <div {...props} data-slot="calendar-week-header" className={className}>
      {orderedLabels.map((label) => (
        <div key={label} data-slot="calendar-week-head">
          {label}
        </div>
      ))}
    </div>
  )
}

// packages/@fex-design/components/vue/src/primitive/calendar/calendar-week-header.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useCalendarContext } from './context'

const props = withDefaults(defineProps<{ labels?: readonly string[] }>(), {
  labels: () => ['日', '一', '二', '三', '四', '五', '六'],
})

const context = useCalendarContext('CalendarWeekHeader')

const orderedLabels = computed(() =>
  props.labels.map((_, index) => props.labels[(index + context.weekStartsOn.value) % 7] ?? ''),
)
</script>

<template>
  <div data-slot="calendar-week-header">
    <div v-for="label in orderedLabels" :key="label" data-slot="calendar-week-head">
      {{ label }}
    </div>
  </div>
</template>
