// packages/@fex-design/components/react/src/primitive/calendar/calendar-navigation-button.tsx
import { addDate, subtractDate } from '@fex-design/core/calendar'
import type { ComponentProps } from 'react'
import { useCalendarContext } from './calendar-context'

export type CalendarNavigationAction =
  | 'previous-year'
  | 'previous-month'
  | 'next-month'
  | 'next-year'
  | 'previous-panel'
  | 'next-panel'

export interface CalendarNavigationButtonProps extends ComponentProps<'button'> {
  action: CalendarNavigationAction
}

export function CalendarNavigationButton({
  action,
  type = 'button',
  onClick,
  children,
  ...props
}: CalendarNavigationButtonProps) {
  const context = useCalendarContext('CalendarNavigationButton')

  function runAction() {
    if (action === 'previous-year') {
      context.setViewDate(subtractDate(context.viewDate, { years: 1 }))
      return
    }
    if (action === 'previous-month') {
      context.setViewDate(subtractDate(context.viewDate, { months: 1 }))
      return
    }
    if (action === 'next-month') {
      context.setViewDate(addDate(context.viewDate, { months: 1 }))
      return
    }
    if (action === 'next-year') {
      context.setViewDate(addDate(context.viewDate, { years: 1 }))
      return
    }
    if (action === 'previous-panel') {
      context.setViewDate(
        context.panel === 'date'
          ? subtractDate(context.viewDate, { months: 1 })
          : subtractDate(context.viewDate, { years: 1 }),
      )
      return
    }
    context.setViewDate(
      context.panel === 'date'
        ? addDate(context.viewDate, { months: 1 })
        : addDate(context.viewDate, { years: 1 }),
    )
  }

  return (
    <button
      {...props}
      type={type}
      data-slot="calendar-navigation-button"
      data-action={action}
      onClick={(event) => {
        onClick?.(event)
        if (event.defaultPrevented) return
        runAction()
      }}
    >
      {children}
    </button>
  )
}

// packages/@fex-design/components/vue/src/primitive/calendar/calendar-navigation-button.vue
<script setup lang="ts">
import { addDate, subtractDate } from '@fex-design/core/calendar'
import { useCalendarContext } from './context'

const props = defineProps<{
  action:
    | 'previous-year'
    | 'previous-month'
    | 'next-month'
    | 'next-year'
    | 'previous-panel'
    | 'next-panel'
}>()

const context = useCalendarContext('CalendarNavigationButton')

function runAction() {
  if (props.action === 'previous-year')
    context.setViewDate(subtractDate(context.viewDate.value, { years: 1 }))
  if (props.action === 'previous-month')
    context.setViewDate(subtractDate(context.viewDate.value, { months: 1 }))
  if (props.action === 'next-month')
    context.setViewDate(addDate(context.viewDate.value, { months: 1 }))
  if (props.action === 'next-year')
    context.setViewDate(addDate(context.viewDate.value, { years: 1 }))
  if (props.action === 'previous-panel') {
    context.setViewDate(
      context.panel.value === 'date'
        ? subtractDate(context.viewDate.value, { months: 1 })
        : subtractDate(context.viewDate.value, { years: 1 }),
    )
  }
  if (props.action === 'next-panel') {
    context.setViewDate(
      context.panel.value === 'date'
        ? addDate(context.viewDate.value, { months: 1 })
        : addDate(context.viewDate.value, { years: 1 }),
    )
  }
}
</script>

<template>
  <button
    type="button"
    data-slot="calendar-navigation-button"
    :data-action="action"
    @click="runAction"
  >
    <slot />
  </button>
</template>
