// packages/@fex-design/react/src/primitive/cascader/cascader-context.ts
import type {
  CascaderController,
  CascaderNode,
  CascaderOption,
  CascaderSnapshot,
} from '@fex-design/core/cascader/types'
import { createContext, use, type ReactNode } from 'react'

export interface CascaderContextValue {
  controller: CascaderController
  snapshot: CascaderSnapshot
  multiple: boolean
  expandTrigger: 'click' | 'hover'
  showSearch: boolean
  clearable: boolean
  disabled: boolean
  loading: boolean
  status?: 'error' | 'warning' | undefined
  placeholder?: string | undefined
  selectedPaths: readonly (readonly CascaderNode[])[]
  displayRender?:
    | ((labels: readonly string[], path: readonly CascaderOption[]) => ReactNode)
    | undefined
}

export const CascaderContext = createContext<CascaderContextValue | null>(null)

export function useCascader() {
  const context = use(CascaderContext)
  if (!context) throw new Error('Cascader parts must be used inside CascaderRoot.')
  return context
}

// packages/@fex-design/components/solid/src/primitive/cascader/cascader-context.ts
import type { createCascaderController } from '@fex-design/core/cascader/create-cascader-controller'
import type { CascaderNode, CascaderOption } from '@fex-design/core/cascader/types'
import { createContext, useContext, type JSX } from 'solid-js'
import type { createCoreStoreSignal } from '@fex-design/solid/primitives/create-core-store-signal'

export interface CascaderContextValue {
  controller: ReturnType<typeof createCascaderController>
  snapshot: ReturnType<typeof createCoreStoreSignal>
  selectedPaths: () => readonly (readonly CascaderNode[])[]
  multiple: () => boolean
  expandTrigger: () => 'click' | 'hover'
  showSearch: () => boolean
  clearable: () => boolean
  disabled: () => boolean
  loading: () => boolean
  status: () => 'error' | 'warning' | undefined
  placeholder: () => string | undefined
  displayRender?: (labels: readonly string[], path: readonly CascaderOption[]) => JSX.Element
}

export const CascaderContext = createContext<CascaderContextValue>()

export function useCascader(part: string) {
  const value = useContext(CascaderContext)
  if (!value) throw new Error(`${part} must be used inside CascaderRoot.`)
  return value
}
