// packages/@fex-design/components/vue/src/ui/button/examples/states.vue
<script setup lang="ts">
import { Button } from '@fex-design/vue/ui/button'
</script>

<template>
  <div class="flex flex-wrap items-center gap-6">
    <Button>Default</Button>
    <Button>Hover / Focus</Button>
    <Button disabled>Disabled</Button>
    <Button aria-pressed="true">Pressed</Button>
  </div>
</template>

// packages/@fex-design/react/src/ui/button/examples/states.tsx
import { Button } from '@fex-design/react/ui/button'

export function StatesExample() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <Button>Default</Button>
      <Button>Hover / Focus</Button>
      <Button disabled>Disabled</Button>
      <Button aria-pressed="true">Pressed</Button>
    </div>
  )
}
