// packages/@fex-design/components/svelte/src/primitive/drawer/drawer-portal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useDrawer } from "./drawer-context";

  let {
    children,
    container,
    forceMount = false,
  }: {
    children?: Snippet;
    container?: HTMLElement | null;
    forceMount?: boolean;
  } = $props();
  const { snapshot, depth } = useDrawer("DrawerPortal");

  function portal(element: HTMLDivElement) {
    (container ?? document.body).appendChild(element);
    return { destroy: () => element.remove() };
  }
</script>

{#if $snapshot.mounted || forceMount}
  <div
    use:portal
    data-slot="drawer-portal"
    style:display="contents"
    style:--drawer-z-index={50 + depth * 2}
  >
    {@render children?.()}
  </div>
{/if}

// packages/@fex-design/vue/src/primitive/drawer/drawer-portal.vue
<script setup lang="ts">
import { Teleport } from 'vue'
import { useDrawerContext } from './context'
defineProps<{ container?: HTMLElement | null; forceMount?: boolean }>()
const { snapshot, depth } = useDrawerContext('DrawerPortal')
</script>
<template>
  <Teleport to="body"
    ><div
      v-if="snapshot.mounted || $props.forceMount"
      :style="{ display: 'contents', '--drawer-z-index': 50 + depth * 2 }"
    >
      <slot /></div
  ></Teleport>
</template>
