// packages/@fex-design/svelte/src/primitive/drawer/drawer-footer.svelte
<script lang="ts">
  import { drawerFooterClassName } from "@fex-design/styles/drawer";
  let {
    children,
    class: className = "",
  }: { children?: import("svelte").Snippet; class?: string } = $props();
</script>

<div class={`${drawerFooterClassName} ${className}`} data-slot="drawer-footer">
  {@render children?.()}
</div>

// packages/@fex-design/vue/src/primitive/drawer/drawer-footer.vue
<script setup lang="ts">
import { drawerFooterClassName } from '@fex-design/styles/drawer'
import { cn } from '@fex/utils'
defineProps<{ class?: string }>()
</script>
<template>
  <div v-bind="$attrs" data-slot="drawer-footer" :class="cn(drawerFooterClassName, $props.class)">
    <slot />
  </div>
</template>
