// packages/@fex-design/react/src/primitive/input-number/examples/controls.tsx
import {
  InputNumberActions,
  InputNumberClear,
  InputNumberControl,
  InputNumberDecrement,
  InputNumberIncrement,
  InputNumberRoot,
} from '@fex-design/react/primitive/input-number'
import { InputPrefix, InputSuffix } from '@fex-design/react/primitive/input'
export function ControlsExample() {
  return (
    <div className="grid w-full gap-3">
      <p>默认控制</p>
      <InputNumberRoot defaultValue={8}>
        <InputNumberControl />
        <InputNumberActions>
          <InputNumberIncrement />
          <InputNumberDecrement />
        </InputNumberActions>
      </InputNumberRoot>
      <p>隐藏控制</p>
      <InputNumberRoot defaultValue={8}>
        <InputNumberControl />
      </InputNumberRoot>
    </div>
  )
}

// packages/@fex-design/components/angular/src/primitive/input-number/examples/controls.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  InputNumberActions,
  InputNumberControl,
  InputNumberDecrement,
  InputNumberIncrement,
  InputNumberRoot,
} from '@fex-design/angular/primitive/input-number'
@Component({
  selector: 'input-number-primitive-controls-example',
  standalone: true,
  imports: [
    InputNumberRoot,
    InputNumberControl,
    InputNumberActions,
    InputNumberIncrement,
    InputNumberDecrement,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './controls.html',
})
export class ControlsExample {}
