// packages/@fex-design/react/src/primitive/button/examples/composition.tsx
import { PlusIcon } from '@fex-design/react/icon/plus'
import { Button, ButtonGroup, ButtonIcon } from '@fex-design/react/primitive/button'

export function CompositionExample() {
  return (
    <div className="flex flex-wrap items-center gap-3">
      <ButtonGroup spacing={8}>
        <Button>
          <ButtonIcon placement="start">
            <PlusIcon />
          </ButtonIcon>
          Add
        </Button>
        <Button aria-pressed="true">Selected</Button>
        <Button disabled>Disabled</Button>
      </ButtonGroup>
    </div>
  )
}

// packages/@fex-design/svelte/src/primitive/button/examples/composition.svelte
<script lang="ts">
  import PlusIcon from '@fex-design/svelte/icon/plus'
  import { Button, ButtonGroup, ButtonIcon } from '@fex-design/svelte/primitive/button'
</script>

<div class="flex flex-wrap items-center gap-3">
<ButtonGroup spacing={8}>
<Button>
<ButtonIcon placement="start">
<PlusIcon />
</ButtonIcon>Add</Button>
<Button aria-pressed="true">Selected</Button>
<Button disabled>Disabled</Button>
</ButtonGroup>
</div>
