// apps/svelte-app/src/routes/select/multi-field-search-demo.svelte
<script lang="ts">
  import { defaultSelectFilterOption } from "@fex-design/core/select/filter-options";
  import { frameworkOptions } from "./data";
  import Demo from "./simple-demo.svelte";
</script>

<Demo
  title="Multi-field search"
  description="Search label, searchText and keywords; try google or meta."
  items={frameworkOptions}
  showSearch
  filterOption={defaultSelectFilterOption}
/>

// apps/react-app/src/pages/Select/multi-field-search-demo.tsx
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import {
  SelectContent,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/react/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function MultiFieldSearchDemo() {
  return (
    <SelectDemoSection
      title="Multi-field search"
      description="Search label, searchText and keywords; try google or meta."
    >
      <SelectRoot showSearch items={frameworkOptions} filterOption={defaultSelectFilterOption}>
        <SelectTrigger placeholder="输入 google 或 meta" />
        <SelectContent />
      </SelectRoot>
    </SelectDemoSection>
  )
}
