// apps/vue-app/src/pages/Select/virtual-demo.vue
<script setup lang="ts">
import { SelectContent, SelectRoot, SelectTrigger } from '@fex-design/vue/primitive/select'
import { virtualOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Virtual scrolling"
    description="Only the visible fixed-height options and overscan are mounted from 1,000 entries."
    ><SelectRoot show-search :items="virtualOptions" :virtual="{ itemHeight: 32, overscan: 4 }"
      ><SelectTrigger placeholder="请输入关键词或选择选项" /><SelectContent /></SelectRoot
  ></Demo>
</template>

// apps/react-app/src/pages/Select/virtual-demo.tsx
import {
  SelectContent,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/react/primitive/select'
import { virtualOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function VirtualDemo() {
  return (
    <SelectDemoSection
      title="Virtual scrolling"
      description="Only the visible fixed-height options and overscan are mounted from 1,000 entries."
    >
      <SelectRoot showSearch items={virtualOptions} virtual={{ itemHeight: 32, overscan: 4 }}>
        <SelectTrigger placeholder="请输入关键词或选择选项" />
        <SelectContent />
      </SelectRoot>
    </SelectDemoSection>
  )
}
