// packages/@fex-design/solid/src/primitive/alert/alert.tsx
import type { AlertOptions } from '@fex-design/core/alert/types'
import {
  alertActionClassName,
  alertClassName,
  alertDescriptionClassName,
  alertIconClassName,
  alertTitleClassName,
} from '@fex-design/styles/alert'
import { cn } from '@fex/utils'
import type { JSX, ParentProps } from 'solid-js'
import { splitProps } from 'solid-js'

type DivProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

export type AlertProps = DivProps & AlertOptions

export function Alert(props: AlertProps) {
  const [local, rest] = splitProps(props, ['class', 'children', 'type', 'variant'])
  return (
    <div
      data-slot="alert"
      role="alert"
      {...rest}
      class={cn(
        alertClassName({ type: local.type ?? 'info', variant: local.variant ?? 'filled' }),
        local.class,
      )}
    >
      {local.children}
    </div>
  )
}

export type AlertIconProps = ParentProps<JSX.HTMLAttributes<HTMLSpanElement>>

export function AlertIcon(props: AlertIconProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <span {...rest} data-slot="alert-icon" class={cn(alertIconClassName, local.class)}>
      {local.children}
    </span>
  )
}

export function AlertTitle(props: DivProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <div {...rest} data-slot="alert-title" class={cn(alertTitleClassName, local.class)}>
      {local.children}
    </div>
  )
}

export function AlertDescription(props: DivProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <div {...rest} data-slot="alert-description" class={cn(alertDescriptionClassName, local.class)}>
      {local.children}
    </div>
  )
}

export function AlertAction(props: DivProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <div {...rest} data-slot="alert-action" class={cn(alertActionClassName, local.class)}>
      {local.children}
    </div>
  )
}

// packages/@fex-design/react/src/primitive/alert/alert.tsx
import type { AlertOptions } from '@fex-design/core/alert/types'
import {
  alertActionClassName,
  alertClassName,
  alertDescriptionClassName,
  alertIconClassName,
  alertTitleClassName,
} from '@fex-design/styles/alert'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'

export type AlertProps = ComponentProps<'div'> & AlertOptions

export function Alert({ className, type = 'info', variant = 'filled', ...props }: AlertProps) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={cn(alertClassName({ type, variant }), className)}
      {...props}
    />
  )
}

export type AlertIconProps = ComponentProps<'span'>

export function AlertIcon({ className, ...props }: AlertIconProps) {
  return <span data-slot="alert-icon" className={cn(alertIconClassName, className)} {...props} />
}

export function AlertTitle({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="alert-title" className={cn(alertTitleClassName, className)} {...props} />
}

export function AlertDescription({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-description"
      className={cn(alertDescriptionClassName, className)}
      {...props}
    />
  )
}

export function AlertAction({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="alert-action" className={cn(alertActionClassName, className)} {...props} />
}
