// apps/solid-app/src/pages/Select/clear-demo.tsx
import { SelectContent, SelectRoot, SelectTrigger } from '@fex-design/solid/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection as Demo } from './demo-section'
export function ClearDemo() {
  return (
    <Demo
      title="Clear"
      description="Clear and the dropdown indicator share one suffix position and never render together."
    >
      <SelectRoot clearable items={frameworkOptions} defaultValue="solid">
        <SelectTrigger placeholder="请选择" />
        <SelectContent />
      </SelectRoot>
    </Demo>
  )
}

// apps/vue-app/src/pages/Select/clear-demo.vue
<script setup lang="ts">
import { SelectContent, SelectRoot, SelectTrigger } from '@fex-design/vue/primitive/select'
import { frameworkOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Clear"
    description="Clear and the dropdown indicator share one suffix position and never render together."
    ><SelectRoot clearable default-value="solid" :items="frameworkOptions"
      ><SelectTrigger placeholder="请选择" /><SelectContent /></SelectRoot
  ></Demo>
</template>
