// packages/@fex-design/components/react/src/primitive/badge/badge-group.tsx
import { splitOverflowItems } from "@fex-design/core/collection/split-overflow-items"
import type { BadgeGroupOptions } from "@fex-design/core"
import {
  badgeClassName,
  badgeGroupClassName,
} from "@fex-design/components-styles/badge"
import { cn } from "@fex-design/utils"
import { Children, type ComponentProps, type ReactNode } from "react"

export interface BadgeGroupProps extends ComponentProps<"div">, BadgeGroupOptions {
  renderOverflow?: (count: number, items: readonly ReactNode[]) => ReactNode
}

export function BadgeGroup({
  maxCount,
  renderOverflow,
  className,
  children,
  ...props
}: BadgeGroupProps) {
  const split = splitOverflowItems(Children.toArray(children), maxCount)
  return (
    <div {...props} data-slot="badge-group" className={cn(badgeGroupClassName, className)}>
      {split.visibleItems}
      {split.overflowCount > 0 &&
        (renderOverflow?.(split.overflowCount, split.overflowItems) ?? (
          <span data-slot="badge" className={badgeClassName()}>
            +{split.overflowCount}
          </span>
        ))}
    </div>
  )
}

// packages/@fex-design/svelte/src/primitive/badge/badge-group.svelte
<script lang="ts" generics="T">
  import type { BadgeGroupOptions } from '@fex-design/core'
  import { splitOverflowItems } from '@fex-design/core/collection/split-overflow-items'
  import { badgeClassName, badgeGroupClassName } from '@fex-design/styles/badge'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  interface Props extends BadgeGroupOptions { items: readonly T[]; class?: string; item: Snippet<[T]>; overflow?: Snippet<[number, readonly T[]]> }
  let { items, maxCount, class: className, item, overflow }: Props = $props()
  const split = $derived(splitOverflowItems(items, maxCount))
</script>
<div data-slot="badge-group" class={cn(badgeGroupClassName, className)}>{#each split.visibleItems as entry, index (index)}{@render item(entry)}{/each}{#if split.overflowCount}{#if overflow}{@render overflow(split.overflowCount, split.overflowItems)}{:else}<span data-slot="badge" class={badgeClassName()}>+{split.overflowCount}</span>{/if}{/if}</div>
