// packages/@fex-design/vue/src/primitive/separator/examples/vertical.vue
<script setup lang="ts">
import { Separator } from '@fex-design/vue/primitive/separator'
import Card from '@fex-design/vue/ui/card'
const items = [
  ['Workspace', 'Fex Design'],
  ['Plan', 'Team'],
  ['Region', 'Asia Pacific'],
]
</script>
<template>
  <Card title="Vertical" description="Use vertical separators between compact inline items."
    ><div class="flex h-5 items-center gap-2">
      <span>Blog</span><Separator orientation="vertical" /><span>Docs</span
      ><Separator orientation="vertical" /><span>Source</span>
    </div></Card
  >
</template>

// packages/@fex-design/svelte/src/ui/separator/examples/vertical.svelte
<script lang="ts">
import Separator from '../../../primitive/separator/separator.svelte'
import Card from '@fex-design/svelte/ui/card'
</script>
<Card title="Vertical" description="Use vertical separators between compact inline items."><div class="flex h-5 items-center gap-2"><span>Blog</span><Separator orientation="vertical"/><span>Docs</span><Separator orientation="vertical"/><span>Source</span></div></Card>
