// packages/@fex-design/svelte/src/primitive/skeleton/skeleton-avatar.svelte
<script lang="ts">
  import type { SkeletonAvatarOptions } from '@fex-design/core/skeleton/types'
  import { skeletonAvatarClassName } from '@fex-design/styles/skeleton'
  import { cn } from '@fex/utils'
  import type { HTMLAttributes } from 'svelte/elements'
  import SkeletonBlock from './skeleton-block.svelte'
  let { class: className, shape, size, ...rest }: HTMLAttributes<HTMLDivElement> & SkeletonAvatarOptions = $props()
</script>
<SkeletonBlock {...rest} data-slot="skeleton-avatar" class={cn(skeletonAvatarClassName({ shape, size }), className)} />

// packages/@fex-design/react/src/primitive/skeleton/skeleton-avatar.tsx
import type { SkeletonAvatarOptions } from '@fex-design/core/skeleton/types'
import { skeletonAvatarClassName } from '@fex-design/styles/skeleton'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'
import { SkeletonBlock } from './skeleton-block'
export type SkeletonAvatarProps = ComponentProps<'div'> & SkeletonAvatarOptions
export function SkeletonAvatar({ className, shape, size, ...props }: SkeletonAvatarProps) {
  return (
    <SkeletonBlock
      data-slot="skeleton-avatar"
      className={cn(skeletonAvatarClassName({ shape, size }), className)}
      {...props}
    />
  )
}
