// packages/@fex-design/components/solid/src/primitive/data-table/data-table-row-overlay.tsx
import {
  getDataTableRenderedCells,
  getDataTableVisibleLeafColumns,
  type DataTableRenderingTableSource,
} from '@fex-design/core/data-table/layout'
import {
  dataTableCellClassName,
  dataTableCellContentClassName,
  dataTableRootClassName,
  dataTableRowClassName,
  dataTableClassName,
} from '@fex-design/components-styles/data-table'
import type { Row, RowData, Table, TableFeatures } from '@tanstack/table-core'
import { For, type JSX } from 'solid-js'

function renderTemplate(template: unknown, context: unknown): JSX.Element {
  return typeof template === 'function'
    ? (template(context) as JSX.Element)
    : (template as JSX.Element)
}

export interface DataTableRowOverlayProps<TFeatures extends TableFeatures, TData extends RowData> {
  table: Table<TFeatures, TData>
  row: Row<TFeatures, TData>
  style: JSX.CSSProperties
  density?: 'compact' | 'default' | 'comfortable'
}

export function DataTableRowOverlay<TFeatures extends TableFeatures, TData extends RowData>(
  props: DataTableRowOverlayProps<TFeatures, TData>,
) {
  const source = props.table as unknown as DataTableRenderingTableSource
  const columns = () => getDataTableVisibleLeafColumns(source)
  return (
    <div
      data-slot="data-table-row-overlay"
      class={dataTableRootClassName({ density: props.density ?? 'default' })}
      style={props.style}
    >
      <table class={dataTableClassName}>
        <colgroup>
          <For each={columns()}>
            {(column) => (
              <col
                style={{
                  width: column.getSize?.() === undefined ? undefined : `${column.getSize?.()}px`,
                }}
              />
            )}
          </For>
        </colgroup>
        <tbody>
          <tr class={dataTableRowClassName}>
            <For each={getDataTableRenderedCells(props.row)}>
              {(cell) => (
                <td class={dataTableCellClassName}>
                  <div class={dataTableCellContentClassName}>
                    {renderTemplate(cell.column.columnDef.cell, cell.getContext())}
                  </div>
                </td>
              )}
            </For>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

// packages/@fex-design/components/vue/src/primitive/data-table/data-table-row-overlay.vue
<script setup lang="ts" generic="TFeatures extends TableFeatures, TData extends RowData">
import {
  getDataTableRenderedCells,
  getDataTableVisibleLeafColumns,
  type DataTableRenderingTableSource,
} from '@fex-design/core/data-table/layout'
import {
  dataTableCellClassName,
  dataTableCellContentClassName,
  dataTableRootClassName,
  dataTableRowClassName,
  dataTableClassName,
} from '@fex-design/components-styles/data-table'
import type { Row, RowData, Table, TableFeatures } from '@tanstack/table-core'
import type { CSSProperties } from 'vue'
import { DataTableTemplate } from './data-table-template'
const props = withDefaults(
  defineProps<{
    table: Table<TFeatures, TData>
    row: Row<TFeatures, TData>
    style: CSSProperties
    density?: 'compact' | 'default' | 'comfortable'
  }>(),
  { density: 'default' },
)
const source = props.table as unknown as DataTableRenderingTableSource
const columns = () => getDataTableVisibleLeafColumns(source)
</script>
<template>
  <div
    data-slot="data-table-row-overlay"
    :class="dataTableRootClassName({ density: props.density })"
    :style="props.style"
  >
    <table :class="dataTableClassName">
      <colgroup>
        <col
          v-for="column in columns()"
          :key="column.id"
          :style="{
            width: column.getSize?.() === undefined ? undefined : `${column.getSize?.()}px`,
          }"
        />
      </colgroup>
      <tbody>
        <tr :class="dataTableRowClassName">
          <td
            v-for="cell in getDataTableRenderedCells(props.row)"
            :key="cell.id"
            :class="dataTableCellClassName"
          >
            <div :class="dataTableCellContentClassName">
              <DataTableTemplate
                :template="cell.column.columnDef.cell"
                :context="cell.getContext()"
              />
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
